package com.servinglynk.report.bean;

import java.math.BigInteger;

public class Q19a2ClientCashIncomeChangeIncomeSourceByEntryDataBean {
		
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomeTotalAdult;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomePerformanceMeasures;
	private BigInteger q19a2NoOfAdltsWithEarnedIncomePercent;
		
	private BigInteger q19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	private BigInteger q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	private BigInteger q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	private BigInteger q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	private BigInteger q19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	private BigInteger q19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	private BigInteger q19a2AverageChangeInEarnedIncomeTotalAdult;
	private BigInteger q19a2AverageChangeInEarnedIncomePerformanceMeasures;
	private BigInteger q19a2AverageChangeInEarnedIncomePercent;
		
	private BigInteger q19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	private BigInteger q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	private BigInteger q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	private BigInteger q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	private BigInteger q19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	private BigInteger q19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	private BigInteger q19a2NoOfAdultsWithOtherIncomeTotalAdult;
	private BigInteger q19a2NoOfAdultsWithOtherIncomePerformanceMeasures;
	private BigInteger q19a2NoOfAdultsWithOtherIncomePercent;
		
	private BigInteger q19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	private BigInteger q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	private BigInteger q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	private BigInteger q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	private BigInteger q19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	private BigInteger q19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	private BigInteger q19a2AverageChangeInOtherIncomeTotalAdult;
	private BigInteger q19a2AverageChangeInOtherIncomePerformanceMeasures;
	private BigInteger q19a2AverageChangeInOtherIncomePercent;
		
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomeTotalAdult;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomePerformanceMeasures;
	private BigInteger q19a2NumberOfAdultsWithAnyIncomePercent;
		
	private BigInteger q19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	private BigInteger q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	private BigInteger q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	private BigInteger q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	private BigInteger q19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	private BigInteger q19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	private BigInteger q19a2AverageChangeInOverallIncomeTotalAdult;
	private BigInteger q19a2AverageChangeInOverallIncomePerformanceMeasures;
	private BigInteger q19a2AverageChangeInOverallIncomePercent;
	
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit() {
		return q19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit) {
		this.q19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit = q19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry() {
		return q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry) {
		this.q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry = q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry() {
		return q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry) {
		this.q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry = q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit() {
		return q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit) {
		this.q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit = q19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit() {
		return q19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit) {
		this.q19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit = q19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit() {
		return q19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit) {
		this.q19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit = q19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomeTotalAdult() {
		return q19a2NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomeTotalAdult(
			BigInteger q19a2NoOfAdltsWithEarnedIncomeTotalAdult) {
		this.q19a2NoOfAdltsWithEarnedIncomeTotalAdult = q19a2NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomePerformanceMeasures() {
		return q19a2NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomePerformanceMeasures(
			BigInteger q19a2NoOfAdltsWithEarnedIncomePerformanceMeasures) {
		this.q19a2NoOfAdltsWithEarnedIncomePerformanceMeasures = q19a2NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public BigInteger getQ19a2NoOfAdltsWithEarnedIncomePercent() {
		return q19a2NoOfAdltsWithEarnedIncomePercent;
	}
	public void setQ19a2NoOfAdltsWithEarnedIncomePercent(
			BigInteger q19a2NoOfAdltsWithEarnedIncomePercent) {
		this.q19a2NoOfAdltsWithEarnedIncomePercent = q19a2NoOfAdltsWithEarnedIncomePercent;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit() {
		return q19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public void setQ19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(
			BigInteger q19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit) {
		this.q19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit = q19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry() {
		return q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public void setQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(
			BigInteger q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry) {
		this.q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry = q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry() {
		return q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public void setQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(
			BigInteger q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry) {
		this.q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry = q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit() {
		return q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public void setQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(
			BigInteger q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit) {
		this.q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit = q19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit() {
		return q19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public void setQ19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(
			BigInteger q19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit) {
		this.q19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit = q19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit() {
		return q19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public void setQ19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit(
			BigInteger q19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit) {
		this.q19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit = q19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomeTotalAdult() {
		return q19a2AverageChangeInEarnedIncomeTotalAdult;
	}
	public void setQ19a2AverageChangeInEarnedIncomeTotalAdult(
			BigInteger q19a2AverageChangeInEarnedIncomeTotalAdult) {
		this.q19a2AverageChangeInEarnedIncomeTotalAdult = q19a2AverageChangeInEarnedIncomeTotalAdult;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomePerformanceMeasures() {
		return q19a2AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public void setQ19a2AverageChangeInEarnedIncomePerformanceMeasures(
			BigInteger q19a2AverageChangeInEarnedIncomePerformanceMeasures) {
		this.q19a2AverageChangeInEarnedIncomePerformanceMeasures = q19a2AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public BigInteger getQ19a2AverageChangeInEarnedIncomePercent() {
		return q19a2AverageChangeInEarnedIncomePercent;
	}
	public void setQ19a2AverageChangeInEarnedIncomePercent(
			BigInteger q19a2AverageChangeInEarnedIncomePercent) {
		this.q19a2AverageChangeInEarnedIncomePercent = q19a2AverageChangeInEarnedIncomePercent;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit() {
		return q19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(
			BigInteger q19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit) {
		this.q19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit = q19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry() {
		return q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(
			BigInteger q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry) {
		this.q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry = q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry() {
		return q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(
			BigInteger q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry) {
		this.q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry = q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit() {
		return q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(
			BigInteger q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit) {
		this.q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit = q19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit() {
		return q19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(
			BigInteger q19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit) {
		this.q19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit = q19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit() {
		return q19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit(
			BigInteger q19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit) {
		this.q19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit = q19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomeTotalAdult() {
		return q19a2NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomeTotalAdult(
			BigInteger q19a2NoOfAdultsWithOtherIncomeTotalAdult) {
		this.q19a2NoOfAdultsWithOtherIncomeTotalAdult = q19a2NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomePerformanceMeasures() {
		return q19a2NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomePerformanceMeasures(
			BigInteger q19a2NoOfAdultsWithOtherIncomePerformanceMeasures) {
		this.q19a2NoOfAdultsWithOtherIncomePerformanceMeasures = q19a2NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public BigInteger getQ19a2NoOfAdultsWithOtherIncomePercent() {
		return q19a2NoOfAdultsWithOtherIncomePercent;
	}
	public void setQ19a2NoOfAdultsWithOtherIncomePercent(
			BigInteger q19a2NoOfAdultsWithOtherIncomePercent) {
		this.q19a2NoOfAdultsWithOtherIncomePercent = q19a2NoOfAdultsWithOtherIncomePercent;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit() {
		return q19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public void setQ19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(
			BigInteger q19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit) {
		this.q19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit = q19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry() {
		return q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public void setQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(
			BigInteger q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry) {
		this.q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry = q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry() {
		return q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public void setQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(
			BigInteger q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry) {
		this.q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry = q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit() {
		return q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public void setQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(
			BigInteger q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit) {
		this.q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit = q19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit() {
		return q19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public void setQ19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(
			BigInteger q19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit) {
		this.q19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit = q19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit() {
		return q19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public void setQ19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit(
			BigInteger q19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit) {
		this.q19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit = q19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomeTotalAdult() {
		return q19a2AverageChangeInOtherIncomeTotalAdult;
	}
	public void setQ19a2AverageChangeInOtherIncomeTotalAdult(
			BigInteger q19a2AverageChangeInOtherIncomeTotalAdult) {
		this.q19a2AverageChangeInOtherIncomeTotalAdult = q19a2AverageChangeInOtherIncomeTotalAdult;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomePerformanceMeasures() {
		return q19a2AverageChangeInOtherIncomePerformanceMeasures;
	}
	public void setQ19a2AverageChangeInOtherIncomePerformanceMeasures(
			BigInteger q19a2AverageChangeInOtherIncomePerformanceMeasures) {
		this.q19a2AverageChangeInOtherIncomePerformanceMeasures = q19a2AverageChangeInOtherIncomePerformanceMeasures;
	}
	public BigInteger getQ19a2AverageChangeInOtherIncomePercent() {
		return q19a2AverageChangeInOtherIncomePercent;
	}
	public void setQ19a2AverageChangeInOtherIncomePercent(
			BigInteger q19a2AverageChangeInOtherIncomePercent) {
		this.q19a2AverageChangeInOtherIncomePercent = q19a2AverageChangeInOtherIncomePercent;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit() {
		return q19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit) {
		this.q19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit = q19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry() {
		return q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry) {
		this.q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry = q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry() {
		return q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry) {
		this.q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry = q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit() {
		return q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit) {
		this.q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit = q19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit() {
		return q19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit) {
		this.q19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit = q19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit() {
		return q19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit) {
		this.q19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit = q19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomeTotalAdult() {
		return q19a2NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomeTotalAdult(
			BigInteger q19a2NumberOfAdultsWithAnyIncomeTotalAdult) {
		this.q19a2NumberOfAdultsWithAnyIncomeTotalAdult = q19a2NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomePerformanceMeasures() {
		return q19a2NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomePerformanceMeasures(
			BigInteger q19a2NumberOfAdultsWithAnyIncomePerformanceMeasures) {
		this.q19a2NumberOfAdultsWithAnyIncomePerformanceMeasures = q19a2NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public BigInteger getQ19a2NumberOfAdultsWithAnyIncomePercent() {
		return q19a2NumberOfAdultsWithAnyIncomePercent;
	}
	public void setQ19a2NumberOfAdultsWithAnyIncomePercent(
			BigInteger q19a2NumberOfAdultsWithAnyIncomePercent) {
		this.q19a2NumberOfAdultsWithAnyIncomePercent = q19a2NumberOfAdultsWithAnyIncomePercent;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit() {
		return q19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public void setQ19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(
			BigInteger q19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit) {
		this.q19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit = q19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry() {
		return q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public void setQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(
			BigInteger q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry) {
		this.q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry = q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry() {
		return q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public void setQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(
			BigInteger q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry) {
		this.q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry = q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit() {
		return q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public void setQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(
			BigInteger q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit) {
		this.q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit = q19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit() {
		return q19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public void setQ19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(
			BigInteger q19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit) {
		this.q19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit = q19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit() {
		return q19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public void setQ19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit(
			BigInteger q19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit) {
		this.q19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit = q19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomeTotalAdult() {
		return q19a2AverageChangeInOverallIncomeTotalAdult;
	}
	public void setQ19a2AverageChangeInOverallIncomeTotalAdult(
			BigInteger q19a2AverageChangeInOverallIncomeTotalAdult) {
		this.q19a2AverageChangeInOverallIncomeTotalAdult = q19a2AverageChangeInOverallIncomeTotalAdult;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomePerformanceMeasures() {
		return q19a2AverageChangeInOverallIncomePerformanceMeasures;
	}
	public void setQ19a2AverageChangeInOverallIncomePerformanceMeasures(
			BigInteger q19a2AverageChangeInOverallIncomePerformanceMeasures) {
		this.q19a2AverageChangeInOverallIncomePerformanceMeasures = q19a2AverageChangeInOverallIncomePerformanceMeasures;
	}
	public BigInteger getQ19a2AverageChangeInOverallIncomePercent() {
		return q19a2AverageChangeInOverallIncomePercent;
	}
	public void setQ19a2AverageChangeInOverallIncomePercent(
			BigInteger q19a2AverageChangeInOverallIncomePercent) {
		this.q19a2AverageChangeInOverallIncomePercent = q19a2AverageChangeInOverallIncomePercent;
	}
	
	
}
