package com.servinglynk.report.bean;

import java.math.BigInteger;

public class Q19a3ClientCashIncomeChangeIncomeSourceByEntryDataBean {
	
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdltsWithEarnedIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger q19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInEarnedIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger q19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger q19a3NoOfAdultsWithOtherIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger q19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOtherIncomePercent=BigInteger.valueOf(0);

	private BigInteger q19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger q19a3NumberOfAdultsWithAnyIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger q19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger q19a3AverageChangeInOverallIncomePercent=BigInteger.valueOf(0);
	
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit() {
		return q19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit) {
		this.q19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit = q19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry() {
		return q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry) {
		this.q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry = q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry() {
		return q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry) {
		this.q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry = q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit() {
		return q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit) {
		this.q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit = q19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit() {
		return q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit) {
		this.q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit = q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit() {
		return q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit) {
		this.q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit = q19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomeTotalAdult() {
		return q19a3NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomeTotalAdult(
			BigInteger q19a3NoOfAdltsWithEarnedIncomeTotalAdult) {
		this.q19a3NoOfAdltsWithEarnedIncomeTotalAdult = q19a3NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomePerformanceMeasures() {
		return q19a3NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomePerformanceMeasures(
			BigInteger q19a3NoOfAdltsWithEarnedIncomePerformanceMeasures) {
		this.q19a3NoOfAdltsWithEarnedIncomePerformanceMeasures = q19a3NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public BigInteger getQ19a3NoOfAdltsWithEarnedIncomePercent() {
		return q19a3NoOfAdltsWithEarnedIncomePercent;
	}
	public void setQ19a3NoOfAdltsWithEarnedIncomePercent(
			BigInteger q19a3NoOfAdltsWithEarnedIncomePercent) {
		this.q19a3NoOfAdltsWithEarnedIncomePercent = q19a3NoOfAdltsWithEarnedIncomePercent;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit() {
		return q19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public void setQ19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(
			BigInteger q19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit) {
		this.q19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit = q19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry() {
		return q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public void setQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(
			BigInteger q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry) {
		this.q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry = q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry() {
		return q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public void setQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(
			BigInteger q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry) {
		this.q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry = q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit() {
		return q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public void setQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(
			BigInteger q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit) {
		this.q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit = q19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit() {
		return q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public void setQ19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(
			BigInteger q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit) {
		this.q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit = q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit() {
		return q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public void setQ19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(
			BigInteger q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit) {
		this.q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit = q19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomeTotalAdult() {
		return q19a3AverageChangeInEarnedIncomeTotalAdult;
	}
	public void setQ19a3AverageChangeInEarnedIncomeTotalAdult(
			BigInteger q19a3AverageChangeInEarnedIncomeTotalAdult) {
		this.q19a3AverageChangeInEarnedIncomeTotalAdult = q19a3AverageChangeInEarnedIncomeTotalAdult;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomePerformanceMeasures() {
		return q19a3AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public void setQ19a3AverageChangeInEarnedIncomePerformanceMeasures(
			BigInteger q19a3AverageChangeInEarnedIncomePerformanceMeasures) {
		this.q19a3AverageChangeInEarnedIncomePerformanceMeasures = q19a3AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public BigInteger getQ19a3AverageChangeInEarnedIncomePercent() {
		return q19a3AverageChangeInEarnedIncomePercent;
	}
	public void setQ19a3AverageChangeInEarnedIncomePercent(
			BigInteger q19a3AverageChangeInEarnedIncomePercent) {
		this.q19a3AverageChangeInEarnedIncomePercent = q19a3AverageChangeInEarnedIncomePercent;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit() {
		return q19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(
			BigInteger q19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit) {
		this.q19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit = q19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry() {
		return q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(
			BigInteger q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry) {
		this.q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry = q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry() {
		return q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(
			BigInteger q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry) {
		this.q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry = q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit() {
		return q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(
			BigInteger q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit) {
		this.q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit = q19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit() {
		return q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(
			BigInteger q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit) {
		this.q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit = q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit() {
		return q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(
			BigInteger q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit) {
		this.q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit = q19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomeTotalAdult() {
		return q19a3NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomeTotalAdult(
			BigInteger q19a3NoOfAdultsWithOtherIncomeTotalAdult) {
		this.q19a3NoOfAdultsWithOtherIncomeTotalAdult = q19a3NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomePerformanceMeasures() {
		return q19a3NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomePerformanceMeasures(
			BigInteger q19a3NoOfAdultsWithOtherIncomePerformanceMeasures) {
		this.q19a3NoOfAdultsWithOtherIncomePerformanceMeasures = q19a3NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public BigInteger getQ19a3NoOfAdultsWithOtherIncomePercent() {
		return q19a3NoOfAdultsWithOtherIncomePercent;
	}
	public void setQ19a3NoOfAdultsWithOtherIncomePercent(
			BigInteger q19a3NoOfAdultsWithOtherIncomePercent) {
		this.q19a3NoOfAdultsWithOtherIncomePercent = q19a3NoOfAdultsWithOtherIncomePercent;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit() {
		return q19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public void setQ19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(
			BigInteger q19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit) {
		this.q19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit = q19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry() {
		return q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public void setQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(
			BigInteger q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry) {
		this.q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry = q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry() {
		return q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public void setQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(
			BigInteger q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry) {
		this.q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry = q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit() {
		return q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public void setQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(
			BigInteger q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit) {
		this.q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit = q19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit() {
		return q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public void setQ19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(
			BigInteger q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit) {
		this.q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit = q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit() {
		return q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public void setQ19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(
			BigInteger q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit) {
		this.q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit = q19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomeTotalAdult() {
		return q19a3AverageChangeInOtherIncomeTotalAdult;
	}
	public void setQ19a3AverageChangeInOtherIncomeTotalAdult(
			BigInteger q19a3AverageChangeInOtherIncomeTotalAdult) {
		this.q19a3AverageChangeInOtherIncomeTotalAdult = q19a3AverageChangeInOtherIncomeTotalAdult;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomePerformanceMeasures() {
		return q19a3AverageChangeInOtherIncomePerformanceMeasures;
	}
	public void setQ19a3AverageChangeInOtherIncomePerformanceMeasures(
			BigInteger q19a3AverageChangeInOtherIncomePerformanceMeasures) {
		this.q19a3AverageChangeInOtherIncomePerformanceMeasures = q19a3AverageChangeInOtherIncomePerformanceMeasures;
	}
	public BigInteger getQ19a3AverageChangeInOtherIncomePercent() {
		return q19a3AverageChangeInOtherIncomePercent;
	}
	public void setQ19a3AverageChangeInOtherIncomePercent(
			BigInteger q19a3AverageChangeInOtherIncomePercent) {
		this.q19a3AverageChangeInOtherIncomePercent = q19a3AverageChangeInOtherIncomePercent;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit() {
		return q19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit) {
		this.q19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit = q19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry() {
		return q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry) {
		this.q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry = q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry() {
		return q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry) {
		this.q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry = q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit() {
		return q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit) {
		this.q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit = q19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit() {
		return q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit) {
		this.q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit = q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit() {
		return q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit) {
		this.q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit = q19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomeTotalAdult() {
		return q19a3NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomeTotalAdult(
			BigInteger q19a3NumberOfAdultsWithAnyIncomeTotalAdult) {
		this.q19a3NumberOfAdultsWithAnyIncomeTotalAdult = q19a3NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomePerformanceMeasures() {
		return q19a3NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomePerformanceMeasures(
			BigInteger q19a3NumberOfAdultsWithAnyIncomePerformanceMeasures) {
		this.q19a3NumberOfAdultsWithAnyIncomePerformanceMeasures = q19a3NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public BigInteger getQ19a3NumberOfAdultsWithAnyIncomePercent() {
		return q19a3NumberOfAdultsWithAnyIncomePercent;
	}
	public void setQ19a3NumberOfAdultsWithAnyIncomePercent(
			BigInteger q19a3NumberOfAdultsWithAnyIncomePercent) {
		this.q19a3NumberOfAdultsWithAnyIncomePercent = q19a3NumberOfAdultsWithAnyIncomePercent;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit() {
		return q19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public void setQ19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(
			BigInteger q19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit) {
		this.q19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit = q19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry() {
		return q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public void setQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(
			BigInteger q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry) {
		this.q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry = q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry() {
		return q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public void setQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(
			BigInteger q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry) {
		this.q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry = q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit() {
		return q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public void setQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(
			BigInteger q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit) {
		this.q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit = q19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit() {
		return q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public void setQ19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(
			BigInteger q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit) {
		this.q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit = q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit() {
		return q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public void setQ19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(
			BigInteger q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit) {
		this.q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit = q19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomeTotalAdult() {
		return q19a3AverageChangeInOverallIncomeTotalAdult;
	}
	public void setQ19a3AverageChangeInOverallIncomeTotalAdult(
			BigInteger q19a3AverageChangeInOverallIncomeTotalAdult) {
		this.q19a3AverageChangeInOverallIncomeTotalAdult = q19a3AverageChangeInOverallIncomeTotalAdult;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomePerformanceMeasures() {
		return q19a3AverageChangeInOverallIncomePerformanceMeasures;
	}
	public void setQ19a3AverageChangeInOverallIncomePerformanceMeasures(
			BigInteger q19a3AverageChangeInOverallIncomePerformanceMeasures) {
		this.q19a3AverageChangeInOverallIncomePerformanceMeasures = q19a3AverageChangeInOverallIncomePerformanceMeasures;
	}
	public BigInteger getQ19a3AverageChangeInOverallIncomePercent() {
		return q19a3AverageChangeInOverallIncomePercent;
	}
	public void setQ19a3AverageChangeInOverallIncomePercent(
			BigInteger q19a3AverageChangeInOverallIncomePercent) {
		this.q19a3AverageChangeInOverallIncomePercent = q19a3AverageChangeInOverallIncomePercent;
	}

	
}
