package com.servinglynk.report.bean;

import java.math.BigInteger;

public class Q19a1ClientCashIncomeChangeIncomeSourceEntryDataBean {
	
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomeTotalAdult;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomePerformanceMeasures;
	private BigInteger q19a1NoOfAdltsWithEarnedIncomePercent;

	private BigInteger q19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	private BigInteger q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	private BigInteger q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	private BigInteger q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	private BigInteger q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	private BigInteger q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	private BigInteger q19a1AverageChangeInEarnedIncomeTotalAdult;
	private BigInteger q19a1AverageChangeInEarnedIncomePerformanceMeasures;
	private BigInteger q19a1AverageChangeInEarnedIncomePercent;
		
	private BigInteger q19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	private BigInteger q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	private BigInteger q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar;
	private BigInteger q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	private BigInteger q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	private BigInteger q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	private BigInteger q19a1NoOfAdultsWithOtherIncomeTotalAdult;
	private BigInteger q19a1NoOfAdultsWithOtherIncomePerformanceMeasures;
	private BigInteger q19a1NoOfAdultsWithOtherIncomePercent;
		
	private BigInteger q19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	private BigInteger q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	private BigInteger q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar;
	private BigInteger q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	private BigInteger q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	private BigInteger q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	private BigInteger q19a1AverageChangeInOtherIncomeTotalAdult;
	private BigInteger q19a1AverageChangeInOtherIncomePerformanceMeasures;
	private BigInteger q19a1AverageChangeInOtherIncomePercent;
		
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomeTotalAdult;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomePerformanceMeasures;
	private BigInteger q19a1NumberOfAdultsWithAnyIncomePercent;
		
	private BigInteger q19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	private BigInteger q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar;
	private BigInteger q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar;
	private BigInteger q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar;
	private BigInteger q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	private BigInteger q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	private BigInteger q19a1AverageChangeInOverallIncomeTotalAdult;
	private BigInteger q19a1AverageChangeInOverallIncomePerformanceMeasures;
	private BigInteger q19a1AverageChangeInOverallIncomePercent;
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return q19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.q19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = q19a1NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar() {
		return q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar = q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar() {
		return q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar) {
		this.q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar = q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar = q19a1NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = q19a1NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomeTotalAdult() {
		return q19a1NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomeTotalAdult(
			BigInteger q19a1NoOfAdltsWithEarnedIncomeTotalAdult) {
		this.q19a1NoOfAdltsWithEarnedIncomeTotalAdult = q19a1NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomePerformanceMeasures() {
		return q19a1NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomePerformanceMeasures(
			BigInteger q19a1NoOfAdltsWithEarnedIncomePerformanceMeasures) {
		this.q19a1NoOfAdltsWithEarnedIncomePerformanceMeasures = q19a1NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public BigInteger getQ19a1NoOfAdltsWithEarnedIncomePercent() {
		return q19a1NoOfAdltsWithEarnedIncomePercent;
	}
	public void setQ19a1NoOfAdltsWithEarnedIncomePercent(
			BigInteger q19a1NoOfAdltsWithEarnedIncomePercent) {
		this.q19a1NoOfAdltsWithEarnedIncomePercent = q19a1NoOfAdltsWithEarnedIncomePercent;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return q19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setQ19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger q19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.q19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = q19a1AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar() {
		return q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setQ19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar = q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar() {
		return q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setQ19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar) {
		this.q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar = q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setQ19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar = q19a1AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setQ19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setQ19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = q19a1AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomeTotalAdult() {
		return q19a1AverageChangeInEarnedIncomeTotalAdult;
	}
	public void setQ19a1AverageChangeInEarnedIncomeTotalAdult(
			BigInteger q19a1AverageChangeInEarnedIncomeTotalAdult) {
		this.q19a1AverageChangeInEarnedIncomeTotalAdult = q19a1AverageChangeInEarnedIncomeTotalAdult;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomePerformanceMeasures() {
		return q19a1AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public void setQ19a1AverageChangeInEarnedIncomePerformanceMeasures(
			BigInteger q19a1AverageChangeInEarnedIncomePerformanceMeasures) {
		this.q19a1AverageChangeInEarnedIncomePerformanceMeasures = q19a1AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public BigInteger getQ19a1AverageChangeInEarnedIncomePercent() {
		return q19a1AverageChangeInEarnedIncomePercent;
	}
	public void setQ19a1AverageChangeInEarnedIncomePercent(
			BigInteger q19a1AverageChangeInEarnedIncomePercent) {
		this.q19a1AverageChangeInEarnedIncomePercent = q19a1AverageChangeInEarnedIncomePercent;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return q19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger q19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.q19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = q19a1NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar() {
		return q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar = q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar() {
		return q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar) {
		this.q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar = q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar = q19a1NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = q19a1NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomeTotalAdult() {
		return q19a1NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomeTotalAdult(
			BigInteger q19a1NoOfAdultsWithOtherIncomeTotalAdult) {
		this.q19a1NoOfAdultsWithOtherIncomeTotalAdult = q19a1NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomePerformanceMeasures() {
		return q19a1NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomePerformanceMeasures(
			BigInteger q19a1NoOfAdultsWithOtherIncomePerformanceMeasures) {
		this.q19a1NoOfAdultsWithOtherIncomePerformanceMeasures = q19a1NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public BigInteger getQ19a1NoOfAdultsWithOtherIncomePercent() {
		return q19a1NoOfAdultsWithOtherIncomePercent;
	}
	public void setQ19a1NoOfAdultsWithOtherIncomePercent(
			BigInteger q19a1NoOfAdultsWithOtherIncomePercent) {
		this.q19a1NoOfAdultsWithOtherIncomePercent = q19a1NoOfAdultsWithOtherIncomePercent;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return q19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setQ19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger q19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.q19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = q19a1AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar() {
		return q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setQ19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar = q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar() {
		return q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setQ19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar) {
		this.q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar = q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setQ19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar = q19a1AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setQ19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setQ19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = q19a1AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomeTotalAdult() {
		return q19a1AverageChangeInOtherIncomeTotalAdult;
	}
	public void setQ19a1AverageChangeInOtherIncomeTotalAdult(
			BigInteger q19a1AverageChangeInOtherIncomeTotalAdult) {
		this.q19a1AverageChangeInOtherIncomeTotalAdult = q19a1AverageChangeInOtherIncomeTotalAdult;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomePerformanceMeasures() {
		return q19a1AverageChangeInOtherIncomePerformanceMeasures;
	}
	public void setQ19a1AverageChangeInOtherIncomePerformanceMeasures(
			BigInteger q19a1AverageChangeInOtherIncomePerformanceMeasures) {
		this.q19a1AverageChangeInOtherIncomePerformanceMeasures = q19a1AverageChangeInOtherIncomePerformanceMeasures;
	}
	public BigInteger getQ19a1AverageChangeInOtherIncomePercent() {
		return q19a1AverageChangeInOtherIncomePercent;
	}
	public void setQ19a1AverageChangeInOtherIncomePercent(
			BigInteger q19a1AverageChangeInOtherIncomePercent) {
		this.q19a1AverageChangeInOtherIncomePercent = q19a1AverageChangeInOtherIncomePercent;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return q19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.q19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = q19a1NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar() {
		return q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar = q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar() {
		return q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar) {
		this.q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar = q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar = q19a1NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = q19a1NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomeTotalAdult() {
		return q19a1NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomeTotalAdult(
			BigInteger q19a1NumberOfAdultsWithAnyIncomeTotalAdult) {
		this.q19a1NumberOfAdultsWithAnyIncomeTotalAdult = q19a1NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomePerformanceMeasures() {
		return q19a1NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomePerformanceMeasures(
			BigInteger q19a1NumberOfAdultsWithAnyIncomePerformanceMeasures) {
		this.q19a1NumberOfAdultsWithAnyIncomePerformanceMeasures = q19a1NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public BigInteger getQ19a1NumberOfAdultsWithAnyIncomePercent() {
		return q19a1NumberOfAdultsWithAnyIncomePercent;
	}
	public void setQ19a1NumberOfAdultsWithAnyIncomePercent(
			BigInteger q19a1NumberOfAdultsWithAnyIncomePercent) {
		this.q19a1NumberOfAdultsWithAnyIncomePercent = q19a1NumberOfAdultsWithAnyIncomePercent;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return q19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setQ19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger q19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.q19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = q19a1AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar() {
		return q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setQ19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar = q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar() {
		return q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setQ19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar) {
		this.q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar = q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setQ19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar = q19a1AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setQ19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setQ19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = q19a1AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomeTotalAdult() {
		return q19a1AverageChangeInOverallIncomeTotalAdult;
	}
	public void setQ19a1AverageChangeInOverallIncomeTotalAdult(
			BigInteger q19a1AverageChangeInOverallIncomeTotalAdult) {
		this.q19a1AverageChangeInOverallIncomeTotalAdult = q19a1AverageChangeInOverallIncomeTotalAdult;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomePerformanceMeasures() {
		return q19a1AverageChangeInOverallIncomePerformanceMeasures;
	}
	public void setQ19a1AverageChangeInOverallIncomePerformanceMeasures(
			BigInteger q19a1AverageChangeInOverallIncomePerformanceMeasures) {
		this.q19a1AverageChangeInOverallIncomePerformanceMeasures = q19a1AverageChangeInOverallIncomePerformanceMeasures;
	}
	public BigInteger getQ19a1AverageChangeInOverallIncomePercent() {
		return q19a1AverageChangeInOverallIncomePercent;
	}
	public void setQ19a1AverageChangeInOverallIncomePercent(
			BigInteger q19a1AverageChangeInOverallIncomePercent) {
		this.q19a1AverageChangeInOverallIncomePercent = q19a1AverageChangeInOverallIncomePercent;
	}

	
}
