  
package com.servinglynk.report.bean;

import java.math.BigInteger;

public class Q19DataBean {
	
	private BigInteger NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger NoOfAdltsWithEarnedIncomePercent=BigInteger.valueOf(0);

	private BigInteger AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger AverageChangeInEarnedIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger NoOfAdultsWithOtherIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOtherIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger NumberOfAdultsWithAnyIncomePercent=BigInteger.valueOf(0);
		
	private BigInteger AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomeTotalAdult=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomePerformanceMeasures=BigInteger.valueOf(0);
	private BigInteger AverageChangeInOverallIncomePercent=BigInteger.valueOf(0);
	public BigInteger getNoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setNoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar() {
		return NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setNoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar = NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar() {
		return NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setNoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar) {
		this.NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar = NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setNoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar = NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setNoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setNoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomeTotalAdult() {
		return NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public void setNoOfAdltsWithEarnedIncomeTotalAdult(
			BigInteger NoOfAdltsWithEarnedIncomeTotalAdult) {
		this.NoOfAdltsWithEarnedIncomeTotalAdult = NoOfAdltsWithEarnedIncomeTotalAdult;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomePerformanceMeasures() {
		return NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public void setNoOfAdltsWithEarnedIncomePerformanceMeasures(
			BigInteger NoOfAdltsWithEarnedIncomePerformanceMeasures) {
		this.NoOfAdltsWithEarnedIncomePerformanceMeasures = NoOfAdltsWithEarnedIncomePerformanceMeasures;
	}
	public BigInteger getNoOfAdltsWithEarnedIncomePercent() {
		return NoOfAdltsWithEarnedIncomePercent;
	}
	public void setNoOfAdltsWithEarnedIncomePercent(
			BigInteger NoOfAdltsWithEarnedIncomePercent) {
		this.NoOfAdltsWithEarnedIncomePercent = NoOfAdltsWithEarnedIncomePercent;
	}
	public BigInteger getAverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setAverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getAverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar() {
		return AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setAverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar = AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getAverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar() {
		return AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setAverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar) {
		this.AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar = AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getAverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setAverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar = AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getAverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setAverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getAverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setAverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getAverageChangeInEarnedIncomeTotalAdult() {
		return AverageChangeInEarnedIncomeTotalAdult;
	}
	public void setAverageChangeInEarnedIncomeTotalAdult(
			BigInteger AverageChangeInEarnedIncomeTotalAdult) {
		this.AverageChangeInEarnedIncomeTotalAdult = AverageChangeInEarnedIncomeTotalAdult;
	}
	public BigInteger getAverageChangeInEarnedIncomePerformanceMeasures() {
		return AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public void setAverageChangeInEarnedIncomePerformanceMeasures(
			BigInteger AverageChangeInEarnedIncomePerformanceMeasures) {
		this.AverageChangeInEarnedIncomePerformanceMeasures = AverageChangeInEarnedIncomePerformanceMeasures;
	}
	public BigInteger getAverageChangeInEarnedIncomePercent() {
		return AverageChangeInEarnedIncomePercent;
	}
	public void setAverageChangeInEarnedIncomePercent(
			BigInteger AverageChangeInEarnedIncomePercent) {
		this.AverageChangeInEarnedIncomePercent = AverageChangeInEarnedIncomePercent;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setNoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar() {
		return NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setNoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar = NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar() {
		return NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setNoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar) {
		this.NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar = NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setNoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar = NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setNoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setNoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getNoOfAdultsWithOtherIncomeTotalAdult() {
		return NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public void setNoOfAdultsWithOtherIncomeTotalAdult(
			BigInteger NoOfAdultsWithOtherIncomeTotalAdult) {
		this.NoOfAdultsWithOtherIncomeTotalAdult = NoOfAdultsWithOtherIncomeTotalAdult;
	}
	public BigInteger getNoOfAdultsWithOtherIncomePerformanceMeasures() {
		return NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public void setNoOfAdultsWithOtherIncomePerformanceMeasures(
			BigInteger NoOfAdultsWithOtherIncomePerformanceMeasures) {
		this.NoOfAdultsWithOtherIncomePerformanceMeasures = NoOfAdultsWithOtherIncomePerformanceMeasures;
	}
	public BigInteger getNoOfAdultsWithOtherIncomePercent() {
		return NoOfAdultsWithOtherIncomePercent;
	}
	public void setNoOfAdultsWithOtherIncomePercent(
			BigInteger NoOfAdultsWithOtherIncomePercent) {
		this.NoOfAdultsWithOtherIncomePercent = NoOfAdultsWithOtherIncomePercent;
	}
	public BigInteger getAverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setAverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getAverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar() {
		return AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setAverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar = AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getAverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar() {
		return AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setAverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar) {
		this.AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar = AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getAverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setAverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar = AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getAverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setAverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getAverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setAverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getAverageChangeInOtherIncomeTotalAdult() {
		return AverageChangeInOtherIncomeTotalAdult;
	}
	public void setAverageChangeInOtherIncomeTotalAdult(
			BigInteger AverageChangeInOtherIncomeTotalAdult) {
		this.AverageChangeInOtherIncomeTotalAdult = AverageChangeInOtherIncomeTotalAdult;
	}
	public BigInteger getAverageChangeInOtherIncomePerformanceMeasures() {
		return AverageChangeInOtherIncomePerformanceMeasures;
	}
	public void setAverageChangeInOtherIncomePerformanceMeasures(
			BigInteger AverageChangeInOtherIncomePerformanceMeasures) {
		this.AverageChangeInOtherIncomePerformanceMeasures = AverageChangeInOtherIncomePerformanceMeasures;
	}
	public BigInteger getAverageChangeInOtherIncomePercent() {
		return AverageChangeInOtherIncomePercent;
	}
	public void setAverageChangeInOtherIncomePercent(
			BigInteger AverageChangeInOtherIncomePercent) {
		this.AverageChangeInOtherIncomePercent = AverageChangeInOtherIncomePercent;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setNumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar() {
		return NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setNumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar = NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar() {
		return NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setNumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar) {
		this.NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar = NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setNumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar = NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setNumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setNumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomeTotalAdult() {
		return NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public void setNumberOfAdultsWithAnyIncomeTotalAdult(
			BigInteger NumberOfAdultsWithAnyIncomeTotalAdult) {
		this.NumberOfAdultsWithAnyIncomeTotalAdult = NumberOfAdultsWithAnyIncomeTotalAdult;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomePerformanceMeasures() {
		return NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public void setNumberOfAdultsWithAnyIncomePerformanceMeasures(
			BigInteger NumberOfAdultsWithAnyIncomePerformanceMeasures) {
		this.NumberOfAdultsWithAnyIncomePerformanceMeasures = NumberOfAdultsWithAnyIncomePerformanceMeasures;
	}
	public BigInteger getNumberOfAdultsWithAnyIncomePercent() {
		return NumberOfAdultsWithAnyIncomePercent;
	}
	public void setNumberOfAdultsWithAnyIncomePercent(
			BigInteger NumberOfAdultsWithAnyIncomePercent) {
		this.NumberOfAdultsWithAnyIncomePercent = NumberOfAdultsWithAnyIncomePercent;
	}
	public BigInteger getAverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup() {
		return AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public void setAverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup(
			BigInteger AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup) {
		this.AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup = AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndNotHaveFollowup;
	}
	public BigInteger getAverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar() {
		return AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public void setAverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar(
			BigInteger AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar) {
		this.AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar = AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollar;
	}
	public BigInteger getAverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar() {
		return AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public void setAverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar(
			BigInteger AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar) {
		this.AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar = AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollar;
	}
	public BigInteger getAverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar() {
		return AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public void setAverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar(
			BigInteger AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar) {
		this.AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar = AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollar;
	}
	public BigInteger getAverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome() {
		return AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public void setAverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome(
			BigInteger AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome) {
		this.AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome = AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedTheIncome;
	}
	public BigInteger getAverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup() {
		return AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public void setAverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup(
			BigInteger AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup) {
		this.AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup = AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryOrFollowup;
	}
	public BigInteger getAverageChangeInOverallIncomeTotalAdult() {
		return AverageChangeInOverallIncomeTotalAdult;
	}
	public void setAverageChangeInOverallIncomeTotalAdult(
			BigInteger AverageChangeInOverallIncomeTotalAdult) {
		this.AverageChangeInOverallIncomeTotalAdult = AverageChangeInOverallIncomeTotalAdult;
	}
	public BigInteger getAverageChangeInOverallIncomePerformanceMeasures() {
		return AverageChangeInOverallIncomePerformanceMeasures;
	}
	public void setAverageChangeInOverallIncomePerformanceMeasures(
			BigInteger AverageChangeInOverallIncomePerformanceMeasures) {
		this.AverageChangeInOverallIncomePerformanceMeasures = AverageChangeInOverallIncomePerformanceMeasures;
	}
	public BigInteger getAverageChangeInOverallIncomePercent() {
		return AverageChangeInOverallIncomePercent;
	}
	public void setAverageChangeInOverallIncomePercent(
			BigInteger AverageChangeInOverallIncomePercent) {
		this.AverageChangeInOverallIncomePercent = AverageChangeInOverallIncomePercent;
	}
}
