CREATE EXTERNAL TABLE IF NOT EXISTS picklist_group(id string ,picklist_group_name string ,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:picklist_group_name,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "picklist_group_survey");
CREATE EXTERNAL TABLE IF NOT EXISTS picklist_value(id string ,picklist_value_code string ,created_at timestamp,  updated_at timestamp,user_id string,is_active string,value_text string,picklist_group_id string ) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:picklist_value_code,CF:created_at,CF:updated_at,CF:user_id,CF:is_active,CF:picklist_value_code,CF:picklist_group_id") TBLPROPERTIES ("hbase.table.name" = "picklist_value_survey");
CREATE EXTERNAL TABLE IF NOT EXISTS question_group(id string ,question_group_name string ,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:question_group_name,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "question_group");
CREATE EXTERNAL TABLE IF NOT EXISTS section_question_mapping(id string,is_required string,question_id string,question_group_id string,section_id string,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:is_required,CF:question_id,CF:question_group_id,CF:section_id,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "section_question_mapping_survey");
CREATE EXTERNAL TABLE IF NOT EXISTS section_score(id string ,section_score string ,survey_id string,section_id string,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:section_score,CF:survey_id,CF:section_id,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "section_score_survey");
CREATE EXTERNAL TABLE IF NOT EXISTS survey(id string ,project_group_code string ,survey_title string,survey_owner string,locked string,is_copy_survey_id string,tag_value string,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:project_group_code,CF:survey_title,CF:survey_owner,CF:locked,CF:is_copy_survey_id,CF:tag_value,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "survey_survey");
CREATE EXTERNAL TABLE IF NOT EXISTS survey_section(id string ,survey_id string ,section_text string,section_detail string,section_weight string,section_order string,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,CF:survey_id,CF:section_text ,CF:section_detail,CF:section_weight,CF:section_order,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "survey_section_survey");


CREATE EXTERNAL TABLE IF NOT EXISTS question(id string ,project_group_id string ,question_description string,display_text string,question_data_type string,
question_type string,correct_value_for_assessment string,hud_question string,locked string,question_weight string,question_group_id string,picklist_group_id string,
is_copy_question_id string,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES 
("hbase.columns.mapping" = ":key,CF:project_group_id,CF:question_description,CF:display_text,CF:question_data_type,CF:question_type,CF:correct_value_for_assessment,CF:hud_question,CF:locked,
CF:question_weight,CF:question_group_id,CF:picklist_group_id,CF:is_copy_question_id,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "question_survey");

CREATE EXTERNAL TABLE IF NOT EXISTS response(id string ,response_text string ,question_score string,app_id string,effective_date date,
section_id string,question_id string,client_id string,survey_id string,refused string,created_at timestamp,  updated_at timestamp,user_id string,is_active string) STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' WITH SERDEPROPERTIES 
("hbase.columns.mapping" = ":key,CF:response_text,CF:question_score,CF:app_id,CF:effective_date,CF:section_id,CF:question_id,CF:client_id,CF:survey_id,CF:refused,CF:created_at,CF:updated_at,CF:user_id,CF:is_active") TBLPROPERTIES ("hbase.table.name" = "response_survey");

