package com.servinglynk.hmis.warehouse.model.base;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.servinglynk.hmis.warehouse.enums.ClientDobDataQualityEnum;
import com.servinglynk.hmis.warehouse.enums.ClientEthnicityEnum;
import com.servinglynk.hmis.warehouse.enums.ClientGenderEnum;
import com.servinglynk.hmis.warehouse.enums.ClientNameDataQualityEnum;
import com.servinglynk.hmis.warehouse.enums.ClientRaceEnum;
import com.servinglynk.hmis.warehouse.enums.ClientSsnDataQualityEnum;
import com.servinglynk.hmis.warehouse.enums.ClientVeteranStatusEnum;
import com.servinglynk.hmis.warehouse.enums.HashStatusEnum;


/**
 * Object mapping for hibernate-handled table: client.
 *
 *
 * @author autogenerated
 */
//@Entity
//@Table(name = "client", catalog = "hmis", schema = "base")
@Document(indexName = "client",type = "com.servinglynk.hmis.warehouse.model.base.Client",shards = 10)
@JsonRootName("client")
@JsonNaming(value = PropertyNamingStrategy.LowerCaseStrategy.class)
@Component
public class Client implements Cloneable, Serializable {

	private static final long serialVersionUID = 6304318647555713317L;
	@org.springframework.data.annotation.Id
	private String id;
	@Field(name ="dedupclientid",fielddata = true,type = FieldType.Text)
	private String dedupclientid;
	private ClientDobDataQualityEnum dobDataQuality;
	private ClientEthnicityEnum ethnicity;
	@Field(name="firstname",fielddata = true,type = FieldType.Text)
	private String firstname;
	private ClientGenderEnum gender;
	@Field(name="lastname",fielddata = true,type = FieldType.Text)
	private String lastname;
	@Field(name="middlename",fielddata = true,type = FieldType.Text)
	private String middlename;
	private ClientNameDataQualityEnum namedataquality;
	@Field(name="namesuffix",fielddata = true,type = FieldType.Text)
	private String namesuffix;
	@Field(name="othergender",fielddata = true,type = FieldType.Text)
	private String othergender;
	private ClientRaceEnum race;
	@Field(name="ssn",fielddata = true,type = FieldType.Text)
	private String ssn;
	private ClientSsnDataQualityEnum ssndataquality;
	private ClientVeteranStatusEnum veteranstatus;
	private HashStatusEnum firstnamehashstatus;
	private HashStatusEnum lastnamehashstatus;
	private HashStatusEnum middlenamehashstatus;
	private HashStatusEnum ssnhashstatus;
//	@Field(fielddata = true,type = FieldType.Date,format = DateFormat.basic_date)
	private Date dob;
	@Field(name="sourcesystemid",fielddata = true,type = FieldType.Text)
	private String sourcesystemid;
	@Field(name="schemayear",fielddata = true,type = FieldType.Text)
	private String schemayear;
	@Field(name="phonenumber",fielddata = true,type = FieldType.Text)
	private String phonenumber;
	@Field(name="emailaddress",fielddata = true,type = FieldType.Text)
	private String emailaddress;	
	protected Date datecreated = new Date();
	//@Field(fielddata = true,type = FieldType.Date)
	protected Date dateupdated = new Date();
	protected Date datecreatedfromsource;
	protected Date dateupdatedfromsource;
	@Field(name="projectgroupcode",fielddata = true,type = FieldType.Text)
	protected String projectgroupcode;
	private HmisUser user;
	private boolean deleted;
	private boolean sync;
	private UUID parentid;
	private Long version;
	@Field(name="fullname",fielddata = true,type = FieldType.Text)
	private String fullname;
	@Field(name="name",fielddata = true,type = FieldType.Text)
	private String name;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getDedupclientid() {
		return dedupclientid;
	}
	public void setDedupclientid(String dedupclientid) {
		this.dedupclientid = dedupclientid;
	}
	public ClientDobDataQualityEnum getDobDataQuality() {
		return dobDataQuality;
	}
	public void setDobDataQuality(ClientDobDataQualityEnum dobDataQuality) {
		this.dobDataQuality = dobDataQuality;
	}
	public ClientEthnicityEnum getEthnicity() {
		return ethnicity;
	}
	public void setEthnicity(ClientEthnicityEnum ethnicity) {
		this.ethnicity = ethnicity;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public ClientGenderEnum getGender() {
		return gender;
	}
	public void setGender(ClientGenderEnum gender) {
		this.gender = gender;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getMiddlename() {
		return middlename;
	}
	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}
	public ClientNameDataQualityEnum getNamedataquality() {
		return namedataquality;
	}
	public void setNamedataquality(ClientNameDataQualityEnum namedataquality) {
		this.namedataquality = namedataquality;
	}
	public String getNamesuffix() {
		return namesuffix;
	}
	public void setNamesuffix(String namesuffix) {
		this.namesuffix = namesuffix;
	}
	public String getOthergender() {
		return othergender;
	}
	public void setOthergender(String othergender) {
		this.othergender = othergender;
	}
	public ClientRaceEnum getRace() {
		return race;
	}
	public void setRace(ClientRaceEnum race) {
		this.race = race;
	}
	public String getSsn() {
		return ssn;
	}
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}
	public ClientSsnDataQualityEnum getSsndataquality() {
		return ssndataquality;
	}
	public void setSsndataquality(ClientSsnDataQualityEnum ssndataquality) {
		this.ssndataquality = ssndataquality;
	}
	public ClientVeteranStatusEnum getVeteranstatus() {
		return veteranstatus;
	}
	public void setVeteranstatus(ClientVeteranStatusEnum veteranstatus) {
		this.veteranstatus = veteranstatus;
	}
	public HashStatusEnum getFirstnamehashstatus() {
		return firstnamehashstatus;
	}
	public void setFirstnamehashstatus(HashStatusEnum firstnamehashstatus) {
		this.firstnamehashstatus = firstnamehashstatus;
	}
	public HashStatusEnum getLastnamehashstatus() {
		return lastnamehashstatus;
	}
	public void setLastnamehashstatus(HashStatusEnum lastnamehashstatus) {
		this.lastnamehashstatus = lastnamehashstatus;
	}
	public HashStatusEnum getMiddlenamehashstatus() {
		return middlenamehashstatus;
	}
	public void setMiddlenamehashstatus(HashStatusEnum middlenamehashstatus) {
		this.middlenamehashstatus = middlenamehashstatus;
	}
	public HashStatusEnum getSsnhashstatus() {
		return ssnhashstatus;
	}
	public void setSsnhashstatus(HashStatusEnum ssnhashstatus) {
		this.ssnhashstatus = ssnhashstatus;
	}
	public Date getDob() {
		return dob;
	}
	public void setDob(Date dob) {
		this.dob = dob;
	}
	public String getSourcesystemid() {
		return sourcesystemid;
	}
	public void setSourcesystemid(String sourcesystemid) {
		this.sourcesystemid = sourcesystemid;
	}
	public String getSchemayear() {
		return schemayear;
	}
	public void setSchemayear(String schemayear) {
		this.schemayear = schemayear;
	}
	public String getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}
	public String getEmailaddress() {
		return emailaddress;
	}
	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}
	public Date getDatecreated() {
		return datecreated;
	}
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}
	public Date getDateupdated() {
		return dateupdated;
	}
	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}
	public Date getDatecreatedfromsource() {
		return datecreatedfromsource;
	}
	public void setDatecreatedfromsource(Date datecreatedfromsource) {
		this.datecreatedfromsource = datecreatedfromsource;
	}
	public Date getDateupdatedfromsource() {
		return dateupdatedfromsource;
	}
	public void setDateupdatedfromsource(Date dateupdatedfromsource) {
		this.dateupdatedfromsource = dateupdatedfromsource;
	}
	public String getProjectgroupcode() {
		return projectgroupcode;
	}
	public void setProjectgroupcode(String projectgroupcode) {
		this.projectgroupcode = projectgroupcode;
	}
	public HmisUser getUser() {
		return user;
	}
	public void setUser(HmisUser user) {
		this.user = user;
	}
	public boolean isDeleted() {
		return deleted;
	}
	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	public boolean isSync() {
		return sync;
	}
	public void setSync(boolean sync) {
		this.sync = sync;
	}
	public UUID getParentid() {
		return parentid;
	}
	public void setParentid(UUID parentid) {
		this.parentid = parentid;
	}
	public Long getVersion() {
		return version;
	}
	public void setVersion(Long version) {
		this.version = version;
	}
	public String getFullname() {
		return fullname;
	}
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}