package com.servinglynk.hmis.warehouse.model.stagv2015;

import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;

/**
 * Object mapping for hibernate-handled table: entryrhy.
 *
 *
 * @author autogenerated
 */


@Entity (name = "entryrhy_stagv2015")
@Table(name = "entryrhy", catalog = "hmis", schema = "stagv2015")
public class Entryrhy extends HmisBaseStagingModel implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = 7937252363949404166L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, java.util.UUID> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, java.util.UUID>());

	/** hashCode temporary storage. */
	private volatile java.util.UUID hashCode;


	/** Field mapping. */
	private Integer abuseAndNeglectFamilyMbr;
	/** Field mapping. */
	private Integer abuseAndNeglectYouth;
	/** Field mapping. */
	private Integer activeMilitaryParent;
	/** Field mapping. */
	private Integer alcoholDrugAbuseFamilyMbr;
	/** Field mapping. */
	private Integer alcoholDrugAbuseYouth;
	/** Field mapping. */
	private Integer askedOfForcedToExchangeForSex;
	/** Field mapping. */
	private Integer askedOfForcedToExchangeForSexPastThreeMonths;
	/** Field mapping. */
	private Integer coercedToContinueWork;
	/** Field mapping. */
	private Integer countOfExchangeForSex;
	/** Field mapping. */
	private Integer countOutReachReferralApproaches;
	/** Field mapping. */
	private Enrollment enrollmentid;
	/** Field mapping. */
	private Integer exchangeForSex;
	/** Field mapping. */
	private Integer exchangeForSexPastThreeMonths;
	/** Field mapping. */
	private Integer formerlyWardChildWelfrForestCare;
	/** Field mapping. */
	private Integer formerlyWardOfJuvenileJustice;
	/** Field mapping. */
	private Integer healthIssuesFamilyMbr;
	/** Field mapping. */
	private Integer healthIssuesYouth;
	/** Field mapping. */
	private Integer houseHoldDynamics;
	/** Field mapping. */
	private Integer housingIssuesFamilyMbr;
	/** Field mapping. */
	private Integer housingIssuesYouth;
	/** Field mapping. */
	private java.util.UUID id;
	/** Field mapping. */
	private Integer incarceratedParent;
	/** Field mapping. */
	private Integer incarceratedParentStatus;
	/** Field mapping. */
	private Integer insufficientIncomeToSupportYouth;
	/** Field mapping. */
	private Integer laborExploitPastThreeMonths;
	/** Field mapping. */
	private Integer mentalDisabilityFamilyMbr;
	/** Field mapping. */
	private Integer mentalDisabilityYouth;
	/** Field mapping. */
	private Integer mentalHealthIssuesFamilyMbr;
	/** Field mapping. */
	private Integer mentalHealthIssuesYouth;
	/** Field mapping. */
	private Integer monthsChildWelfrForestCare;
	/** Field mapping. */
	private Integer physicalDisabilityFamilyMbr;
	/** Field mapping. */
	private Integer physicalDisabilityYouth;
	/** Field mapping. */
	private Integer referralSource;
	/** Field mapping. */
	private Integer schoolEducationIssuesFamilyMbr;
	/** Field mapping. */
	private Integer schoolEducationIssuesYouth;
	/** Field mapping. */
	private Integer sexualOrientatiionGenderIdentityFamilyMbr;
	/** Field mapping. */
	private Integer sexualOrientatiionGenderIdentityYouth;
	/** Field mapping. */
	private Integer sexualOrientation;
	/** Field mapping. */
	private Integer unemployementFamilyMbr;
	/** Field mapping. */
	private Integer unemployementYouth;
	/** Field mapping. */
	private Integer workPlacePromiseDifference;
	/** Field mapping. */
	private Integer workPlaceViolenceThreat;
	/** Field mapping. */
	private Integer yearsChildWelfrForestCare;
	/** Field mapping. */
	private Integer yearsJuvenileJustice;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Entryrhy() {
		// Default constructor
	}

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Entryrhy(java.util.UUID id) {
		this.id = id;
	}





	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Entryrhy.class;
	}


	 /**
	 * Return the value associated with the column: abuseAndNeglectFamilyMbr.
	 * @return A Integer object (this.abuseAndNeglectFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "abuse_and_neglect_family_mbr"  )
	public Integer getAbuseAndNeglectFamilyMbr() {
		return this.abuseAndNeglectFamilyMbr;

	}



	 /**
	 * Set the value related to the column: abuseAndNeglectFamilyMbr.
	 * @param abuseAndNeglectFamilyMbr the abuseAndNeglectFamilyMbr value you wish to set
	 */
	public void setAbuseAndNeglectFamilyMbr(final Integer abuseAndNeglectFamilyMbr) {
		this.abuseAndNeglectFamilyMbr = abuseAndNeglectFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: abuseAndNeglectYouth.
	 * @return A Integer object (this.abuseAndNeglectYouth)
	 */
	@Basic( optional = true )
	@Column( name = "abuse_and_neglect_youth"  )
	public Integer getAbuseAndNeglectYouth() {
		return this.abuseAndNeglectYouth;

	}



	 /**
	 * Set the value related to the column: abuseAndNeglectYouth.
	 * @param abuseAndNeglectYouth the abuseAndNeglectYouth value you wish to set
	 */
	public void setAbuseAndNeglectYouth(final Integer abuseAndNeglectYouth) {
		this.abuseAndNeglectYouth = abuseAndNeglectYouth;
	}

	 /**
	 * Return the value associated with the column: activeMilitaryParent.
	 * @return A Integer object (this.activeMilitaryParent)
	 */
	@Basic( optional = true )
	@Column( name = "active_military_parent"  )
	public Integer getActiveMilitaryParent() {
		return this.activeMilitaryParent;

	}



	 /**
	 * Set the value related to the column: activeMilitaryParent.
	 * @param activeMilitaryParent the activeMilitaryParent value you wish to set
	 */
	public void setActiveMilitaryParent(final Integer activeMilitaryParent) {
		this.activeMilitaryParent = activeMilitaryParent;
	}

	 /**
	 * Return the value associated with the column: alcoholDrugAbuseFamilyMbr.
	 * @return A Integer object (this.alcoholDrugAbuseFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "alcohol_drug_abuse_family_mbr"  )
	public Integer getAlcoholDrugAbuseFamilyMbr() {
		return this.alcoholDrugAbuseFamilyMbr;

	}



	 /**
	 * Set the value related to the column: alcoholDrugAbuseFamilyMbr.
	 * @param alcoholDrugAbuseFamilyMbr the alcoholDrugAbuseFamilyMbr value you wish to set
	 */
	public void setAlcoholDrugAbuseFamilyMbr(final Integer alcoholDrugAbuseFamilyMbr) {
		this.alcoholDrugAbuseFamilyMbr = alcoholDrugAbuseFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: alcoholDrugAbuseYouth.
	 * @return A Integer object (this.alcoholDrugAbuseYouth)
	 */
	@Basic( optional = true )
	@Column( name = "alcohol_drug_abuse_youth"  )
	public Integer getAlcoholDrugAbuseYouth() {
		return this.alcoholDrugAbuseYouth;

	}



	 /**
	 * Set the value related to the column: alcoholDrugAbuseYouth.
	 * @param alcoholDrugAbuseYouth the alcoholDrugAbuseYouth value you wish to set
	 */
	public void setAlcoholDrugAbuseYouth(final Integer alcoholDrugAbuseYouth) {
		this.alcoholDrugAbuseYouth = alcoholDrugAbuseYouth;
	}

	 /**
	 * Return the value associated with the column: askedOfForcedToExchangeForSex.
	 * @return A Integer object (this.askedOfForcedToExchangeForSex)
	 */
	@Basic( optional = true )
	@Column( name = "asked_of_forced_to_exchange_for_sex"  )
	public Integer getAskedOfForcedToExchangeForSex() {
		return this.askedOfForcedToExchangeForSex;

	}



	 /**
	 * Set the value related to the column: askedOfForcedToExchangeForSex.
	 * @param askedOfForcedToExchangeForSex the askedOfForcedToExchangeForSex value you wish to set
	 */
	public void setAskedOfForcedToExchangeForSex(final Integer askedOfForcedToExchangeForSex) {
		this.askedOfForcedToExchangeForSex = askedOfForcedToExchangeForSex;
	}

	 /**
	 * Return the value associated with the column: askedOfForcedToExchangeForSexPastThreeMonths.
	 * @return A Integer object (this.askedOfForcedToExchangeForSexPastThreeMonths)
	 */
	@Basic( optional = true )
	@Column( name = "asked_of_forced_to_exchange_for_sex_past_three_months"  )
	public Integer getAskedOfForcedToExchangeForSexPastThreeMonths() {
		return this.askedOfForcedToExchangeForSexPastThreeMonths;

	}



	 /**
	 * Set the value related to the column: askedOfForcedToExchangeForSexPastThreeMonths.
	 * @param askedOfForcedToExchangeForSexPastThreeMonths the askedOfForcedToExchangeForSexPastThreeMonths value you wish to set
	 */
	public void setAskedOfForcedToExchangeForSexPastThreeMonths(final Integer askedOfForcedToExchangeForSexPastThreeMonths) {
		this.askedOfForcedToExchangeForSexPastThreeMonths = askedOfForcedToExchangeForSexPastThreeMonths;
	}

	 /**
	 * Return the value associated with the column: coercedToContinueWork.
	 * @return A Integer object (this.coercedToContinueWork)
	 */
	@Basic( optional = true )
	@Column( name = "coerced_to_continue_work"  )
	public Integer getCoercedToContinueWork() {
		return this.coercedToContinueWork;

	}



	 /**
	 * Set the value related to the column: coercedToContinueWork.
	 * @param coercedToContinueWork the coercedToContinueWork value you wish to set
	 */
	public void setCoercedToContinueWork(final Integer coercedToContinueWork) {
		this.coercedToContinueWork = coercedToContinueWork;
	}

	 /**
	 * Return the value associated with the column: countOfExchangeForSex.
	 * @return A Integer object (this.countOfExchangeForSex)
	 */
	@Basic( optional = true )
	@Column( name = "count_of_exchange_for_sex"  )
	public Integer getCountOfExchangeForSex() {
		return this.countOfExchangeForSex;

	}



	 /**
	 * Set the value related to the column: countOfExchangeForSex.
	 * @param countOfExchangeForSex the countOfExchangeForSex value you wish to set
	 */
	public void setCountOfExchangeForSex(final Integer countOfExchangeForSex) {
		this.countOfExchangeForSex = countOfExchangeForSex;
	}

	 /**
	 * Return the value associated with the column: countOutReachReferralApproaches.
	 * @return A Integer object (this.countOutReachReferralApproaches)
	 */
	@Basic( optional = true )
	@Column( name = "count_out_reach_referral_approaches"  )
	public Integer getCountOutReachReferralApproaches() {
		return this.countOutReachReferralApproaches;

	}



	 /**
	 * Set the value related to the column: countOutReachReferralApproaches.
	 * @param countOutReachReferralApproaches the countOutReachReferralApproaches value you wish to set
	 */
	public void setCountOutReachReferralApproaches(final Integer countOutReachReferralApproaches) {
		this.countOutReachReferralApproaches = countOutReachReferralApproaches;
	}

	 /**
	 * Return the value associated with the column: enrollmentid.
	 * @return A Enrollment object (this.enrollmentid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = true )
	@JoinColumn(name = "enrollmentid", nullable = true )
	public Enrollment getEnrollmentid() {
		return this.enrollmentid;

	}



	 /**
	 * Set the value related to the column: enrollmentid.
	 * @param enrollmentid the enrollmentid value you wish to set
	 */
	public void setEnrollmentid(final Enrollment enrollmentid) {
		this.enrollmentid = enrollmentid;
	}

	 /**
	 * Return the value associated with the column: exchangeForSex.
	 * @return A Integer object (this.exchangeForSex)
	 */
	@Basic( optional = true )
	@Column( name = "exchange_for_sex"  )
	public Integer getExchangeForSex() {
		return this.exchangeForSex;

	}



	 /**
	 * Set the value related to the column: exchangeForSex.
	 * @param exchangeForSex the exchangeForSex value you wish to set
	 */
	public void setExchangeForSex(final Integer exchangeForSex) {
		this.exchangeForSex = exchangeForSex;
	}

	 /**
	 * Return the value associated with the column: exchangeForSexPastThreeMonths.
	 * @return A Integer object (this.exchangeForSexPastThreeMonths)
	 */
	@Basic( optional = true )
	@Column( name = "exchange_for_sex_past_three_months"  )
	public Integer getExchangeForSexPastThreeMonths() {
		return this.exchangeForSexPastThreeMonths;

	}



	 /**
	 * Set the value related to the column: exchangeForSexPastThreeMonths.
	 * @param exchangeForSexPastThreeMonths the exchangeForSexPastThreeMonths value you wish to set
	 */
	public void setExchangeForSexPastThreeMonths(final Integer exchangeForSexPastThreeMonths) {
		this.exchangeForSexPastThreeMonths = exchangeForSexPastThreeMonths;
	}
	 /**
	 * Return the value associated with the column: formerlyWardChildWelfrForestCare.
	 * @return A Integer object (this.formerlyWardChildWelfrForestCare)
	 */
	@Basic( optional = true )
	@Column( name = "formerly_ward_child_welfr_forest_care"  )
	public Integer getFormerlyWardChildWelfrForestCare() {
		return this.formerlyWardChildWelfrForestCare;

	}



	 /**
	 * Set the value related to the column: formerlyWardChildWelfrForestCare.
	 * @param formerlyWardChildWelfrForestCare the formerlyWardChildWelfrForestCare value you wish to set
	 */
	public void setFormerlyWardChildWelfrForestCare(final Integer formerlyWardChildWelfrForestCare) {
		this.formerlyWardChildWelfrForestCare = formerlyWardChildWelfrForestCare;
	}

	 /**
	 * Return the value associated with the column: formerlyWardOfJuvenileJustice.
	 * @return A Integer object (this.formerlyWardOfJuvenileJustice)
	 */
	@Basic( optional = true )
	@Column( name = "formerly_ward_of_juvenile_justice"  )
	public Integer getFormerlyWardOfJuvenileJustice() {
		return this.formerlyWardOfJuvenileJustice;

	}



	 /**
	 * Set the value related to the column: formerlyWardOfJuvenileJustice.
	 * @param formerlyWardOfJuvenileJustice the formerlyWardOfJuvenileJustice value you wish to set
	 */
	public void setFormerlyWardOfJuvenileJustice(final Integer formerlyWardOfJuvenileJustice) {
		this.formerlyWardOfJuvenileJustice = formerlyWardOfJuvenileJustice;
	}

	 /**
	 * Return the value associated with the column: healthIssuesFamilyMbr.
	 * @return A Integer object (this.healthIssuesFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "health_issues_family_mbr"  )
	public Integer getHealthIssuesFamilyMbr() {
		return this.healthIssuesFamilyMbr;

	}



	 /**
	 * Set the value related to the column: healthIssuesFamilyMbr.
	 * @param healthIssuesFamilyMbr the healthIssuesFamilyMbr value you wish to set
	 */
	public void setHealthIssuesFamilyMbr(final Integer healthIssuesFamilyMbr) {
		this.healthIssuesFamilyMbr = healthIssuesFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: healthIssuesYouth.
	 * @return A Integer object (this.healthIssuesYouth)
	 */
	@Basic( optional = true )
	@Column( name = "health_issues_youth"  )
	public Integer getHealthIssuesYouth() {
		return this.healthIssuesYouth;

	}



	 /**
	 * Set the value related to the column: healthIssuesYouth.
	 * @param healthIssuesYouth the healthIssuesYouth value you wish to set
	 */
	public void setHealthIssuesYouth(final Integer healthIssuesYouth) {
		this.healthIssuesYouth = healthIssuesYouth;
	}

	 /**
	 * Return the value associated with the column: houseHoldDynamics.
	 * @return A Integer object (this.houseHoldDynamics)
	 */
	@Basic( optional = true )
	@Column( name = "house_hold_dynamics"  )
	public Integer getHouseHoldDynamics() {
		return this.houseHoldDynamics;

	}



	 /**
	 * Set the value related to the column: houseHoldDynamics.
	 * @param houseHoldDynamics the houseHoldDynamics value you wish to set
	 */
	public void setHouseHoldDynamics(final Integer houseHoldDynamics) {
		this.houseHoldDynamics = houseHoldDynamics;
	}

	 /**
	 * Return the value associated with the column: housingIssuesFamilyMbr.
	 * @return A Integer object (this.housingIssuesFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "housing_issues_family_mbr"  )
	public Integer getHousingIssuesFamilyMbr() {
		return this.housingIssuesFamilyMbr;

	}



	 /**
	 * Set the value related to the column: housingIssuesFamilyMbr.
	 * @param housingIssuesFamilyMbr the housingIssuesFamilyMbr value you wish to set
	 */
	public void setHousingIssuesFamilyMbr(final Integer housingIssuesFamilyMbr) {
		this.housingIssuesFamilyMbr = housingIssuesFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: housingIssuesYouth.
	 * @return A Integer object (this.housingIssuesYouth)
	 */
	@Basic( optional = true )
	@Column( name = "housing_issues_youth"  )
	public Integer getHousingIssuesYouth() {
		return this.housingIssuesYouth;

	}



	 /**
	 * Set the value related to the column: housingIssuesYouth.
	 * @param housingIssuesYouth the housingIssuesYouth value you wish to set
	 */
	public void setHousingIssuesYouth(final Integer housingIssuesYouth) {
		this.housingIssuesYouth = housingIssuesYouth;
	}

	 /**
	 * Return the value associated with the column: id.
	 * @return A java.util.UUID object (this.id)
	 */
	@Id
	 @Basic( optional = false )
    @Column( name = "id", nullable = false  ) @org.hibernate.annotations.Type(type="org.hibernate.type.PostgresUUIDType")
	public java.util.UUID getId() {
		return this.id;

	}



	 /**
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final java.util.UUID id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

	 /**
	 * Return the value associated with the column: incarceratedParent.
	 * @return A Integer object (this.incarceratedParent)
	 */
	@Basic( optional = true )
	@Column( name = "incarcerated_parent"  )
	public Integer getIncarceratedParent() {
		return this.incarceratedParent;

	}



	 /**
	 * Set the value related to the column: incarceratedParent.
	 * @param incarceratedParent the incarceratedParent value you wish to set
	 */
	public void setIncarceratedParent(final Integer incarceratedParent) {
		this.incarceratedParent = incarceratedParent;
	}

	 /**
	 * Return the value associated with the column: incarceratedParentStatus.
	 * @return A Integer object (this.incarceratedParentStatus)
	 */
	@Basic( optional = true )
	@Column( name = "incarcerated_parent_status"  )
	public Integer getIncarceratedParentStatus() {
		return this.incarceratedParentStatus;

	}



	 /**
	 * Set the value related to the column: incarceratedParentStatus.
	 * @param incarceratedParentStatus the incarceratedParentStatus value you wish to set
	 */
	public void setIncarceratedParentStatus(final Integer incarceratedParentStatus) {
		this.incarceratedParentStatus = incarceratedParentStatus;
	}

	 /**
	 * Return the value associated with the column: insufficientIncomeToSupportYouth.
	 * @return A Integer object (this.insufficientIncomeToSupportYouth)
	 */
	@Basic( optional = true )
	@Column( name = "insufficient_income_to_support_youth"  )
	public Integer getInsufficientIncomeToSupportYouth() {
		return this.insufficientIncomeToSupportYouth;

	}



	 /**
	 * Set the value related to the column: insufficientIncomeToSupportYouth.
	 * @param insufficientIncomeToSupportYouth the insufficientIncomeToSupportYouth value you wish to set
	 */
	public void setInsufficientIncomeToSupportYouth(final Integer insufficientIncomeToSupportYouth) {
		this.insufficientIncomeToSupportYouth = insufficientIncomeToSupportYouth;
	}

	 /**
	 * Return the value associated with the column: laborExploitPastThreeMonths.
	 * @return A Integer object (this.laborExploitPastThreeMonths)
	 */
	@Basic( optional = true )
	@Column( name = "labor_exploit_past_three_months"  )
	public Integer getLaborExploitPastThreeMonths() {
		return this.laborExploitPastThreeMonths;

	}



	 /**
	 * Set the value related to the column: laborExploitPastThreeMonths.
	 * @param laborExploitPastThreeMonths the laborExploitPastThreeMonths value you wish to set
	 */
	public void setLaborExploitPastThreeMonths(final Integer laborExploitPastThreeMonths) {
		this.laborExploitPastThreeMonths = laborExploitPastThreeMonths;
	}

	 /**
	 * Return the value associated with the column: mentalDisabilityFamilyMbr.
	 * @return A Integer object (this.mentalDisabilityFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "mental_disability_family_mbr"  )
	public Integer getMentalDisabilityFamilyMbr() {
		return this.mentalDisabilityFamilyMbr;

	}



	 /**
	 * Set the value related to the column: mentalDisabilityFamilyMbr.
	 * @param mentalDisabilityFamilyMbr the mentalDisabilityFamilyMbr value you wish to set
	 */
	public void setMentalDisabilityFamilyMbr(final Integer mentalDisabilityFamilyMbr) {
		this.mentalDisabilityFamilyMbr = mentalDisabilityFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: mentalDisabilityYouth.
	 * @return A Integer object (this.mentalDisabilityYouth)
	 */
	@Basic( optional = true )
	@Column( name = "mental_disability_youth"  )
	public Integer getMentalDisabilityYouth() {
		return this.mentalDisabilityYouth;

	}



	 /**
	 * Set the value related to the column: mentalDisabilityYouth.
	 * @param mentalDisabilityYouth the mentalDisabilityYouth value you wish to set
	 */
	public void setMentalDisabilityYouth(final Integer mentalDisabilityYouth) {
		this.mentalDisabilityYouth = mentalDisabilityYouth;
	}

	 /**
	 * Return the value associated with the column: mentalHealthIssuesFamilyMbr.
	 * @return A Integer object (this.mentalHealthIssuesFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "mental_health_issues_family_mbr"  )
	public Integer getMentalHealthIssuesFamilyMbr() {
		return this.mentalHealthIssuesFamilyMbr;

	}



	 /**
	 * Set the value related to the column: mentalHealthIssuesFamilyMbr.
	 * @param mentalHealthIssuesFamilyMbr the mentalHealthIssuesFamilyMbr value you wish to set
	 */
	public void setMentalHealthIssuesFamilyMbr(final Integer mentalHealthIssuesFamilyMbr) {
		this.mentalHealthIssuesFamilyMbr = mentalHealthIssuesFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: mentalHealthIssuesYouth.
	 * @return A Integer object (this.mentalHealthIssuesYouth)
	 */
	@Basic( optional = true )
	@Column( name = "mental_health_issues_youth"  )
	public Integer getMentalHealthIssuesYouth() {
		return this.mentalHealthIssuesYouth;

	}



	 /**
	 * Set the value related to the column: mentalHealthIssuesYouth.
	 * @param mentalHealthIssuesYouth the mentalHealthIssuesYouth value you wish to set
	 */
	public void setMentalHealthIssuesYouth(final Integer mentalHealthIssuesYouth) {
		this.mentalHealthIssuesYouth = mentalHealthIssuesYouth;
	}

	 /**
	 * Return the value associated with the column: monthsChildWelfrForestCare.
	 * @return A Integer object (this.monthsChildWelfrForestCare)
	 */
	@Basic( optional = true )
	@Column( name = "months_child_welfr_forest_care"  )
	public Integer getMonthsChildWelfrForestCare() {
		return this.monthsChildWelfrForestCare;

	}



	 /**
	 * Set the value related to the column: monthsChildWelfrForestCare.
	 * @param monthsChildWelfrForestCare the monthsChildWelfrForestCare value you wish to set
	 */
	public void setMonthsChildWelfrForestCare(final Integer monthsChildWelfrForestCare) {
		this.monthsChildWelfrForestCare = monthsChildWelfrForestCare;
	}

	 /**
	 * Return the value associated with the column: physicalDisabilityFamilyMbr.
	 * @return A Integer object (this.physicalDisabilityFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "physical_disability_family_mbr"  )
	public Integer getPhysicalDisabilityFamilyMbr() {
		return this.physicalDisabilityFamilyMbr;

	}



	 /**
	 * Set the value related to the column: physicalDisabilityFamilyMbr.
	 * @param physicalDisabilityFamilyMbr the physicalDisabilityFamilyMbr value you wish to set
	 */
	public void setPhysicalDisabilityFamilyMbr(final Integer physicalDisabilityFamilyMbr) {
		this.physicalDisabilityFamilyMbr = physicalDisabilityFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: physicalDisabilityYouth.
	 * @return A Integer object (this.physicalDisabilityYouth)
	 */
	@Basic( optional = true )
	@Column( name = "physical_disability_youth"  )
	public Integer getPhysicalDisabilityYouth() {
		return this.physicalDisabilityYouth;

	}



	 /**
	 * Set the value related to the column: physicalDisabilityYouth.
	 * @param physicalDisabilityYouth the physicalDisabilityYouth value you wish to set
	 */
	public void setPhysicalDisabilityYouth(final Integer physicalDisabilityYouth) {
		this.physicalDisabilityYouth = physicalDisabilityYouth;
	}

	 /**
	 * Return the value associated with the column: referralSource.
	 * @return A Integer object (this.referralSource)
	 */
	@Basic( optional = true )
	@Column( name = "referral_source"  )
	public Integer getReferralSource() {
		return this.referralSource;

	}



	 /**
	 * Set the value related to the column: referralSource.
	 * @param referralSource the referralSource value you wish to set
	 */
	public void setReferralSource(final Integer referralSource) {
		this.referralSource = referralSource;
	}

	 /**
	 * Return the value associated with the column: schoolEducationIssuesFamilyMbr.
	 * @return A Integer object (this.schoolEducationIssuesFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "school_education_issues_family_mbr"  )
	public Integer getSchoolEducationIssuesFamilyMbr() {
		return this.schoolEducationIssuesFamilyMbr;

	}



	 /**
	 * Set the value related to the column: schoolEducationIssuesFamilyMbr.
	 * @param schoolEducationIssuesFamilyMbr the schoolEducationIssuesFamilyMbr value you wish to set
	 */
	public void setSchoolEducationIssuesFamilyMbr(final Integer schoolEducationIssuesFamilyMbr) {
		this.schoolEducationIssuesFamilyMbr = schoolEducationIssuesFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: schoolEducationIssuesYouth.
	 * @return A Integer object (this.schoolEducationIssuesYouth)
	 */
	@Basic( optional = true )
	@Column( name = "school_education_issues_youth"  )
	public Integer getSchoolEducationIssuesYouth() {
		return this.schoolEducationIssuesYouth;

	}



	 /**
	 * Set the value related to the column: schoolEducationIssuesYouth.
	 * @param schoolEducationIssuesYouth the schoolEducationIssuesYouth value you wish to set
	 */
	public void setSchoolEducationIssuesYouth(final Integer schoolEducationIssuesYouth) {
		this.schoolEducationIssuesYouth = schoolEducationIssuesYouth;
	}

	 /**
	 * Return the value associated with the column: sexualOrientatiionGenderIdentityFamilyMbr.
	 * @return A Integer object (this.sexualOrientatiionGenderIdentityFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "sexual_orientatiion_gender_identity_family_mbr"  )
	public Integer getSexualOrientatiionGenderIdentityFamilyMbr() {
		return this.sexualOrientatiionGenderIdentityFamilyMbr;

	}



	 /**
	 * Set the value related to the column: sexualOrientatiionGenderIdentityFamilyMbr.
	 * @param sexualOrientatiionGenderIdentityFamilyMbr the sexualOrientatiionGenderIdentityFamilyMbr value you wish to set
	 */
	public void setSexualOrientatiionGenderIdentityFamilyMbr(final Integer sexualOrientatiionGenderIdentityFamilyMbr) {
		this.sexualOrientatiionGenderIdentityFamilyMbr = sexualOrientatiionGenderIdentityFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: sexualOrientatiionGenderIdentityYouth.
	 * @return A Integer object (this.sexualOrientatiionGenderIdentityYouth)
	 */
	@Basic( optional = true )
	@Column( name = "sexual_orientatiion_gender_identity_youth"  )
	public Integer getSexualOrientatiionGenderIdentityYouth() {
		return this.sexualOrientatiionGenderIdentityYouth;

	}



	 /**
	 * Set the value related to the column: sexualOrientatiionGenderIdentityYouth.
	 * @param sexualOrientatiionGenderIdentityYouth the sexualOrientatiionGenderIdentityYouth value you wish to set
	 */
	public void setSexualOrientatiionGenderIdentityYouth(final Integer sexualOrientatiionGenderIdentityYouth) {
		this.sexualOrientatiionGenderIdentityYouth = sexualOrientatiionGenderIdentityYouth;
	}

	 /**
	 * Return the value associated with the column: sexualOrientation.
	 * @return A Integer object (this.sexualOrientation)
	 */
	@Basic( optional = true )
	@Column( name = "sexual_orientation"  )
	public Integer getSexualOrientation() {
		return this.sexualOrientation;

	}



	 /**
	 * Set the value related to the column: sexualOrientation.
	 * @param sexualOrientation the sexualOrientation value you wish to set
	 */
	public void setSexualOrientation(final Integer sexualOrientation) {
		this.sexualOrientation = sexualOrientation;
	}
	 /**
	 * Return the value associated with the column: unemployementFamilyMbr.
	 * @return A Integer object (this.unemployementFamilyMbr)
	 */
	@Basic( optional = true )
	@Column( name = "unemployement_family_mbr"  )
	public Integer getUnemployementFamilyMbr() {
		return this.unemployementFamilyMbr;

	}



	 /**
	 * Set the value related to the column: unemployementFamilyMbr.
	 * @param unemployementFamilyMbr the unemployementFamilyMbr value you wish to set
	 */
	public void setUnemployementFamilyMbr(final Integer unemployementFamilyMbr) {
		this.unemployementFamilyMbr = unemployementFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: unemployementYouth.
	 * @return A Integer object (this.unemployementYouth)
	 */
	@Basic( optional = true )
	@Column( name = "unemployement_youth"  )
	public Integer getUnemployementYouth() {
		return this.unemployementYouth;

	}



	 /**
	 * Set the value related to the column: unemployementYouth.
	 * @param unemployementYouth the unemployementYouth value you wish to set
	 */
	public void setUnemployementYouth(final Integer unemployementYouth) {
		this.unemployementYouth = unemployementYouth;
	}

	 /**
	 * Return the value associated with the column: workPlacePromiseDifference.
	 * @return A Integer object (this.workPlacePromiseDifference)
	 */
	@Basic( optional = true )
	@Column( name = "work_place_promise_difference"  )
	public Integer getWorkPlacePromiseDifference() {
		return this.workPlacePromiseDifference;

	}



	 /**
	 * Set the value related to the column: workPlacePromiseDifference.
	 * @param workPlacePromiseDifference the workPlacePromiseDifference value you wish to set
	 */
	public void setWorkPlacePromiseDifference(final Integer workPlacePromiseDifference) {
		this.workPlacePromiseDifference = workPlacePromiseDifference;
	}

	 /**
	 * Return the value associated with the column: workPlaceViolenceThreat.
	 * @return A Integer object (this.workPlaceViolenceThreat)
	 */
	@Basic( optional = true )
	@Column( name = "work_place_violence_threat"  )
	public Integer getWorkPlaceViolenceThreat() {
		return this.workPlaceViolenceThreat;

	}



	 /**
	 * Set the value related to the column: workPlaceViolenceThreat.
	 * @param workPlaceViolenceThreat the workPlaceViolenceThreat value you wish to set
	 */
	public void setWorkPlaceViolenceThreat(final Integer workPlaceViolenceThreat) {
		this.workPlaceViolenceThreat = workPlaceViolenceThreat;
	}

	 /**
	 * Return the value associated with the column: yearsChildWelfrForestCare.
	 * @return A Integer object (this.yearsChildWelfrForestCare)
	 */
	@Basic( optional = true )
	@Column( name = "years_child_welfr_forest_care"  )
	public Integer getYearsChildWelfrForestCare() {
		return this.yearsChildWelfrForestCare;

	}



	 /**
	 * Set the value related to the column: yearsChildWelfrForestCare.
	 * @param yearsChildWelfrForestCare the yearsChildWelfrForestCare value you wish to set
	 */
	public void setYearsChildWelfrForestCare(final Integer yearsChildWelfrForestCare) {
		this.yearsChildWelfrForestCare = yearsChildWelfrForestCare;
	}

	 /**
	 * Return the value associated with the column: yearsJuvenileJustice.
	 * @return A Integer object (this.yearsJuvenileJustice)
	 */
	@Basic( optional = true )
	@Column( name = "years_juvenile_justice"  )
	public Integer getYearsJuvenileJustice() {
		return this.yearsJuvenileJustice;

	}



	 /**
	 * Set the value related to the column: yearsJuvenileJustice.
	 * @param yearsJuvenileJustice the yearsJuvenileJustice value you wish to set
	 */
	public void setYearsJuvenileJustice(final Integer yearsJuvenileJustice) {
		this.yearsJuvenileJustice = yearsJuvenileJustice;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Entryrhy clone() throws CloneNotSupportedException {

        final Entryrhy copy = (Entryrhy)super.clone();

		copy.setAbuseAndNeglectFamilyMbr(this.getAbuseAndNeglectFamilyMbr());
		copy.setAbuseAndNeglectYouth(this.getAbuseAndNeglectYouth());
		copy.setActiveMilitaryParent(this.getActiveMilitaryParent());
		copy.setAlcoholDrugAbuseFamilyMbr(this.getAlcoholDrugAbuseFamilyMbr());
		copy.setAlcoholDrugAbuseYouth(this.getAlcoholDrugAbuseYouth());
		copy.setAskedOfForcedToExchangeForSex(this.getAskedOfForcedToExchangeForSex());
		copy.setAskedOfForcedToExchangeForSexPastThreeMonths(this.getAskedOfForcedToExchangeForSexPastThreeMonths());
		copy.setCoercedToContinueWork(this.getCoercedToContinueWork());
		copy.setCountOfExchangeForSex(this.getCountOfExchangeForSex());
		copy.setCountOutReachReferralApproaches(this.getCountOutReachReferralApproaches());
		copy.setDateCreated(this.getDateCreated());
		copy.setDateCreatedFromSource(this.getDateCreatedFromSource());
		copy.setDateUpdated(this.getDateUpdated());
		copy.setDateUpdatedFromSource(this.getDateUpdatedFromSource());
		copy.setDeleted(this.isDeleted());
		copy.setEnrollmentid(this.getEnrollmentid());
		copy.setExchangeForSex(this.getExchangeForSex());
		copy.setExchangeForSexPastThreeMonths(this.getExchangeForSexPastThreeMonths());
		copy.setExport(this.getExport());
		copy.setFormerlyWardChildWelfrForestCare(this.getFormerlyWardChildWelfrForestCare());
		copy.setFormerlyWardOfJuvenileJustice(this.getFormerlyWardOfJuvenileJustice());
		copy.setHealthIssuesFamilyMbr(this.getHealthIssuesFamilyMbr());
		copy.setHealthIssuesYouth(this.getHealthIssuesYouth());
		copy.setHouseHoldDynamics(this.getHouseHoldDynamics());
		copy.setHousingIssuesFamilyMbr(this.getHousingIssuesFamilyMbr());
		copy.setHousingIssuesYouth(this.getHousingIssuesYouth());
		copy.setId(this.getId());
		copy.setIncarceratedParent(this.getIncarceratedParent());
		copy.setIncarceratedParentStatus(this.getIncarceratedParentStatus());
		copy.setInsufficientIncomeToSupportYouth(this.getInsufficientIncomeToSupportYouth());
		copy.setLaborExploitPastThreeMonths(this.getLaborExploitPastThreeMonths());
		copy.setMentalDisabilityFamilyMbr(this.getMentalDisabilityFamilyMbr());
		copy.setMentalDisabilityYouth(this.getMentalDisabilityYouth());
		copy.setMentalHealthIssuesFamilyMbr(this.getMentalHealthIssuesFamilyMbr());
		copy.setMentalHealthIssuesYouth(this.getMentalHealthIssuesYouth());
		copy.setMonthsChildWelfrForestCare(this.getMonthsChildWelfrForestCare());
		copy.setParentId(this.getParentId());
		copy.setPhysicalDisabilityFamilyMbr(this.getPhysicalDisabilityFamilyMbr());
		copy.setPhysicalDisabilityYouth(this.getPhysicalDisabilityYouth());
		copy.setProjectGroupCode(this.getProjectGroupCode());
		copy.setReferralSource(this.getReferralSource());
		copy.setSchoolEducationIssuesFamilyMbr(this.getSchoolEducationIssuesFamilyMbr());
		copy.setSchoolEducationIssuesYouth(this.getSchoolEducationIssuesYouth());
		copy.setSexualOrientatiionGenderIdentityFamilyMbr(this.getSexualOrientatiionGenderIdentityFamilyMbr());
		copy.setSexualOrientatiionGenderIdentityYouth(this.getSexualOrientatiionGenderIdentityYouth());
		copy.setSexualOrientation(this.getSexualOrientation());
		copy.setSync(this.isSync());
		copy.setUnemployementFamilyMbr(this.getUnemployementFamilyMbr());
		copy.setUnemployementYouth(this.getUnemployementYouth());
		copy.setUserId(this.getUserId());
		copy.setVersion(this.getVersion());
		copy.setWorkPlacePromiseDifference(this.getWorkPlacePromiseDifference());
		copy.setWorkPlaceViolenceThreat(this.getWorkPlaceViolenceThreat());
		copy.setYearsChildWelfrForestCare(this.getYearsChildWelfrForestCare());
		copy.setYearsJuvenileJustice(this.getYearsJuvenileJustice());
		return copy;
	}



	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();

		sb.append("abuseAndNeglectFamilyMbr: " + this.getAbuseAndNeglectFamilyMbr() + ", ");
		sb.append("abuseAndNeglectYouth: " + this.getAbuseAndNeglectYouth() + ", ");
		sb.append("activeMilitaryParent: " + this.getActiveMilitaryParent() + ", ");
		sb.append("alcoholDrugAbuseFamilyMbr: " + this.getAlcoholDrugAbuseFamilyMbr() + ", ");
		sb.append("alcoholDrugAbuseYouth: " + this.getAlcoholDrugAbuseYouth() + ", ");
		sb.append("askedOfForcedToExchangeForSex: " + this.getAskedOfForcedToExchangeForSex() + ", ");
		sb.append("askedOfForcedToExchangeForSexPastThreeMonths: " + this.getAskedOfForcedToExchangeForSexPastThreeMonths() + ", ");
		sb.append("coercedToContinueWork: " + this.getCoercedToContinueWork() + ", ");
		sb.append("countOfExchangeForSex: " + this.getCountOfExchangeForSex() + ", ");
		sb.append("countOutReachReferralApproaches: " + this.getCountOutReachReferralApproaches() + ", ");
		sb.append("dateCreated: " + this.getDateCreated() + ", ");
		sb.append("dateCreatedFromSource: " + this.getDateCreatedFromSource() + ", ");
		sb.append("dateUpdated: " + this.getDateUpdated() + ", ");
		sb.append("dateUpdatedFromSource: " + this.getDateUpdatedFromSource() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("exchangeForSex: " + this.getExchangeForSex() + ", ");
		sb.append("exchangeForSexPastThreeMonths: " + this.getExchangeForSexPastThreeMonths() + ", ");
		sb.append("formerlyWardChildWelfrForestCare: " + this.getFormerlyWardChildWelfrForestCare() + ", ");
		sb.append("formerlyWardOfJuvenileJustice: " + this.getFormerlyWardOfJuvenileJustice() + ", ");
		sb.append("healthIssuesFamilyMbr: " + this.getHealthIssuesFamilyMbr() + ", ");
		sb.append("healthIssuesYouth: " + this.getHealthIssuesYouth() + ", ");
		sb.append("houseHoldDynamics: " + this.getHouseHoldDynamics() + ", ");
		sb.append("housingIssuesFamilyMbr: " + this.getHousingIssuesFamilyMbr() + ", ");
		sb.append("housingIssuesYouth: " + this.getHousingIssuesYouth() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("incarceratedParent: " + this.getIncarceratedParent() + ", ");
		sb.append("incarceratedParentStatus: " + this.getIncarceratedParentStatus() + ", ");
		sb.append("insufficientIncomeToSupportYouth: " + this.getInsufficientIncomeToSupportYouth() + ", ");
		sb.append("laborExploitPastThreeMonths: " + this.getLaborExploitPastThreeMonths() + ", ");
		sb.append("mentalDisabilityFamilyMbr: " + this.getMentalDisabilityFamilyMbr() + ", ");
		sb.append("mentalDisabilityYouth: " + this.getMentalDisabilityYouth() + ", ");
		sb.append("mentalHealthIssuesFamilyMbr: " + this.getMentalHealthIssuesFamilyMbr() + ", ");
		sb.append("mentalHealthIssuesYouth: " + this.getMentalHealthIssuesYouth() + ", ");
		sb.append("monthsChildWelfrForestCare: " + this.getMonthsChildWelfrForestCare() + ", ");
		sb.append("parentId: " + this.getParentId() + ", ");
		sb.append("physicalDisabilityFamilyMbr: " + this.getPhysicalDisabilityFamilyMbr() + ", ");
		sb.append("physicalDisabilityYouth: " + this.getPhysicalDisabilityYouth() + ", ");
		sb.append("projectGroupCode: " + this.getProjectGroupCode() + ", ");
		sb.append("referralSource: " + this.getReferralSource() + ", ");
		sb.append("schoolEducationIssuesFamilyMbr: " + this.getSchoolEducationIssuesFamilyMbr() + ", ");
		sb.append("schoolEducationIssuesYouth: " + this.getSchoolEducationIssuesYouth() + ", ");
		sb.append("sexualOrientatiionGenderIdentityFamilyMbr: " + this.getSexualOrientatiionGenderIdentityFamilyMbr() + ", ");
		sb.append("sexualOrientatiionGenderIdentityYouth: " + this.getSexualOrientatiionGenderIdentityYouth() + ", ");
		sb.append("sexualOrientation: " + this.getSexualOrientation() + ", ");
		sb.append("sync: " + this.isSync() + ", ");
		sb.append("unemployementFamilyMbr: " + this.getUnemployementFamilyMbr() + ", ");
		sb.append("unemployementYouth: " + this.getUnemployementYouth() + ", ");
		sb.append("userId: " + this.getUserId() + ", ");
		sb.append("version: " + this.getVersion() + ", ");
		sb.append("workPlacePromiseDifference: " + this.getWorkPlacePromiseDifference() + ", ");
		sb.append("workPlaceViolenceThreat: " + this.getWorkPlaceViolenceThreat() + ", ");
		sb.append("yearsChildWelfrForestCare: " + this.getYearsChildWelfrForestCare() + ", ");
		sb.append("yearsJuvenileJustice: " + this.getYearsJuvenileJustice());
		return sb.toString();
	}


	/** Equals implementation.
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;

		if ( this == aThat ) {
			 return true;
		}


		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}

		final Entryrhy that;
		try {
			that = (Entryrhy) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}


		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAbuseAndNeglectFamilyMbr() == null) && (that.getAbuseAndNeglectFamilyMbr() == null)) || (getAbuseAndNeglectFamilyMbr() != null && getAbuseAndNeglectFamilyMbr().equals(that.getAbuseAndNeglectFamilyMbr())));
		result = result && (((getAbuseAndNeglectYouth() == null) && (that.getAbuseAndNeglectYouth() == null)) || (getAbuseAndNeglectYouth() != null && getAbuseAndNeglectYouth().equals(that.getAbuseAndNeglectYouth())));
		result = result && (((getActiveMilitaryParent() == null) && (that.getActiveMilitaryParent() == null)) || (getActiveMilitaryParent() != null && getActiveMilitaryParent().equals(that.getActiveMilitaryParent())));
		result = result && (((getAlcoholDrugAbuseFamilyMbr() == null) && (that.getAlcoholDrugAbuseFamilyMbr() == null)) || (getAlcoholDrugAbuseFamilyMbr() != null && getAlcoholDrugAbuseFamilyMbr().equals(that.getAlcoholDrugAbuseFamilyMbr())));
		result = result && (((getAlcoholDrugAbuseYouth() == null) && (that.getAlcoholDrugAbuseYouth() == null)) || (getAlcoholDrugAbuseYouth() != null && getAlcoholDrugAbuseYouth().equals(that.getAlcoholDrugAbuseYouth())));
		result = result && (((getAskedOfForcedToExchangeForSex() == null) && (that.getAskedOfForcedToExchangeForSex() == null)) || (getAskedOfForcedToExchangeForSex() != null && getAskedOfForcedToExchangeForSex().equals(that.getAskedOfForcedToExchangeForSex())));
		result = result && (((getAskedOfForcedToExchangeForSexPastThreeMonths() == null) && (that.getAskedOfForcedToExchangeForSexPastThreeMonths() == null)) || (getAskedOfForcedToExchangeForSexPastThreeMonths() != null && getAskedOfForcedToExchangeForSexPastThreeMonths().equals(that.getAskedOfForcedToExchangeForSexPastThreeMonths())));
		result = result && (((getCoercedToContinueWork() == null) && (that.getCoercedToContinueWork() == null)) || (getCoercedToContinueWork() != null && getCoercedToContinueWork().equals(that.getCoercedToContinueWork())));
		result = result && (((getCountOfExchangeForSex() == null) && (that.getCountOfExchangeForSex() == null)) || (getCountOfExchangeForSex() != null && getCountOfExchangeForSex().equals(that.getCountOfExchangeForSex())));
		result = result && (((getCountOutReachReferralApproaches() == null) && (that.getCountOutReachReferralApproaches() == null)) || (getCountOutReachReferralApproaches() != null && getCountOutReachReferralApproaches().equals(that.getCountOutReachReferralApproaches())));
		result = result && (((getDateCreated() == null) && (that.getDateCreated() == null)) || (getDateCreated() != null && getDateCreated().equals(that.getDateCreated())));
		result = result && (((getDateCreatedFromSource() == null) && (that.getDateCreatedFromSource() == null)) || (getDateCreatedFromSource() != null && getDateCreatedFromSource().equals(that.getDateCreatedFromSource())));
		result = result && (((getDateUpdated() == null) && (that.getDateUpdated() == null)) || (getDateUpdated() != null && getDateUpdated().equals(that.getDateUpdated())));
		result = result && (((getDateUpdatedFromSource() == null) && (that.getDateUpdatedFromSource() == null)) || (getDateUpdatedFromSource() != null && getDateUpdatedFromSource().equals(that.getDateUpdatedFromSource())));
		result = result && (((getEnrollmentid() == null) && (that.getEnrollmentid() == null)) || (getEnrollmentid() != null && getEnrollmentid().getId().equals(that.getEnrollmentid().getId())));
		result = result && (((getExchangeForSex() == null) && (that.getExchangeForSex() == null)) || (getExchangeForSex() != null && getExchangeForSex().equals(that.getExchangeForSex())));
		result = result && (((getExchangeForSexPastThreeMonths() == null) && (that.getExchangeForSexPastThreeMonths() == null)) || (getExchangeForSexPastThreeMonths() != null && getExchangeForSexPastThreeMonths().equals(that.getExchangeForSexPastThreeMonths())));
		result = result && (((getExport() == null) && (that.getExport() == null)) || (getExport() != null && getExport().getId().equals(that.getExport().getId())));
		result = result && (((getFormerlyWardChildWelfrForestCare() == null) && (that.getFormerlyWardChildWelfrForestCare() == null)) || (getFormerlyWardChildWelfrForestCare() != null && getFormerlyWardChildWelfrForestCare().equals(that.getFormerlyWardChildWelfrForestCare())));
		result = result && (((getFormerlyWardOfJuvenileJustice() == null) && (that.getFormerlyWardOfJuvenileJustice() == null)) || (getFormerlyWardOfJuvenileJustice() != null && getFormerlyWardOfJuvenileJustice().equals(that.getFormerlyWardOfJuvenileJustice())));
		result = result && (((getHealthIssuesFamilyMbr() == null) && (that.getHealthIssuesFamilyMbr() == null)) || (getHealthIssuesFamilyMbr() != null && getHealthIssuesFamilyMbr().equals(that.getHealthIssuesFamilyMbr())));
		result = result && (((getHealthIssuesYouth() == null) && (that.getHealthIssuesYouth() == null)) || (getHealthIssuesYouth() != null && getHealthIssuesYouth().equals(that.getHealthIssuesYouth())));
		result = result && (((getHouseHoldDynamics() == null) && (that.getHouseHoldDynamics() == null)) || (getHouseHoldDynamics() != null && getHouseHoldDynamics().equals(that.getHouseHoldDynamics())));
		result = result && (((getHousingIssuesFamilyMbr() == null) && (that.getHousingIssuesFamilyMbr() == null)) || (getHousingIssuesFamilyMbr() != null && getHousingIssuesFamilyMbr().equals(that.getHousingIssuesFamilyMbr())));
		result = result && (((getHousingIssuesYouth() == null) && (that.getHousingIssuesYouth() == null)) || (getHousingIssuesYouth() != null && getHousingIssuesYouth().equals(that.getHousingIssuesYouth())));
		result = result && (((getIncarceratedParent() == null) && (that.getIncarceratedParent() == null)) || (getIncarceratedParent() != null && getIncarceratedParent().equals(that.getIncarceratedParent())));
		result = result && (((getIncarceratedParentStatus() == null) && (that.getIncarceratedParentStatus() == null)) || (getIncarceratedParentStatus() != null && getIncarceratedParentStatus().equals(that.getIncarceratedParentStatus())));
		result = result && (((getInsufficientIncomeToSupportYouth() == null) && (that.getInsufficientIncomeToSupportYouth() == null)) || (getInsufficientIncomeToSupportYouth() != null && getInsufficientIncomeToSupportYouth().equals(that.getInsufficientIncomeToSupportYouth())));
		result = result && (((getLaborExploitPastThreeMonths() == null) && (that.getLaborExploitPastThreeMonths() == null)) || (getLaborExploitPastThreeMonths() != null && getLaborExploitPastThreeMonths().equals(that.getLaborExploitPastThreeMonths())));
		result = result && (((getMentalDisabilityFamilyMbr() == null) && (that.getMentalDisabilityFamilyMbr() == null)) || (getMentalDisabilityFamilyMbr() != null && getMentalDisabilityFamilyMbr().equals(that.getMentalDisabilityFamilyMbr())));
		result = result && (((getMentalDisabilityYouth() == null) && (that.getMentalDisabilityYouth() == null)) || (getMentalDisabilityYouth() != null && getMentalDisabilityYouth().equals(that.getMentalDisabilityYouth())));
		result = result && (((getMentalHealthIssuesFamilyMbr() == null) && (that.getMentalHealthIssuesFamilyMbr() == null)) || (getMentalHealthIssuesFamilyMbr() != null && getMentalHealthIssuesFamilyMbr().equals(that.getMentalHealthIssuesFamilyMbr())));
		result = result && (((getMentalHealthIssuesYouth() == null) && (that.getMentalHealthIssuesYouth() == null)) || (getMentalHealthIssuesYouth() != null && getMentalHealthIssuesYouth().equals(that.getMentalHealthIssuesYouth())));
		result = result && (((getMonthsChildWelfrForestCare() == null) && (that.getMonthsChildWelfrForestCare() == null)) || (getMonthsChildWelfrForestCare() != null && getMonthsChildWelfrForestCare().equals(that.getMonthsChildWelfrForestCare())));
		result = result && (((getParentId() == null) && (that.getParentId() == null)) || (getParentId() != null && getParentId().equals(that.getParentId())));
		result = result && (((getPhysicalDisabilityFamilyMbr() == null) && (that.getPhysicalDisabilityFamilyMbr() == null)) || (getPhysicalDisabilityFamilyMbr() != null && getPhysicalDisabilityFamilyMbr().equals(that.getPhysicalDisabilityFamilyMbr())));
		result = result && (((getPhysicalDisabilityYouth() == null) && (that.getPhysicalDisabilityYouth() == null)) || (getPhysicalDisabilityYouth() != null && getPhysicalDisabilityYouth().equals(that.getPhysicalDisabilityYouth())));
		result = result && (((getProjectGroupCode() == null) && (that.getProjectGroupCode() == null)) || (getProjectGroupCode() != null && getProjectGroupCode().equals(that.getProjectGroupCode())));
		result = result && (((getReferralSource() == null) && (that.getReferralSource() == null)) || (getReferralSource() != null && getReferralSource().equals(that.getReferralSource())));
		result = result && (((getSchoolEducationIssuesFamilyMbr() == null) && (that.getSchoolEducationIssuesFamilyMbr() == null)) || (getSchoolEducationIssuesFamilyMbr() != null && getSchoolEducationIssuesFamilyMbr().equals(that.getSchoolEducationIssuesFamilyMbr())));
		result = result && (((getSchoolEducationIssuesYouth() == null) && (that.getSchoolEducationIssuesYouth() == null)) || (getSchoolEducationIssuesYouth() != null && getSchoolEducationIssuesYouth().equals(that.getSchoolEducationIssuesYouth())));
		result = result && (((getSexualOrientatiionGenderIdentityFamilyMbr() == null) && (that.getSexualOrientatiionGenderIdentityFamilyMbr() == null)) || (getSexualOrientatiionGenderIdentityFamilyMbr() != null && getSexualOrientatiionGenderIdentityFamilyMbr().equals(that.getSexualOrientatiionGenderIdentityFamilyMbr())));
		result = result && (((getSexualOrientatiionGenderIdentityYouth() == null) && (that.getSexualOrientatiionGenderIdentityYouth() == null)) || (getSexualOrientatiionGenderIdentityYouth() != null && getSexualOrientatiionGenderIdentityYouth().equals(that.getSexualOrientatiionGenderIdentityYouth())));
		result = result && (((getSexualOrientation() == null) && (that.getSexualOrientation() == null)) || (getSexualOrientation() != null && getSexualOrientation().equals(that.getSexualOrientation())));
		result = result && (((getUnemployementFamilyMbr() == null) && (that.getUnemployementFamilyMbr() == null)) || (getUnemployementFamilyMbr() != null && getUnemployementFamilyMbr().equals(that.getUnemployementFamilyMbr())));
		result = result && (((getUnemployementYouth() == null) && (that.getUnemployementYouth() == null)) || (getUnemployementYouth() != null && getUnemployementYouth().equals(that.getUnemployementYouth())));
		result = result && (((getUserId() == null) && (that.getUserId() == null)) || (getUserId() != null && getUserId().equals(that.getUserId())));
		result = result && (((getVersion() == null) && (that.getVersion() == null)) || (getVersion() != null && getVersion().equals(that.getVersion())));
		result = result && (((getWorkPlacePromiseDifference() == null) && (that.getWorkPlacePromiseDifference() == null)) || (getWorkPlacePromiseDifference() != null && getWorkPlacePromiseDifference().equals(that.getWorkPlacePromiseDifference())));
		result = result && (((getWorkPlaceViolenceThreat() == null) && (that.getWorkPlaceViolenceThreat() == null)) || (getWorkPlaceViolenceThreat() != null && getWorkPlaceViolenceThreat().equals(that.getWorkPlaceViolenceThreat())));
		result = result && (((getYearsChildWelfrForestCare() == null) && (that.getYearsChildWelfrForestCare() == null)) || (getYearsChildWelfrForestCare() != null && getYearsChildWelfrForestCare().equals(that.getYearsChildWelfrForestCare())));
		result = result && (((getYearsJuvenileJustice() == null) && (that.getYearsJuvenileJustice() == null)) || (getYearsJuvenileJustice() != null && getYearsJuvenileJustice().equals(that.getYearsJuvenileJustice())));
		return result;
	}

}
