package com.servinglynk.hmis.warehouse.model.v2017;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;
import org.hibernate.proxy.HibernateProxy;

import com.servinglynk.hmis.warehouse.enums.DataCollectionStageEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAlcoholDrugAbuseFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYChildWelfareYearsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardChildWelfareEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardJuvenileJusticeEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYIncarceratedParentEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYInsufficientIncomeEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYJuvenileJusticeYearsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYMentalHealthIssuesFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYPhysicalDisabilityFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYUnemploymentFamEnum;
import com.servinglynk.hmis.warehouse.enums.ReferralsourceReferralsourceEnum;
import com.servinglynk.hmis.warehouse.enums.SexualorientationSexualorientationEnum;

/**
 * Object mapping for hibernate-handled table: entryrhy.
 *
 *
 * @author autogenerated
 */


@Entity (name = "entryrhy_v2017")
@Table(name = "entryrhy", catalog = "hmis", schema = "v2017")
public class Entryrhy extends HmisBaseModel implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = 7937252363949404166L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, java.util.UUID> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, java.util.UUID>());

	/** hashCode temporary storage. */
	private volatile java.util.UUID hashCode;

	/** Field mapping. */
	private SexualorientationSexualorientationEnum sexualOrientation;
	/** Field mapping. */
	private EntryRHYUnemploymentFamEnum unemployementFamilyMbr;
	/** Field mapping. */
	private EntryRHYMentalHealthIssuesFamEnum mentalHealthIssuesFamilyMbr;
	/** Field mapping. */
	private EntryRHYPhysicalDisabilityFamEnum physicalDisabilityFamilyMbr;
	/** Field mapping. */
	private EntryRHYAlcoholDrugAbuseFamEnum alcoholDrugAbuseFamilyMbr;
	/** Field mapping. */
	private EntryRHYInsufficientIncomeEnum insufficientIncomeToSupportYouth;
	/** Field mapping. */
	private EntryRHYIncarceratedParentEnum incarceratedParent;
	/** Field mapping. */
	private EntryRHYFormerWardJuvenileJusticeEnum formerlyWardOfJuvenileJustice;
	/** Field mapping. */
	private EntryRHYJuvenileJusticeYearsEnum yearsJuvenileJustice;
	/** Field mapping. */
	private Integer monthsJuvenileJustice;
	/** Field mapping. */
	private EntryRHYFormerWardChildWelfareEnum formerlyWardChildWelfrForestCare;
	/** Field mapping. */
	private EntryRHYChildWelfareYearsEnum yearsChildWelfrForestCare;
	/** Field mapping. */
	private Integer monthsChildWelfrForestCare;
	/** Field mapping. */
	private ReferralsourceReferralsourceEnum referralSource;
	/** Field mapping. */
	private Integer countOutReachReferralApproaches;
	/** Field mapping. */
	private Enrollment enrollmentid;
	/** Field mapping. */
	private java.util.UUID id;

	/** Field mapping. */
	private DataCollectionStageEnum dataCollectionStage;
	/** Field mapping. */
	private LocalDateTime informationDate;

	@Type(type = "com.servinglynk.hmis.warehouse.enums.DataCollectionStageEnumType")
	@Basic( optional = true )
	@Column
	 public DataCollectionStageEnum getDataCollectionStage() {
		return dataCollectionStage;
	}

	public void setDataCollectionStage(DataCollectionStageEnum dataCollectionStage) {
		this.dataCollectionStage = dataCollectionStage;
	}
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Entryrhy() {
		// Default constructor
	}

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Entryrhy(java.util.UUID id) {
		this.id = id;
	}

	/**
	 * Return the value associated with the column: informationDate.
	 * @return A LocalDateTime object (this.informationDate)
	 */
	@Type(type="org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
	@Basic( optional = true )
	@Column( name = "information_date"  )
	public LocalDateTime getInformationDate() {
		return this.informationDate;

	}



	 /**
	 * Set the value related to the column: informationDate.
	 * @param informationDate the informationDate value you wish to set
	 */
	public void setInformationDate(final LocalDateTime informationDate) {
		this.informationDate = informationDate;
	}



	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Entryrhy.class;
	}



	 /**
	 * Return the value associated with the column: enrollmentid.
	 * @return A Enrollment object (this.enrollmentid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = true )
	@JoinColumn(name = "enrollmentid", nullable = true )
	public Enrollment getEnrollmentid() {
		return this.enrollmentid;

	}



	 /**
	 * Set the value related to the column: enrollmentid.
	 * @param enrollmentid the enrollmentid value you wish to set
	 */
	public void setEnrollmentid(final Enrollment enrollmentid) {
		this.enrollmentid = enrollmentid;
	}



	 /**
	 * Return the value associated with the column: id.
	 * @return A java.util.UUID object (this.id)
	 */
	@Id
	 @Basic( optional = false )
    @Column( name = "id", nullable = false  ) @org.hibernate.annotations.Type(type="org.hibernate.type.PostgresUUIDType")
	public java.util.UUID getId() {
		return this.id;

	}



	 /**
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final java.util.UUID id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}


	 /**
	 * Return the value associated with the column: referralSource.
	 * @return A Integer object (this.referralSource)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.ReferralsourceReferralsourceEnumType")
	@Basic( optional = true )
	@Column( name = "referral_source"  )
	public ReferralsourceReferralsourceEnum getReferralSource() {
		return this.referralSource;

	}



	 /**
	 * Set the value related to the column: referralSource.
	 * @param referralSource the referralSource value you wish to set
	 */
	public void setReferralSource(final ReferralsourceReferralsourceEnum referralSource) {
		this.referralSource = referralSource;
	}

	@Basic( optional = true )
	@Column (name="months_child_welfr_forest_care")
	public Integer getMonthsChildWelfrForestCare() {
		return monthsChildWelfrForestCare;
	}

	public void setMonthsChildWelfrForestCare(Integer monthsChildWelfrForestCare) {
		this.monthsChildWelfrForestCare = monthsChildWelfrForestCare;
	}

	/**
	 * Return the value associated with the column: alcoholDrugAbuseFamilyMbr.
	 * @return A Integer object (this.alcoholDrugAbuseFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAlcoholDrugAbuseFamEnumType")
	@Basic( optional = true )
	@Column (name="alcohol_drug_abuse_family_mbr")
   public EntryRHYAlcoholDrugAbuseFamEnum getAlcoholDrugAbuseFamilyMbr() {
		return alcoholDrugAbuseFamilyMbr;
	}

	public void setAlcoholDrugAbuseFamilyMbr(
			EntryRHYAlcoholDrugAbuseFamEnum alcoholDrugAbuseFamilyMbr) {
		this.alcoholDrugAbuseFamilyMbr = alcoholDrugAbuseFamilyMbr;
	}



	@Column(name="count_out_reach_referral_approaches")
	public Integer getCountOutReachReferralApproaches() {
		return countOutReachReferralApproaches;
	}

	public void setCountOutReachReferralApproaches(
			Integer countOutReachReferralApproaches) {
		this.countOutReachReferralApproaches = countOutReachReferralApproaches;
	}

	/**
	 * Return the value associated with the column: formerlyWardChildWelfrForestCare.
	 * @return A Integer object (this.formerlyWardChildWelfrForestCare)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardChildWelfareEnumType")
	@Basic( optional = true )
	@Column (name="formerly_ward_child_welfr_forest_care")
	public EntryRHYFormerWardChildWelfareEnum getFormerlyWardChildWelfrForestCare() {
		return formerlyWardChildWelfrForestCare;
	}

	public void setFormerlyWardChildWelfrForestCare(
			EntryRHYFormerWardChildWelfareEnum formerlyWardChildWelfrForestCare) {
		this.formerlyWardChildWelfrForestCare = formerlyWardChildWelfrForestCare;
	}

	/**
	 * Return the value associated with the column: formerlyWardOfJuvenileJustice.
	 * @return A Integer object (this.formerlyWardOfJuvenileJustice)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardJuvenileJusticeEnumType")
	@Basic( optional = true )
	@Column (name="formerly_ward_of_juvenile_justice")
	public EntryRHYFormerWardJuvenileJusticeEnum getFormerlyWardOfJuvenileJustice() {
		return formerlyWardOfJuvenileJustice;
	}

	public void setFormerlyWardOfJuvenileJustice(
			EntryRHYFormerWardJuvenileJusticeEnum formerlyWardOfJuvenileJustice) {
		this.formerlyWardOfJuvenileJustice = formerlyWardOfJuvenileJustice;
	}



	/**
	 * Return the value associated with the column: incarceratedParent.
	 * @return A Integer object (this.incarceratedParent)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYIncarceratedParentEnumType")
	@Basic( optional = true )
	@Column (name="incarcerated_parent")
	public EntryRHYIncarceratedParentEnum getIncarceratedParent() {
		return incarceratedParent;
	}

	public void setIncarceratedParent(
			EntryRHYIncarceratedParentEnum incarceratedParent) {
		this.incarceratedParent = incarceratedParent;
	}

	/**
	 * Return the value associated with the column: insufficientIncomeToSupportYouth.
	 * @return A Integer object (this.insufficientIncomeToSupportYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYInsufficientIncomeEnumType")
	@Basic( optional = true )
	@Column (name="insufficient_income_to_support_youth")
	public EntryRHYInsufficientIncomeEnum getInsufficientIncomeToSupportYouth() {
		return insufficientIncomeToSupportYouth;
	}

	public void setInsufficientIncomeToSupportYouth(
			EntryRHYInsufficientIncomeEnum insufficientIncomeToSupportYouth) {
		this.insufficientIncomeToSupportYouth = insufficientIncomeToSupportYouth;
	}

	/**
	 * Return the value associated with the column: mentalHealthIssuesFamilyMbr.
	 * @return A Integer object (this.mentalHealthIssuesFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYMentalHealthIssuesFamEnumType")
	@Basic( optional = true )
	@Column (name="mental_health_issues_family_mbrily_mbr")
	public EntryRHYMentalHealthIssuesFamEnum getMentalHealthIssuesFamilyMbr() {
		return mentalHealthIssuesFamilyMbr;
	}

	public void setMentalHealthIssuesFamilyMbr(
			EntryRHYMentalHealthIssuesFamEnum mentalHealthIssuesFamilyMbr) {
		this.mentalHealthIssuesFamilyMbr = mentalHealthIssuesFamilyMbr;
	}


	/**
	 * Return the value associated with the column: physicalDisabilityFamilyMbr.
	 * @return A Integer object (this.physicalDisabilityFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYPhysicalDisabilityFamEnumType")
	@Basic( optional = true )
	@Column (name="physical_disability_family_mbr")
	public EntryRHYPhysicalDisabilityFamEnum getPhysicalDisabilityFamilyMbr() {
		return physicalDisabilityFamilyMbr;
	}

	public void setPhysicalDisabilityFamilyMbr(
			EntryRHYPhysicalDisabilityFamEnum physicalDisabilityFamilyMbr) {
		this.physicalDisabilityFamilyMbr = physicalDisabilityFamilyMbr;
	}



	/**
	 * Return the value associated with the column: sexualOrientation.
	 * @return A Integer object (this.sexualOrientation)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.SexualorientationSexualorientationEnumType")
	@Basic( optional = true )
	@Column (name="sexual_orientation")
	public SexualorientationSexualorientationEnum getSexualOrientation() {
		return sexualOrientation;
	}

	public void setSexualOrientation(
			SexualorientationSexualorientationEnum sexualOrientation) {
		this.sexualOrientation = sexualOrientation;
	}

	/**
	 * Return the value associated with the column: unemployementFamilyMbr.
	 * @return A Integer object (this.unemployementFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYUnemploymentFamEnumType")
	@Basic( optional = true )
	@Column (name="unemployement_family_mbr")
	public EntryRHYUnemploymentFamEnum getUnemployementFamilyMbr() {
		return unemployementFamilyMbr;
	}

	public void setUnemployementFamilyMbr(
			EntryRHYUnemploymentFamEnum unemployementFamilyMbr) {
		this.unemployementFamilyMbr = unemployementFamilyMbr;
	}

	/**
	 * Return the value associated with the column: yearsChildWelfrForestCare.
	 * @return A Integer object (this.yearsChildWelfrForestCare)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYChildWelfareYearsEnumType")
	@Basic( optional = true )
	@Column (name="years_child_welfr_forest_care")
	public EntryRHYChildWelfareYearsEnum getYearsChildWelfrForestCare() {
		return yearsChildWelfrForestCare;
	}

	public void setYearsChildWelfrForestCare(
			EntryRHYChildWelfareYearsEnum yearsChildWelfrForestCare) {
		this.yearsChildWelfrForestCare = yearsChildWelfrForestCare;
	}

	/**
	 * Return the value associated with the column: yearsJuvenileJustice.
	 * @return A Integer object (this.yearsJuvenileJustice)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYJuvenileJusticeYearsEnumType")
	@Basic( optional = true )
	@Column (name="years_juvenile_justice")
	public EntryRHYJuvenileJusticeYearsEnum getYearsJuvenileJustice() {
		return yearsJuvenileJustice;
	}

	public void setYearsJuvenileJustice(
			EntryRHYJuvenileJusticeYearsEnum yearsJuvenileJustice) {
		this.yearsJuvenileJustice = yearsJuvenileJustice;
	}

	/**
	 * @return the monthsJuvenileJustice
	 */
	@Basic( optional = true )
	@Column (name="months_juvenile_justice")
	public Integer getMonthsJuvenileJustice() {
		return monthsJuvenileJustice;
	}

	/**
	 * @param monthsJuvenileJustice the monthsJuvenileJustice to set
	 */
	public void setMonthsJuvenileJustice(
			Integer monthsJuvenileJustice) {
		this.monthsJuvenileJustice = monthsJuvenileJustice;
	}

	/** Field mapping. */
	protected Export export;
	 /**
	 * Return the value associated with the column: export.
	 * @return A Export object (this.export)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = true )
	@JoinColumn(name = "export_id", nullable = true )
	public Export getExport() {
		return this.export;

	}



	 /**
	 * Set the value related to the column: export.
	 * @param export the export value you wish to set
	 */
	public void setExport(final Export export) {
		this.export = export;
	}
   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Entryrhy clone() throws CloneNotSupportedException {

        final Entryrhy copy = (Entryrhy)super.clone();

		copy.setAlcoholDrugAbuseFamilyMbr(this.getAlcoholDrugAbuseFamilyMbr());
		copy.setCountOutReachReferralApproaches(this.getCountOutReachReferralApproaches());
		copy.setDateCreated(this.getDateCreated());
		copy.setDateCreatedFromSource(this.getDateCreatedFromSource());
		copy.setDateUpdated(this.getDateUpdated());
		copy.setDateUpdatedFromSource(this.getDateUpdatedFromSource());
		copy.setDeleted(this.isDeleted());
		copy.setEnrollmentid(this.getEnrollmentid());
		copy.setExport(this.getExport());
		copy.setFormerlyWardChildWelfrForestCare(this.getFormerlyWardChildWelfrForestCare());
		copy.setFormerlyWardOfJuvenileJustice(this.getFormerlyWardOfJuvenileJustice());
		copy.setId(this.getId());
		copy.setIncarceratedParent(this.getIncarceratedParent());
		copy.setInsufficientIncomeToSupportYouth(this.getInsufficientIncomeToSupportYouth());
		copy.setMentalHealthIssuesFamilyMbr(this.getMentalHealthIssuesFamilyMbr());
		copy.setParentId(this.getParentId());
		copy.setPhysicalDisabilityFamilyMbr(this.getPhysicalDisabilityFamilyMbr());
		copy.setProjectGroupCode(this.getProjectGroupCode());
		copy.setReferralSource(this.getReferralSource());
		copy.setSexualOrientation(this.getSexualOrientation());
		copy.setSync(this.isSync());
		copy.setUnemployementFamilyMbr(this.getUnemployementFamilyMbr());
		copy.setUserId(this.getUserId());
		copy.setVersion(this.getVersion());
		copy.setYearsChildWelfrForestCare(this.getYearsChildWelfrForestCare());
		copy.setYearsJuvenileJustice(this.getYearsJuvenileJustice());
		return copy;
	}



	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();

		sb.append("alcoholDrugAbuseFamilyMbr: " + this.getAlcoholDrugAbuseFamilyMbr() + ", ");
		sb.append("countOutReachReferralApproaches: " + this.getCountOutReachReferralApproaches() + ", ");
		sb.append("dateCreated: " + this.getDateCreated() + ", ");
		sb.append("dateCreatedFromSource: " + this.getDateCreatedFromSource() + ", ");
		sb.append("dateUpdated: " + this.getDateUpdated() + ", ");
		sb.append("dateUpdatedFromSource: " + this.getDateUpdatedFromSource() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("formerlyWardChildWelfrForestCare: " + this.getFormerlyWardChildWelfrForestCare() + ", ");
		sb.append("formerlyWardOfJuvenileJustice: " + this.getFormerlyWardOfJuvenileJustice() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("incarceratedParent: " + this.getIncarceratedParent() + ", ");
		sb.append("insufficientIncomeToSupportYouth: " + this.getInsufficientIncomeToSupportYouth() + ", ");
		sb.append("parentId: " + this.getParentId() + ", ");
		sb.append("physicalDisabilityFamilyMbr: " + this.getPhysicalDisabilityFamilyMbr() + ", ");
		sb.append("projectGroupCode: " + this.getProjectGroupCode() + ", ");
		sb.append("referralSource: " + this.getReferralSource() + ", ");
		sb.append("sexualOrientation: " + this.getSexualOrientation() + ", ");
		sb.append("sync: " + this.isSync() + ", ");
		sb.append("unemployementFamilyMbr: " + this.getUnemployementFamilyMbr() + ", ");
		sb.append("userId: " + this.getUserId() + ", ");
		sb.append("version: " + this.getVersion() + ", ");
		sb.append("yearsChildWelfrForestCare: " + this.getYearsChildWelfrForestCare() + ", ");
		sb.append("yearsJuvenileJustice: " + this.getYearsJuvenileJustice());
		return sb.toString();
	}


	/** Equals implementation.
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;

		if ( this == aThat ) {
			 return true;
		}


		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}

		final Entryrhy that;
		try {
			that = (Entryrhy) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}


		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAlcoholDrugAbuseFamilyMbr() == null) && (that.getAlcoholDrugAbuseFamilyMbr() == null)) || (getAlcoholDrugAbuseFamilyMbr() != null && getAlcoholDrugAbuseFamilyMbr().equals(that.getAlcoholDrugAbuseFamilyMbr())));
		result = result && (((getCountOutReachReferralApproaches() == null) && (that.getCountOutReachReferralApproaches() == null)) || (getCountOutReachReferralApproaches() != null && getCountOutReachReferralApproaches().equals(that.getCountOutReachReferralApproaches())));
		result = result && (((getDateCreated() == null) && (that.getDateCreated() == null)) || (getDateCreated() != null && getDateCreated().equals(that.getDateCreated())));
		result = result && (((getDateCreatedFromSource() == null) && (that.getDateCreatedFromSource() == null)) || (getDateCreatedFromSource() != null && getDateCreatedFromSource().equals(that.getDateCreatedFromSource())));
		result = result && (((getDateUpdated() == null) && (that.getDateUpdated() == null)) || (getDateUpdated() != null && getDateUpdated().equals(that.getDateUpdated())));
		result = result && (((getDateUpdatedFromSource() == null) && (that.getDateUpdatedFromSource() == null)) || (getDateUpdatedFromSource() != null && getDateUpdatedFromSource().equals(that.getDateUpdatedFromSource())));
		result = result && (((getEnrollmentid() == null) && (that.getEnrollmentid() == null)) || (getEnrollmentid() != null && getEnrollmentid().getId().equals(that.getEnrollmentid().getId())));
		result = result && (((getExport() == null) && (that.getExport() == null)) || (getExport() != null && getExport().getId().equals(that.getExport().getId())));
		result = result && (((getFormerlyWardChildWelfrForestCare() == null) && (that.getFormerlyWardChildWelfrForestCare() == null)) || (getFormerlyWardChildWelfrForestCare() != null && getFormerlyWardChildWelfrForestCare().equals(that.getFormerlyWardChildWelfrForestCare())));
		result = result && (((getFormerlyWardOfJuvenileJustice() == null) && (that.getFormerlyWardOfJuvenileJustice() == null)) || (getFormerlyWardOfJuvenileJustice() != null && getFormerlyWardOfJuvenileJustice().equals(that.getFormerlyWardOfJuvenileJustice())));
		result = result && (((getIncarceratedParent() == null) && (that.getIncarceratedParent() == null)) || (getIncarceratedParent() != null && getIncarceratedParent().equals(that.getIncarceratedParent())));
		result = result && (((getInsufficientIncomeToSupportYouth() == null) && (that.getInsufficientIncomeToSupportYouth() == null)) || (getInsufficientIncomeToSupportYouth() != null && getInsufficientIncomeToSupportYouth().equals(that.getInsufficientIncomeToSupportYouth())));
		result = result && (((getParentId() == null) && (that.getParentId() == null)) || (getParentId() != null && getParentId().equals(that.getParentId())));
		result = result && (((getPhysicalDisabilityFamilyMbr() == null) && (that.getPhysicalDisabilityFamilyMbr() == null)) || (getPhysicalDisabilityFamilyMbr() != null && getPhysicalDisabilityFamilyMbr().equals(that.getPhysicalDisabilityFamilyMbr())));
		result = result && (((getProjectGroupCode() == null) && (that.getProjectGroupCode() == null)) || (getProjectGroupCode() != null && getProjectGroupCode().equals(that.getProjectGroupCode())));
		result = result && (((getReferralSource() == null) && (that.getReferralSource() == null)) || (getReferralSource() != null && getReferralSource().equals(that.getReferralSource())));
		result = result && (((getSexualOrientation() == null) && (that.getSexualOrientation() == null)) || (getSexualOrientation() != null && getSexualOrientation().equals(that.getSexualOrientation())));
		result = result && (((getUnemployementFamilyMbr() == null) && (that.getUnemployementFamilyMbr() == null)) || (getUnemployementFamilyMbr() != null && getUnemployementFamilyMbr().equals(that.getUnemployementFamilyMbr())));
		result = result && (((getUserId() == null) && (that.getUserId() == null)) || (getUserId() != null && getUserId().equals(that.getUserId())));
		result = result && (((getVersion() == null) && (that.getVersion() == null)) || (getVersion() != null && getVersion().equals(that.getVersion())));
		result = result && (((getYearsChildWelfrForestCare() == null) && (that.getYearsChildWelfrForestCare() == null)) || (getYearsChildWelfrForestCare() != null && getYearsChildWelfrForestCare().equals(that.getYearsChildWelfrForestCare())));
		result = result && (((getYearsJuvenileJustice() == null) && (that.getYearsJuvenileJustice() == null)) || (getYearsJuvenileJustice() != null && getYearsJuvenileJustice().equals(that.getYearsJuvenileJustice())));
		return result;
	}

}
