package com.servinglynk.hmis.warehouse.model.v2017;

import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;
import org.hibernate.proxy.HibernateProxy;

import com.servinglynk.hmis.warehouse.enums.ExitRHYEarlyExitReasonEnum;
import com.servinglynk.hmis.warehouse.enums.ProjectcompletionstatusProjectcompletionstatusEnum;

/**
 * Object mapping for hibernate-handled table: exitrhy.
 *
 *
 * @author autogenerated
 */


@Entity(name = "exitrhy_v2017")
@Table(name = "exitrhy", catalog = "hmis", schema = "v2017")
public class Exitrhy extends HmisBaseModel implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -4922345514822424647L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, java.util.UUID> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, java.util.UUID>());

	/** hashCode temporary storage. */
	private volatile java.util.UUID hashCode;


	/** Field mapping. */
//	private ExitRHYAssistanceMainstreamBenefitsEnum assistanceMainStreamBenefits;
	/** Field mapping. */
	private ExitRHYEarlyExitReasonEnum earlyExitReason;
	/** Field mapping. */
	private Exit exitid;
	/** Field mapping. */
//	private ExitRHYExitCounselingEnum exitCounseling;
	/** Field mapping. */
//	private ExitRHYFamilyReunificationAchievedEnum familyReunificationAchieved;
	/** Field mapping. */
//	private ExitRHYFurtherFollowUpServicesEnum furtherFollowupServices;
	/** Field mapping. */
	private java.util.UUID id;
	/** Field mapping. */
//	private ExitRHYOtherAftercarePlanOrActionEnum otherAftercarePlanOrAction;
	/** Field mapping. */
//	private ExitRHYPermanentHousingPlacementEnum permenantHousingPlacement;
	/** Field mapping. */
	private ProjectcompletionstatusProjectcompletionstatusEnum projectCompletionStatus;
	/** Field mapping. */
//	private ExitRHYResourcePackageEnum resourcePackage;
	/** Field mapping. */
//	private ExitRHYScheduledFollowUpContactsEnum scheduledFollowupContacts;
	/** Field mapping. */
//	private ExitRHYTemporaryShelterPlacementEnum tempShelterPlacement;
	/** Field mapping. */
//	private ExitRHYWrittenAfterCarePlanEnum writtenAfterCarePlan;
	
	private Integer exchageForSex;
	private Integer exchangeForSexPastThreeMonths;
	private Integer countOfExchangeForSex;  
	private Integer askedOrForcedToExchangeForSex;
	private Integer askedOrForcedToExchangeForSexPastThreeMonths; 
	private Integer workPlaceViolenceThreats;  
	private Integer workPlacePromiseDifference;
	private Integer coercedToContinueWork;  
	private Integer laborExploitPastThreeMonths;
	private Integer counselingReceived;  
	private Integer counselingType;  
	private Integer sessionCountAtExit;
	private Integer sessionsInPlan; 
	private Integer postExitCounselingPlan;  
	private Integer destinationSafeClient;  
	private Integer destinationSafeWorker;  
	private Integer posAdultConnections;
	private Integer posPeerConnections;  
	private Integer posCommunityConnections;
	
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Exitrhy() {
		// Default constructor
	}

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Exitrhy(java.util.UUID id) {
		this.id = id;
	}





	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Exitrhy.class;
	}


	 /**
		 * Return the value associated with the column: assistanceMainStreamBenefits.
		 * @return A Integer object (this.assistanceMainStreamBenefits)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYAssistanceMainstreamBenefitsEnumType")
		@Basic( optional = true )
		@Column (name="assistance_main_stream_benefits")
		public ExitRHYAssistanceMainstreamBenefitsEnum getAssistanceMainStreamBenefits() {
			return this.assistanceMainStreamBenefits;

		}*/



		 /**
		 * Set the value related to the column: assistanceMainStreamBenefits.
		 * @param assistanceMainStreamBenefits the assistanceMainStreamBenefits value you wish to set
		 */
		/*public void setAssistanceMainStreamBenefits(final ExitRHYAssistanceMainstreamBenefitsEnum assistanceMainStreamBenefits) {
			this.assistanceMainStreamBenefits = assistanceMainStreamBenefits;
		}*/
	
	
	

		 /**
		 * Return the value associated with the column: earlyExitReason.
		 * @return A Integer object (this.earlyExitReason)
		 */
		@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYEarlyExitReasonEnumType")
		@Basic( optional = true )
		@Column (name="early_exit_reason")
		public ExitRHYEarlyExitReasonEnum getEarlyExitReason() {
			return this.earlyExitReason;

		}


		@Basic( optional = true )
		@Column( name = "exchage_for_sex")
		 public Integer getExchageForSex() {
			return exchageForSex;
		}

		public void setExchageForSex(Integer exchageForSex) {
			this.exchageForSex = exchageForSex;
		}

		@Basic( optional = true )
		@Column( name = "exchange_for_sex_past_three_months")
		public Integer getExchangeForSexPastThreeMonths() {
			return exchangeForSexPastThreeMonths;
		}

		public void setExchangeForSexPastThreeMonths(
				Integer exchangeForSexPastThreeMonths) {
			this.exchangeForSexPastThreeMonths = exchangeForSexPastThreeMonths;
		}
		
		@Basic( optional = true )
		@Column( name = "count_of_exchange_for_sex")
		public Integer getCountOfExchangeForSex() {
			return countOfExchangeForSex;
		}

		public void setCountOfExchangeForSex(Integer countOfExchangeForSex) {
			this.countOfExchangeForSex = countOfExchangeForSex;
		}
		
		@Basic( optional = true )
		@Column( name = "asked_or_forced_to_exchange_for_sex")
		public Integer getAskedOrForcedToExchangeForSex() {
			return askedOrForcedToExchangeForSex;
		}

		public void setAskedOrForcedToExchangeForSex(
				Integer askedOrForcedToExchangeForSex) {
			this.askedOrForcedToExchangeForSex = askedOrForcedToExchangeForSex;
		}
		
		@Basic( optional = true )
		@Column( name = "asked_or_forced_to_exchange_for_sex_past_three_months")
		public Integer getAskedOrForcedToExchangeForSexPastThreeMonths() {
			return askedOrForcedToExchangeForSexPastThreeMonths;
		}

		public void setAskedOrForcedToExchangeForSexPastThreeMonths(
				Integer askedOrForcedToExchangeForSexPastThreeMonths) {
			this.askedOrForcedToExchangeForSexPastThreeMonths = askedOrForcedToExchangeForSexPastThreeMonths;
		}

		@Basic( optional = true )
		@Column( name = "work_place_violence_threats")
		public Integer getWorkPlaceViolenceThreats() {
			return workPlaceViolenceThreats;
		}

		public void setWorkPlaceViolenceThreats(Integer workPlaceViolenceThreats) {
			this.workPlaceViolenceThreats = workPlaceViolenceThreats;
		}
		
		@Basic( optional = true )
		@Column( name = "work_place_promise_difference")
		public Integer getWorkPlacePromiseDifference() {
			return workPlacePromiseDifference;
		}

		public void setWorkPlacePromiseDifference(Integer workPlacePromiseDifference) {
			this.workPlacePromiseDifference = workPlacePromiseDifference;
		}
		
		@Basic( optional = true )
		@Column( name = "coerced_to_continue_work")
		public Integer getCoercedToContinueWork() {
			return coercedToContinueWork;
		}

		public void setCoercedToContinueWork(Integer coercedToContinueWork) {
			this.coercedToContinueWork = coercedToContinueWork;
		}
		
		@Basic( optional = true )
		@Column( name = "labor_exploit_past_three_months")
		public Integer getLaborExploitPastThreeMonths() {
			return laborExploitPastThreeMonths;
		}

		public void setLaborExploitPastThreeMonths(Integer laborExploitPastThreeMonths) {
			this.laborExploitPastThreeMonths = laborExploitPastThreeMonths;
		}
		
		@Basic( optional = true )
		@Column( name = "counseling_received")
		public Integer getCounselingReceived() {
			return counselingReceived;
		}

		public void setCounselingReceived(Integer counselingReceived) {
			this.counselingReceived = counselingReceived;
		}
		
		@Basic( optional = true )
		@Column( name = "counseling_type")
		public Integer getCounselingType() {
			return counselingType;
		}

		public void setCounselingType(Integer counselingType) {
			this.counselingType = counselingType;
		}
		
		@Basic( optional = true )
		@Column( name = "session_count_at_exit")
		public Integer getSessionCountAtExit() {
			return sessionCountAtExit;
		}

		public void setSessionCountAtExit(Integer sessionCountAtExit) {
			this.sessionCountAtExit = sessionCountAtExit;
		}
		
		
		@Basic( optional = true )
		@Column( name = "sessions_in_plan")
		public Integer getSessionsInPlan() {
			return sessionsInPlan;
		}

		public void setSessionsInPlan(Integer sessionsInPlan) {
			this.sessionsInPlan = sessionsInPlan;
		}
		
		@Basic( optional = true )
		@Column( name = "post_exit_counseling_plan")
		public Integer getPostExitCounselingPlan() {
			return postExitCounselingPlan;
		}

		public void setPostExitCounselingPlan(Integer postExitCounselingPlan) {
			this.postExitCounselingPlan = postExitCounselingPlan;
		}

  
		@Basic( optional = true )
		@Column( name = "destination_safe_client")
		public Integer getDestinationSafeClient() {
			return destinationSafeClient;
		}

		public void setDestinationSafeClient(Integer destinationSafeClient) {
			this.destinationSafeClient = destinationSafeClient;
		}
		
		@Basic( optional = true )
		@Column( name = "destination_safe_worker")
		public Integer getDestinationSafeWorker() {
			return destinationSafeWorker;
		}

		public void setDestinationSafeWorker(Integer destinationSafeWorker) {
			this.destinationSafeWorker = destinationSafeWorker;
		}
		
		@Basic( optional = true )
		@Column( name = "pos_adult_connections")
		public Integer getPosAdultConnections() {
			return posAdultConnections;
		}

		public void setPosAdultConnections(Integer posAdultConnections) {
			this.posAdultConnections = posAdultConnections;
		}
		
		@Basic( optional = true )
		@Column( name = "pos_peer_connections")
		public Integer getPosPeerConnections() {
			return posPeerConnections;
		}

		public void setPosPeerConnections(Integer posPeerConnections) {
			this.posPeerConnections = posPeerConnections;
		}

		
		@Basic( optional = true )
		@Column( name = "pos_community_connections")
		public Integer getPosCommunityConnections() {
			return posCommunityConnections;
		}

		public void setPosCommunityConnections(Integer posCommunityConnections) {
			this.posCommunityConnections = posCommunityConnections;
		}

		/**
		 * Set the value related to the column: earlyExitReason.
		 * @param earlyExitReason the earlyExitReason value you wish to set
		 */
		public void setEarlyExitReason(final ExitRHYEarlyExitReasonEnum earlyExitReason) {
			this.earlyExitReason = earlyExitReason;
		}

		 /**
		 * Return the value associated with the column: exitid.
		 * @return A Exit object (this.exitid)
		 */
		@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
		@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
		@Basic( optional = true )
		@JoinColumn(name = "exitid", nullable = true )
		public Exit getExitid() {
			return this.exitid;

		}



		 /**
		 * Set the value related to the column: exitid.
		 * @param exitid the exitid value you wish to set
		 */
		public void setExitid(final Exit exitid) {
			this.exitid = exitid;
		}

		 /**
		 * Return the value associated with the column: exitCounseling.
		 * @return A Integer object (this.exitCounseling)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYExitCounselingEnumType")
		@Basic( optional = true )
		@Column (name="exit_counseling")
		public ExitRHYExitCounselingEnum getExitCounseling() {
			return this.exitCounseling;

		}*/



		 /**
		 * Set the value related to the column: exitCounseling.
		 * @param exitCounseling the exitCounseling value you wish to set
		 */
		/*public void setExitCounseling(final ExitRHYExitCounselingEnum exitCounseling) {
			this.exitCounseling = exitCounseling;
		}*/

		 /**
		 * Return the value associated with the column: familyReunificationAchieved.
		 * @return A Integer object (this.familyReunificationAchieved)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYFamilyReunificationAchievedEnumType")
		@Basic( optional = true )
		@Column (name="family_reunification_achieved")
		public ExitRHYFamilyReunificationAchievedEnum getFamilyReunificationAchieved() {
			return this.familyReunificationAchieved;

		}
*/


		 /**
		 * Set the value related to the column: familyReunificationAchieved.
		 * @param familyReunificationAchieved the familyReunificationAchieved value you wish to set
		 */
		/*public void setFamilyReunificationAchieved(final ExitRHYFamilyReunificationAchievedEnum familyReunificationAchieved) {
			this.familyReunificationAchieved = familyReunificationAchieved;
		}*/

		 /**
		 * Return the value associated with the column: furtherFollowupServices.
		 * @return A Integer object (this.furtherFollowupServices)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYFurtherFollowUpServicesEnumType")
		@Basic( optional = true )
		@Column (name="further_followup_services")
		public ExitRHYFurtherFollowUpServicesEnum getFurtherFollowupServices() {
			return this.furtherFollowupServices;

		}*/



		 /**
		 * Set the value related to the column: furtherFollowupServices.
		 * @param furtherFollowupServices the furtherFollowupServices value you wish to set
		 */
		/*public void setFurtherFollowupServices(final ExitRHYFurtherFollowUpServicesEnum furtherFollowupServices) {
			this.furtherFollowupServices = furtherFollowupServices;
		}*/

		 /**
		 * Return the value associated with the column: id.
		 * @return A java.util.UUID object (this.id)
		 */
		@Id
		 @Basic( optional = false )
	   @Column( name = "id", nullable = false  ) @org.hibernate.annotations.Type(type="org.hibernate.type.PostgresUUIDType")
		public java.util.UUID getId() {
			return this.id;

		}



		 /**
		 * Set the value related to the column: id.
		 * @param id the id value you wish to set
		 */
		public void setId(final java.util.UUID id) {
			// If we've just been persisted and hashCode has been
			// returned then make sure other entities with this
			// ID return the already returned hash code
			if ( (this.id == null ) &&
					(id != null) &&
					(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
			}
			this.id = id;
		}

		 /**
		 * Return the value associated with the column: otherAftercarePlanOrAction.
		 * @return A Integer object (this.otherAftercarePlanOrAction)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYOtherAftercarePlanOrActionEnumType")
		@Basic( optional = true )
		@Column (name="other_aftercare_plan_or_action")
		public ExitRHYOtherAftercarePlanOrActionEnum getOtherAftercarePlanOrAction() {
			return this.otherAftercarePlanOrAction;

		}*/



		 /**
		 * Set the value related to the column: otherAftercarePlanOrAction.
		 * @param otherAftercarePlanOrAction the otherAftercarePlanOrAction value you wish to set
		 */
		/*public void setOtherAftercarePlanOrAction(final ExitRHYOtherAftercarePlanOrActionEnum otherAftercarePlanOrAction) {
			this.otherAftercarePlanOrAction = otherAftercarePlanOrAction;
		}*/


		 /**
		 * Return the value associated with the column: permenantHousingPlacement.
		 * @return A Integer object (this.permenantHousingPlacement)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYPermanentHousingPlacementEnumType")
		@Basic( optional = true )
		@Column (name="permenant_housing_placement")
		public ExitRHYPermanentHousingPlacementEnum getPermenantHousingPlacement() {
			return this.permenantHousingPlacement;

		}*/

		 /**
		 * Set the value related to the column: permenantHousingPlacement.
		 * @param permenantHousingPlacement the permenantHousingPlacement value you wish to set
		 */
		/*public void setPermenantHousingPlacement(final ExitRHYPermanentHousingPlacementEnum permenantHousingPlacement) {
			this.permenantHousingPlacement = permenantHousingPlacement;
		}*/

		 /**
		 * Return the value associated with the column: projectCompletionStatus.
		 * @return A Integer object (this.projectCompletionStatus)
		 */
		@Type(type = "com.servinglynk.hmis.warehouse.enums.ProjectcompletionstatusProjectcompletionstatusEnumType")
		@Basic( optional = true )
		@Column(name="project_completion_status")
		public ProjectcompletionstatusProjectcompletionstatusEnum getProjectCompletionStatus() {
			return this.projectCompletionStatus;

		}



		 /**
		 * Set the value related to the column: projectCompletionStatus.
		 * @param projectCompletionStatus the projectCompletionStatus value you wish to set
		 */
		public void setProjectCompletionStatus(final ProjectcompletionstatusProjectcompletionstatusEnum projectCompletionStatus) {
			this.projectCompletionStatus = projectCompletionStatus;
		}

		 /**
		 * Return the value associated with the column: resourcePackage.
		 * @return A Integer object (this.resourcePackage)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYResourcePackageEnumType")
		@Basic( optional = true )
		@Column (name="resource_package")
		public ExitRHYResourcePackageEnum getResourcePackage() {
			return this.resourcePackage;

		}
*/


		 /**
		 * Set the value related to the column: resourcePackage.
		 * @param resourcePackage the resourcePackage value you wish to set
		 */
		/*public void setResourcePackage(final ExitRHYResourcePackageEnum resourcePackage) {
			this.resourcePackage = resourcePackage;
		}*/

		 /**
		 * Return the value associated with the column: scheduledFollowupContacts.
		 * @return A Integer object (this.scheduledFollowupContacts)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYScheduledFollowUpContactsEnumType")
		@Basic( optional = true )
		@Column (name="scheduled_followup_contacts")
		public ExitRHYScheduledFollowUpContactsEnum getScheduledFollowupContacts() {
			return this.scheduledFollowupContacts;

		}*/



		 /**
		 * Set the value related to the column: scheduledFollowupContacts.
		 * @param scheduledFollowupContacts the scheduledFollowupContacts value you wish to set
		 */
		/*public void setScheduledFollowupContacts(final ExitRHYScheduledFollowUpContactsEnum scheduledFollowupContacts) {
			this.scheduledFollowupContacts = scheduledFollowupContacts;
		}*/


		 /**
		 * Return the value associated with the column: tempShelterPlacement.
		 * @return A Integer object (this.tempShelterPlacement)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYTemporaryShelterPlacementEnumType")
		@Basic( optional = true )
		@Column (name="temp_shelter_placement")
		public ExitRHYTemporaryShelterPlacementEnum getTempShelterPlacement() {
			return this.tempShelterPlacement;

		}*/



		 /**
		 * Set the value related to the column: tempShelterPlacement.
		 * @param tempShelterPlacement the tempShelterPlacement value you wish to set
		 */
		/*public void setTempShelterPlacement(final ExitRHYTemporaryShelterPlacementEnum tempShelterPlacement) {
			this.tempShelterPlacement = tempShelterPlacement;
		}*/

		 /**
		 * Return the value associated with the column: writtenAfterCarePlan.
		 * @return A Integer object (this.writtenAfterCarePlan)
		 */
		/*@Type(type = "com.servinglynk.hmis.warehouse.enums.ExitRHYWrittenAfterCarePlanEnumType")
		@Basic( optional = true )
		@Column(name="written_after_care_plan")
		public ExitRHYWrittenAfterCarePlanEnum getWrittenAfterCarePlan() {
			return this.writtenAfterCarePlan;

		}*/



		 /**
		 * Set the value related to the column: writtenAfterCarePlan.
		 * @param writtenAfterCarePlan the writtenAfterCarePlan value you wish to set
		 */
/*		public void setWrittenAfterCarePlan(final ExitRHYWrittenAfterCarePlanEnum writtenAfterCarePlan) {
			this.writtenAfterCarePlan = writtenAfterCarePlan;
		}*/

		/** Field mapping. */
		protected Export export;
		 /**
		 * Return the value associated with the column: export.
		 * @return A Export object (this.export)
		 */
		@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
		@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
		@Basic( optional = true )
		@JoinColumn(name = "export_id", nullable = true )
		public Export getExport() {
			return this.export;

		}



		 /**
		 * Set the value related to the column: export.
		 * @param export the export value you wish to set
		 */
		public void setExport(final Export export) {
			this.export = export;
		}
   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Exitrhy clone() throws CloneNotSupportedException {

        final Exitrhy copy = (Exitrhy)super.clone();

//		copy.setAssistanceMainStreamBenefits(this.getAssistanceMainStreamBenefits());
		copy.setDateCreated(this.getDateCreated());
		copy.setDateCreatedFromSource(this.getDateCreatedFromSource());
		copy.setDateUpdated(this.getDateUpdated());
		copy.setDateUpdatedFromSource(this.getDateUpdatedFromSource());
		copy.setDeleted(this.isDeleted());
		copy.setEarlyExitReason(this.getEarlyExitReason());
		copy.setExitid(this.getExitid());
//		copy.setExitCounseling(this.getExitCounseling());
		copy.setExport(this.getExport());
//		copy.setFamilyReunificationAchieved(this.getFamilyReunificationAchieved());
//		copy.setFurtherFollowupServices(this.getFurtherFollowupServices());
		copy.setId(this.getId());
//		copy.setOtherAftercarePlanOrAction(this.getOtherAftercarePlanOrAction());
		copy.setParentId(this.getParentId());
//		copy.setPermenantHousingPlacement(this.getPermenantHousingPlacement());
		copy.setProjectCompletionStatus(this.getProjectCompletionStatus());
		copy.setProjectGroupCode(this.getProjectGroupCode());
//		copy.setResourcePackage(this.getResourcePackage());
//		copy.setScheduledFollowupContacts(this.getScheduledFollowupContacts());
		copy.setSync(this.isSync());
//		copy.setTempShelterPlacement(this.getTempShelterPlacement());
		copy.setUserId(this.getUserId());
		copy.setVersion(this.getVersion());
//		copy.setWrittenAfterCarePlan(this.getWrittenAfterCarePlan());
		return copy;
	}



	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();

//		sb.append("assistanceMainStreamBenefits: " + this.getAssistanceMainStreamBenefits() + ", ");
		sb.append("dateCreated: " + this.getDateCreated() + ", ");
		sb.append("dateCreatedFromSource: " + this.getDateCreatedFromSource() + ", ");
		sb.append("dateUpdated: " + this.getDateUpdated() + ", ");
		sb.append("dateUpdatedFromSource: " + this.getDateUpdatedFromSource() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("earlyExitReason: " + this.getEarlyExitReason() + ", ");
//		sb.append("exitCounseling: " + this.getExitCounseling() + ", ");
//		sb.append("familyReunificationAchieved: " + this.getFamilyReunificationAchieved() + ", ");
//		sb.append("furtherFollowupServices: " + this.getFurtherFollowupServices() + ", ");
		sb.append("id: " + this.getId() + ", ");
//		sb.append("otherAftercarePlanOrAction: " + this.getOtherAftercarePlanOrAction() + ", ");
		sb.append("parentId: " + this.getParentId() + ", ");
//		sb.append("permenantHousingPlacement: " + this.getPermenantHousingPlacement() + ", ");
		sb.append("projectCompletionStatus: " + this.getProjectCompletionStatus() + ", ");
		sb.append("projectGroupCode: " + this.getProjectGroupCode() + ", ");
//		sb.append("resourcePackage: " + this.getResourcePackage() + ", ");
//		sb.append("scheduledFollowupContacts: " + this.getScheduledFollowupContacts() + ", ");
		sb.append("sync: " + this.isSync() + ", ");
//		sb.append("tempShelterPlacement: " + this.getTempShelterPlacement() + ", ");
		sb.append("userId: " + this.getUserId() + ", ");
		sb.append("version: " + this.getVersion() + ", ");
//		sb.append("writtenAfterCarePlan: " + this.getWrittenAfterCarePlan());
		return sb.toString();
	}


	/** Equals implementation.
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;

		if ( this == aThat ) {
			 return true;
		}


		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}

		final Exitrhy that;
		try {
			that = (Exitrhy) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}


		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getAssistanceMainStreamBenefits() == null) && (that.getAssistanceMainStreamBenefits() == null)) || (getAssistanceMainStreamBenefits() != null && getAssistanceMainStreamBenefits().equals(that.getAssistanceMainStreamBenefits())));
		result = result && (((getDateCreated() == null) && (that.getDateCreated() == null)) || (getDateCreated() != null && getDateCreated().equals(that.getDateCreated())));
		result = result && (((getDateCreatedFromSource() == null) && (that.getDateCreatedFromSource() == null)) || (getDateCreatedFromSource() != null && getDateCreatedFromSource().equals(that.getDateCreatedFromSource())));
		result = result && (((getDateUpdated() == null) && (that.getDateUpdated() == null)) || (getDateUpdated() != null && getDateUpdated().equals(that.getDateUpdated())));
		result = result && (((getDateUpdatedFromSource() == null) && (that.getDateUpdatedFromSource() == null)) || (getDateUpdatedFromSource() != null && getDateUpdatedFromSource().equals(that.getDateUpdatedFromSource())));
		result = result && (((getEarlyExitReason() == null) && (that.getEarlyExitReason() == null)) || (getEarlyExitReason() != null && getEarlyExitReason().equals(that.getEarlyExitReason())));
		result = result && (((getExitid() == null) && (that.getExitid() == null)) || (getExitid() != null && getExitid().getId().equals(that.getExitid().getId())));
//		result = result && (((getExitCounseling() == null) && (that.getExitCounseling() == null)) || (getExitCounseling() != null && getExitCounseling().equals(that.getExitCounseling())));
		result = result && (((getExport() == null) && (that.getExport() == null)) || (getExport() != null && getExport().getId().equals(that.getExport().getId())));
//		result = result && (((getFamilyReunificationAchieved() == null) && (that.getFamilyReunificationAchieved() == null)) || (getFamilyReunificationAchieved() != null && getFamilyReunificationAchieved().equals(that.getFamilyReunificationAchieved())));
//		result = result && (((getFurtherFollowupServices() == null) && (that.getFurtherFollowupServices() == null)) || (getFurtherFollowupServices() != null && getFurtherFollowupServices().equals(that.getFurtherFollowupServices())));
//		result = result && (((getOtherAftercarePlanOrAction() == null) && (that.getOtherAftercarePlanOrAction() == null)) || (getOtherAftercarePlanOrAction() != null && getOtherAftercarePlanOrAction().equals(that.getOtherAftercarePlanOrAction())));
		result = result && (((getParentId() == null) && (that.getParentId() == null)) || (getParentId() != null && getParentId().equals(that.getParentId())));
//		result = result && (((getPermenantHousingPlacement() == null) && (that.getPermenantHousingPlacement() == null)) || (getPermenantHousingPlacement() != null && getPermenantHousingPlacement().equals(that.getPermenantHousingPlacement())));
		result = result && (((getProjectCompletionStatus() == null) && (that.getProjectCompletionStatus() == null)) || (getProjectCompletionStatus() != null && getProjectCompletionStatus().equals(that.getProjectCompletionStatus())));
		result = result && (((getProjectGroupCode() == null) && (that.getProjectGroupCode() == null)) || (getProjectGroupCode() != null && getProjectGroupCode().equals(that.getProjectGroupCode())));
//		result = result && (((getResourcePackage() == null) && (that.getResourcePackage() == null)) || (getResourcePackage() != null && getResourcePackage().equals(that.getResourcePackage())));
//		result = result && (((getScheduledFollowupContacts() == null) && (that.getScheduledFollowupContacts() == null)) || (getScheduledFollowupContacts() != null && getScheduledFollowupContacts().equals(that.getScheduledFollowupContacts())));
//		result = result && (((getTempShelterPlacement() == null) && (that.getTempShelterPlacement() == null)) || (getTempShelterPlacement() != null && getTempShelterPlacement().equals(that.getTempShelterPlacement())));
		result = result && (((getUserId() == null) && (that.getUserId() == null)) || (getUserId() != null && getUserId().equals(that.getUserId())));
		result = result && (((getVersion() == null) && (that.getVersion() == null)) || (getVersion() != null && getVersion().equals(that.getVersion())));
//		result = result && (((getWrittenAfterCarePlan() == null) && (that.getWrittenAfterCarePlan() == null)) || (getWrittenAfterCarePlan() != null && getWrittenAfterCarePlan().equals(that.getWrittenAfterCarePlan())));
		return result;
	}
}
