package com.servinglynk.report.business;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import com.servinglynk.report.bean.Q13c1PhysicalAndMentalHealthConditionsForStayersDataBean;

public class Q13c1PhysicalAndMentalHealthConditionsForStayersDataBeanMaker {
	
	public static List<Q13c1PhysicalAndMentalHealthConditionsForStayersDataBean> getQ13c1PhysicalAndMentalHealthConditionsForStayersList(){
	
	Q13c1PhysicalAndMentalHealthConditionsForStayersDataBean q13c1PhysicalAndMentalHealthConditionsForStayerTableBean= new Q13c1PhysicalAndMentalHealthConditionsForStayersDataBean();
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1MentalIllnessTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1MentalIllnessWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1MentalIllnessWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1MentalIllnessWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1MentalIllnessUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1AlcoholAbuseTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1AlcoholAbuseWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1AlcoholAbuseWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1AlcoholAbuseWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1AlcoholAbuseUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DrugAbuseTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DrugAbuseWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DrugAbuseWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DrugAbuseWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DrugAbuseUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1BothAlcoholAndDrugAbuseTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1BothAlcoholAndDrugAbuseWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1BothAlcoholAndDrugAbuseWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1BothAlcoholAndDrugAbuseWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1BothAlcoholAndDrugAbuseUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1ChronicHealthConditionTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1ChronicHealthConditionWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1ChronicHealthConditionWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1ChronicHealthConditionWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1ChronicHealthConditionUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1HIVRelatedDiseasesTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1HIVRelatedDiseasesWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1HIVRelatedDiseasesWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1HIVRelatedDiseasesWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1HIVRelatedDiseasesUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DevelopmentalDisabilityTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DevelopmentalDisabilityWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DevelopmentalDisabilityWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DevelopmentalDisabilityWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1DevelopmentalDisabilityUnknowHousehold(BigInteger.valueOf(0));
	
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1PhysicalDisabilityTotal(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1PhysicalDisabilityWithoutChildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1PhysicalDisabilityWithChildAndAdults(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1PhysicalDisabilityWithOnlychildren(BigInteger.valueOf(0));
	q13c1PhysicalAndMentalHealthConditionsForStayerTableBean.setQ13c1PhysicalDisabilityUnknowHousehold(BigInteger.valueOf(0));
	
	return Arrays.asList(q13c1PhysicalAndMentalHealthConditionsForStayerTableBean);
	
	}


}
