package com.servinglynk.report.business;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import com.servinglynk.report.bean.Q18DataBean;
import com.servinglynk.report.bean.ReportData;

public class Q18DataBeanMaker extends BaseBeanMaker {

	public static List<Q18DataBean> getQ18ClientCashIncomeCategoryEarnedOtherIncomeList(ReportData data){
		
		Q18DataBean q18ClientCashIncomeCategoryEarnedOtherIncomeTableData = new Q18DataBean();
		
		
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithBothEarnedAndOtherIncomeNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithBothEarnedAndOtherIncomeNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithBothEarnedAndOtherNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithDKRNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithDKRNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithDKRNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithIncomeInfoAtEntryNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithIncomeInfoAtEntryNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithIncomeInfoAtEntryNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithMissingInfoNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithMissingInfoNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithMissingInfoNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithNoIncomeNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithNoIncomeNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithNoOtherNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithOnlyEarnedIncomeNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithOnlyEarnedIncomeNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithOnlyEarnedIncomeNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithOnlyOtherIncomeNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithOnlyOtherIncomeNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18AdultsWithOnlyOtherIncomeNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18NumberOfAdultStayersNotRequiredNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18NumberOfAdultStayersNotRequiredNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18NumberOfAdultStayersNotRequiredNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18NumberOfAdultStayersWithoutRequiredNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18NumberOfAdultStayersWithoutRequiredNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18NumberOfAdultStayersWithoutRequiredNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18TotalAdultsNumberOfAdultsAtEntry(data.getNumOfAdults());
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18TotalAdultsNumberOfAdultsAtExit(data.getTotNoOfAdultLeavers());
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18TotalAdultsNumberOfAdultsAtFollowup(data.getTotNoOfAdultStayers());
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18OneOrMoreSourceofIncomeNumberOfAdultsAtEntry(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18OneOrMoreSourceofIncomeNumberOfAdultsAtExit(BigInteger.valueOf(0));
		q18ClientCashIncomeCategoryEarnedOtherIncomeTableData.setQ18OneOrMoreSourceofIncomeNumberOfAdultsAtFollowup(BigInteger.valueOf(0));
		
		return Arrays.asList(q18ClientCashIncomeCategoryEarnedOtherIncomeTableData);
	}
}
