package com.servinglynk.report.business;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import com.servinglynk.report.bean.Q19a2ClientCashIncomeChangeIncomeSourceByEntryDataBean;

public class Q19a2ClientCashIncomeChangeIncomeSourceByEntryDataBeanMaker {
	
	public static List<Q19a2ClientCashIncomeChangeIncomeSourceByEntryDataBean> getQ19a2ClientCashIncomeChangeIncomeSourceByEntryList(){
		
		Q19a2ClientCashIncomeChangeIncomeSourceByEntryDataBean q19a2ClientCashIncomeChangeIncomeSourceByEntryTable = new Q19a2ClientCashIncomeChangeIncomeSourceByEntryDataBean();
		
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomeTotalAdult(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomePerformanceMeasures(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdltsWithEarnedIncomePercent(BigInteger.valueOf(0));

		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomeTotalAdult(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomePerformanceMeasures(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInEarnedIncomePercent(BigInteger.valueOf(0));

		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomeTotalAdult(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomePerformanceMeasures(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NoOfAdultsWithOtherIncomePercent(BigInteger.valueOf(0));

		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomeTotalAdult(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomePerformanceMeasures(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOtherIncomePercent(BigInteger.valueOf(0));

		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomeTotalAdult(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomePerformanceMeasures(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2NumberOfAdultsWithAnyIncomePercent(BigInteger.valueOf(0));

		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHaveAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtExitThanAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollarAtExitAsAtEntry(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeDidNotHaveTheIncomeCategoryAtEntryAndGainedIncomeCategoryExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrExit(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomeTotalAdult(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomePerformanceMeasures(BigInteger.valueOf(0));
		q19a2ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a2AverageChangeInOverallIncomePercent(BigInteger.valueOf(0));
		
		return Arrays.asList(q19a2ClientCashIncomeChangeIncomeSourceByEntryTable);
	}

}
