package com.servinglynk.report.business;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import com.servinglynk.report.bean.Q19a3ClientCashIncomeChangeIncomeSourceByEntryDataBean;

public class Q19a3DataBeanMaker {
	
	public static List<Q19a3ClientCashIncomeChangeIncomeSourceByEntryDataBean> getQ19a3ClientCashIncomeChangeIncomeSourceByEntryList(){
		
		Q19a3ClientCashIncomeChangeIncomeSourceByEntryDataBean q19a3ClientCashIncomeChangeIncomeSourceByEntryTable = new Q19a3ClientCashIncomeChangeIncomeSourceByEntryDataBean();
		
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomeTotalAdult(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomePerformanceMeasures(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdltsWithEarnedIncomePercent(BigInteger.valueOf(0));
						
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomeTotalAdult(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomePerformanceMeasures(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInEarnedIncomePercent(BigInteger.valueOf(0));

				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomeTotalAdult(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomePerformanceMeasures(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NoOfAdultsWithOtherIncomePercent(BigInteger.valueOf(0));

				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomeTotalAdult(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomePerformanceMeasures(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOtherIncomePercent(BigInteger.valueOf(0));

				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomeTotalAdult(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomePerformanceMeasures(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3NumberOfAdultsWithAnyIncomePercent(BigInteger.valueOf(0));

				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeHadIncomeCategoryAtEntryAndDidNotHavefollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryButHadLessDollarAtFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndSameDollartFollowupOrExitAtEntry(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeRetainedIncomeCategoryAndIncreasedDollarAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryEntryAndGainedIncomeCategoryAtFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeDidNotHaveIncomeCategoryAtEntryOrFollowupOrExit(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomeTotalAdult(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomePerformanceMeasures(BigInteger.valueOf(0));
				q19a3ClientCashIncomeChangeIncomeSourceByEntryTable.setQ19a3AverageChangeInOverallIncomePercent(BigInteger.valueOf(0));
				
		
		return Arrays.asList(q19a3ClientCashIncomeChangeIncomeSourceByEntryTable);
	}

}
