package com.servinglynk.hmis.warehouse.model.v2016;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;
import org.hibernate.proxy.HibernateProxy;

import com.servinglynk.hmis.warehouse.enums.DataCollectionStageEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAbuseAndNeglectFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAbuseAndNeglectYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYActiveMilitaryParentEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAlcoholDrugAbuseFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAlcoholDrugAbuseYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAskedOrForcedToExchangeForSexEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYAskedOrForcedToExchangeForSexPastThreeMonthsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYChildWelfareYearsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYCoercedToContinueWorkEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYExchangeForSexEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYExchangeForSexPastThreeMonthsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardChildWelfareEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardJuvenileJusticeEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYHealthIssuesFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYHealthIssuesYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYHouseholdDynamicsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYHousingIssuesFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYHousingIssuesYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYIncarceratedParentEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYIncarceratedParentStatusEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYInsufficientIncomeEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYJuvenileJusticeYearsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYLaborExploitPastThreeMonthsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYMentalDisabilityFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYMentalDisabilityYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYMentalHealthIssuesFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYMentalHealthIssuesYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYPhysicalDisabilityFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYPhysicalDisabilityYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYSchoolEducationalIssuesFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYSchoolEducationalIssuesYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYSexualOrientationGenderIDFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYSexualOrientationGenderIdentityYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYUnemploymentFamEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYUnemploymentYouthEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYWorkPlaceViolenceThreatsEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYWorkplacePromiseDifferenceEnum;
import com.servinglynk.hmis.warehouse.enums.EntryRHYcountOfExchangeForSexpEnum;
import com.servinglynk.hmis.warehouse.enums.SexualorientationSexualorientationEnum;
import com.servinglynk.hmis.warehouse.model.EnrollmentSharingModel;
import com.servinglynk.hmis.warehouse.model.v2016.Enrollment;

/**
 * Object mapping for hibernate-handled table: entryrhy.
 *
 *
 * @author autogenerated
 */


@Entity (name = "entryrhy_v2016")
@Table(name = "entryrhy", catalog = "hmis", schema = "v2016")
public class Entryrhy extends HmisBaseModel implements Cloneable, Serializable ,EnrollmentSharingModel{

	/** Serial Version UID. */
	private static final long serialVersionUID = 7937252363949404166L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, java.util.UUID> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, java.util.UUID>());

	/** hashCode temporary storage. */
	private volatile java.util.UUID hashCode;


	/** Field mapping. */
	private EntryRHYAbuseAndNeglectFamEnum abuseAndNeglectFamilyMbr;
	/** Field mapping. */
	private EntryRHYAbuseAndNeglectYouthEnum abuseAndNeglectYouth;
	/** Field mapping. */
	private EntryRHYActiveMilitaryParentEnum activeMilitaryParent;
	/** Field mapping. */
	private EntryRHYAlcoholDrugAbuseFamEnum alcoholDrugAbuseFamilyMbr;
	/** Field mapping. */
	private EntryRHYAlcoholDrugAbuseYouthEnum alcoholDrugAbuseYouth;
	/** Field mapping. */
	private EntryRHYAskedOrForcedToExchangeForSexEnum askedOfForcedToExchangeForSex;
	/** Field mapping. */
	private EntryRHYAskedOrForcedToExchangeForSexPastThreeMonthsEnum askedOfForcedToExchangeForSexPastThreeMonths;
	/** Field mapping. */
	private EntryRHYCoercedToContinueWorkEnum coercedToContinueWork;
	/** Field mapping. */
	private EntryRHYcountOfExchangeForSexpEnum countOfExchangeForSex;
	/** Field mapping. */
	private Integer countOutReachReferralApproaches;
	/** Field mapping. */
	private Enrollment enrollmentid;
	/** Field mapping. */
	private EntryRHYExchangeForSexEnum exchangeForSex;
	/** Field mapping. */
	private EntryRHYExchangeForSexPastThreeMonthsEnum exchangeForSexPastThreeMonths;
	/** Field mapping. */
	private EntryRHYFormerWardChildWelfareEnum formerlyWardChildWelfrForestCare;
	/** Field mapping. */
	private EntryRHYFormerWardJuvenileJusticeEnum formerlyWardOfJuvenileJustice;
	/** Field mapping. */
	private EntryRHYHealthIssuesFamEnum healthIssuesFamilyMbr;
	/** Field mapping. */
	private EntryRHYHealthIssuesYouthEnum healthIssuesYouth;
	/** Field mapping. */
	private EntryRHYHouseholdDynamicsEnum houseHoldDynamics;
	/** Field mapping. */
	private EntryRHYHousingIssuesFamEnum housingIssuesFamilyMbr;
	/** Field mapping. */
	private EntryRHYHousingIssuesYouthEnum housingIssuesYouth;
	/** Field mapping. */
	private java.util.UUID id;
	/** Field mapping. */
	private EntryRHYIncarceratedParentEnum incarceratedParent;
	/** Field mapping. */
	private EntryRHYIncarceratedParentStatusEnum incarceratedParentStatus;
	/** Field mapping. */
	private EntryRHYInsufficientIncomeEnum insufficientIncomeToSupportYouth;
	/** Field mapping. */
	private Integer laborExploitPastThreeMonths;
	/** Field mapping. */
	private EntryRHYMentalDisabilityFamEnum mentalDisabilityFamilyMbr;
	/** Field mapping. */
	private EntryRHYMentalDisabilityYouthEnum mentalDisabilityYouth;
	/** Field mapping. */
	private EntryRHYMentalHealthIssuesFamEnum mentalHealthIssuesFamilyMbr;
	/** Field mapping. */
	private EntryRHYMentalHealthIssuesYouthEnum mentalHealthIssuesYouth;
	/** Field mapping. */
	private Integer monthsChildWelfrForestCare;
	/** Field mapping. */
	private EntryRHYPhysicalDisabilityFamEnum physicalDisabilityFamilyMbr;
	/** Field mapping. */
	private EntryRHYPhysicalDisabilityYouthEnum physicalDisabilityYouth;
	/** Field mapping. */
	private Integer referralSource;
	/** Field mapping. */
	private EntryRHYSchoolEducationalIssuesFamEnum schoolEducationIssuesFamilyMbr;
	/** Field mapping. */
	private EntryRHYSchoolEducationalIssuesYouthEnum schoolEducationIssuesYouth;
	/** Field mapping. */
	private EntryRHYSexualOrientationGenderIDFamEnum sexualOrientatiionGenderIdentityFamilyMbr;
	/** Field mapping. */
	private EntryRHYSexualOrientationGenderIdentityYouthEnum sexualOrientatiionGenderIdentityYouth;
	/** Field mapping. */
	private SexualorientationSexualorientationEnum sexualOrientation;
	/** Field mapping. */
	private EntryRHYUnemploymentFamEnum unemployementFamilyMbr;
	/** Field mapping. */
	private EntryRHYUnemploymentYouthEnum unemployementYouth;
	/** Field mapping. */
	private EntryRHYWorkplacePromiseDifferenceEnum workPlacePromiseDifference;
	/** Field mapping. */
	private EntryRHYWorkPlaceViolenceThreatsEnum workPlaceViolenceThreat;
	/** Field mapping. */
	private EntryRHYChildWelfareYearsEnum yearsChildWelfrForestCare;
	/** Field mapping. */
	private EntryRHYJuvenileJusticeYearsEnum yearsJuvenileJustice;
	/** Field mapping. */
	private EntryRHYJuvenileJusticeYearsEnum monthsJuvenileJustice;
	/** Field mapping. */
	private DataCollectionStageEnum dataCollectionStage;
	/** Field mapping. */
	private LocalDateTime informationDate;

	@Type(type = "com.servinglynk.hmis.warehouse.enums.DataCollectionStageEnumType")
	@Basic( optional = true )
	@Column
	 public DataCollectionStageEnum getDataCollectionStage() {
		return dataCollectionStage;
	}

	public void setDataCollectionStage(DataCollectionStageEnum dataCollectionStage) {
		this.dataCollectionStage = dataCollectionStage;
	}
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Entryrhy() {
		// Default constructor
	}

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Entryrhy(java.util.UUID id) {
		this.id = id;
	}

	/**
	 * Return the value associated with the column: informationDate.
	 * @return A LocalDateTime object (this.informationDate)
	 */
	@Type(type="org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
	@Basic( optional = true )
	@Column( name = "information_date"  )
	public LocalDateTime getInformationDate() {
		return this.informationDate;

	}



	 /**
	 * Set the value related to the column: informationDate.
	 * @param informationDate the informationDate value you wish to set
	 */
	public void setInformationDate(final LocalDateTime informationDate) {
		this.informationDate = informationDate;
	}



	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Entryrhy.class;
	}


	 /**
	 * Return the value associated with the column: abuseAndNeglectFamilyMbr.
	 * @return A Integer object (this.abuseAndNeglectFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAbuseAndNeglectFamEnumType")
	@Basic( optional = true )
	@Column(name= "abuse_and_neglect_family_mbr")
	public EntryRHYAbuseAndNeglectFamEnum getAbuseAndNeglectFamilyMbr() {
		return this.abuseAndNeglectFamilyMbr;

	}



	 /**
	 * Set the value related to the column: abuseAndNeglectFamilyMbr.
	 * @param abuseAndNeglectFamilyMbr the abuseAndNeglectFamilyMbr value you wish to set
	 */
	public void setAbuseAndNeglectFamilyMbr(final EntryRHYAbuseAndNeglectFamEnum abuseAndNeglectFamilyMbr) {
		this.abuseAndNeglectFamilyMbr = abuseAndNeglectFamilyMbr;
	}

	 /**
	 * Return the value associated with the column: abuseAndNeglectYouth.
	 * @return A Integer object (this.abuseAndNeglectYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAbuseAndNeglectYouthEnumType")
	@Basic( optional = true )
	@Column (name="abuse_and_neglect_youth")
	public EntryRHYAbuseAndNeglectYouthEnum getAbuseAndNeglectYouth() {
		return this.abuseAndNeglectYouth;

	}



	 /**
	 * Set the value related to the column: abuseAndNeglectYouth.
	 * @param abuseAndNeglectYouth the abuseAndNeglectYouth value you wish to set
	 */
	public void setAbuseAndNeglectYouth(final EntryRHYAbuseAndNeglectYouthEnum abuseAndNeglectYouth) {
		this.abuseAndNeglectYouth = abuseAndNeglectYouth;
	}

	 /**
	 * Return the value associated with the column: activeMilitaryParent.
	 * @return A Integer object (this.activeMilitaryParent)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYActiveMilitaryParentEnumType")
	@Basic( optional = true )
	@Column (name="active_military_parent")
	public EntryRHYActiveMilitaryParentEnum getActiveMilitaryParent() {
		return this.activeMilitaryParent;

	}



	 /**
	 * Set the value related to the column: activeMilitaryParent.
	 * @param activeMilitaryParent the activeMilitaryParent value you wish to set
	 */
	public void setActiveMilitaryParent(final EntryRHYActiveMilitaryParentEnum activeMilitaryParent) {
		this.activeMilitaryParent = activeMilitaryParent;
	}



	 /**
	 * Return the value associated with the column: enrollmentid.
	 * @return A Enrollment object (this.enrollmentid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = true )
	@JoinColumn(name = "enrollmentid", nullable = true )
	public Enrollment getEnrollmentid() {
		return this.enrollmentid;

	}



	 /**
	 * Set the value related to the column: enrollmentid.
	 * @param enrollmentid the enrollmentid value you wish to set
	 */
	public void setEnrollmentid(final Enrollment enrollmentid) {
		this.enrollmentid = enrollmentid;
	}



	 /**
	 * Return the value associated with the column: id.
	 * @return A java.util.UUID object (this.id)
	 */
	@Id
	 @Basic( optional = false )
    @Column( name = "id", nullable = false  ) @org.hibernate.annotations.Type(type="org.hibernate.type.PostgresUUIDType")
	public java.util.UUID getId() {
		return this.id;

	}



	 /**
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final java.util.UUID id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}


	 /**
	 * Return the value associated with the column: monthsChildWelfrForestCare.
	 * @return A Integer object (this.monthsChildWelfrForestCare)
	 */
	@Basic( optional = true )
	@Column( name = "months_child_welfr_forest_care"  )
	public Integer getMonthsChildWelfrForestCare() {
		return this.monthsChildWelfrForestCare;

	}



	 /**
	 * Set the value related to the column: monthsChildWelfrForestCare.
	 * @param monthsChildWelfrForestCare the monthsChildWelfrForestCare value you wish to set
	 */
	public void setMonthsChildWelfrForestCare(final Integer monthsChildWelfrForestCare) {
		this.monthsChildWelfrForestCare = monthsChildWelfrForestCare;
	}



	 /**
	 * Return the value associated with the column: referralSource.
	 * @return A Integer object (this.referralSource)
	 */
	@Basic( optional = true )
	@Column( name = "referral_source"  )
	public Integer getReferralSource() {
		return this.referralSource;

	}



	 /**
	 * Set the value related to the column: referralSource.
	 * @param referralSource the referralSource value you wish to set
	 */
	public void setReferralSource(final Integer referralSource) {
		this.referralSource = referralSource;
	}

	/**
	 * Return the value associated with the column: alcoholDrugAbuseFamilyMbr.
	 * @return A Integer object (this.alcoholDrugAbuseFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAlcoholDrugAbuseFamEnumType")
	@Basic( optional = true )
	@Column (name="alcohol_drug_abuse_family_mbr")
   public EntryRHYAlcoholDrugAbuseFamEnum getAlcoholDrugAbuseFamilyMbr() {
		return alcoholDrugAbuseFamilyMbr;
	}

	public void setAlcoholDrugAbuseFamilyMbr(
			EntryRHYAlcoholDrugAbuseFamEnum alcoholDrugAbuseFamilyMbr) {
		this.alcoholDrugAbuseFamilyMbr = alcoholDrugAbuseFamilyMbr;
	}

	/**
	 * Return the value associated with the column: alcoholDrugAbuseYouth.
	 * @return A Integer object (this.alcoholDrugAbuseYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAlcoholDrugAbuseYouthEnumType")
	@Basic( optional = true )
	@Column (name="alcohol_drug_abuse_youth")
	public EntryRHYAlcoholDrugAbuseYouthEnum getAlcoholDrugAbuseYouth() {
		return alcoholDrugAbuseYouth;
	}

	public void setAlcoholDrugAbuseYouth(
			EntryRHYAlcoholDrugAbuseYouthEnum alcoholDrugAbuseYouth) {
		this.alcoholDrugAbuseYouth = alcoholDrugAbuseYouth;
	}

	/**
	 * Return the value associated with the column: askedOfForcedToExchangeForSex.
	 * @return A Integer object (this.askedOfForcedToExchangeForSex)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAskedOrForcedToExchangeForSexEnumType")
	@Basic( optional = true )
	@Column (name="asked_of_forced_to_exchange_for_sex")
	public EntryRHYAskedOrForcedToExchangeForSexEnum getAskedOfForcedToExchangeForSex() {
		return askedOfForcedToExchangeForSex;
	}

	public void setAskedOfForcedToExchangeForSex(
			EntryRHYAskedOrForcedToExchangeForSexEnum askedOfForcedToExchangeForSex) {
		this.askedOfForcedToExchangeForSex = askedOfForcedToExchangeForSex;
	}

	/**
	 * Return the value associated with the column: askedOfForcedToExchangeForSexPastThreeMonths.
	 * @return A Integer object (this.askedOfForcedToExchangeForSexPastThreeMonths)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYAskedOrForcedToExchangeForSexPastThreeMonthsEnumType")
	@Basic( optional = true )
	@Column (name="asked_of_forced_to_exchange_for_sex_past_3_months")
	public EntryRHYAskedOrForcedToExchangeForSexPastThreeMonthsEnum getAskedOfForcedToExchangeForSexPastThreeMonths() {
		return askedOfForcedToExchangeForSexPastThreeMonths;
	}

	public void setAskedOfForcedToExchangeForSexPastThreeMonths(
			EntryRHYAskedOrForcedToExchangeForSexPastThreeMonthsEnum askedOfForcedToExchangeForSexPastThreeMonths) {
		this.askedOfForcedToExchangeForSexPastThreeMonths = askedOfForcedToExchangeForSexPastThreeMonths;
	}

	/**
	 * Return the value associated with the column: coercedToContinueWork.
	 * @return A Integer object (this.coercedToContinueWork)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYCoercedToContinueWorkEnumType")
	@Basic( optional = true )
	@Column (name="coerced_to_continue_work")
	public EntryRHYCoercedToContinueWorkEnum getCoercedToContinueWork() {
		return coercedToContinueWork;
	}

	public void setCoercedToContinueWork(
			EntryRHYCoercedToContinueWorkEnum coercedToContinueWork) {
		this.coercedToContinueWork = coercedToContinueWork;
	}

	/**
	 * Return the value associated with the column: countOfExchangeForSex.
	 * @return A Integer object (this.countOfExchangeForSex)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYcountOfExchangeForSexpEnumType")
	@Basic( optional = true )
	@Column (name="count_of_exchange_for_sex")
	public EntryRHYcountOfExchangeForSexpEnum getCountOfExchangeForSex() {
		return countOfExchangeForSex;
	}

	public void setCountOfExchangeForSex(
			EntryRHYcountOfExchangeForSexpEnum countOfExchangeForSex) {
		this.countOfExchangeForSex = countOfExchangeForSex;
	}

	@Column(name="count_out_reach_referral_approaches")
	public Integer getCountOutReachReferralApproaches() {
		return countOutReachReferralApproaches;
	}

	public void setCountOutReachReferralApproaches(
			Integer countOutReachReferralApproaches) {
		this.countOutReachReferralApproaches = countOutReachReferralApproaches;
	}

	/**
	 * Return the value associated with the column: exchangeForSex.
	 * @return A Integer object (this.exchangeForSex)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYExchangeForSexEnumType")
	@Basic( optional = true )
	@Column (name="exchange_for_sex")
	public EntryRHYExchangeForSexEnum getExchangeForSex() {
		return exchangeForSex;
	}

	public void setExchangeForSex(EntryRHYExchangeForSexEnum exchangeForSex) {
		this.exchangeForSex = exchangeForSex;
	}

	/**
	 * Return the value associated with the column: exchangeForSexPastThreeMonths.
	 * @return A Integer object (this.exchangeForSexPastThreeMonths)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYExchangeForSexPastThreeMonthsEnumType")
	@Basic( optional = true )
	@Column (name="exchange_for_sex_past_three_months")
	public EntryRHYExchangeForSexPastThreeMonthsEnum getExchangeForSexPastThreeMonths() {
		return exchangeForSexPastThreeMonths;
	}

	public void setExchangeForSexPastThreeMonths(
			EntryRHYExchangeForSexPastThreeMonthsEnum exchangeForSexPastThreeMonths) {
		this.exchangeForSexPastThreeMonths = exchangeForSexPastThreeMonths;
	}

	/**
	 * Return the value associated with the column: formerlyWardChildWelfrForestCare.
	 * @return A Integer object (this.formerlyWardChildWelfrForestCare)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardChildWelfareEnumType")
	@Basic( optional = true )
	@Column (name="formerly_ward_child_welfr_forest_care")
	public EntryRHYFormerWardChildWelfareEnum getFormerlyWardChildWelfrForestCare() {
		return formerlyWardChildWelfrForestCare;
	}

	public void setFormerlyWardChildWelfrForestCare(
			EntryRHYFormerWardChildWelfareEnum formerlyWardChildWelfrForestCare) {
		this.formerlyWardChildWelfrForestCare = formerlyWardChildWelfrForestCare;
	}

	/**
	 * Return the value associated with the column: formerlyWardOfJuvenileJustice.
	 * @return A Integer object (this.formerlyWardOfJuvenileJustice)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYFormerWardJuvenileJusticeEnumType")
	@Basic( optional = true )
	@Column (name="formerly_ward_of_juvenile_justice")
	public EntryRHYFormerWardJuvenileJusticeEnum getFormerlyWardOfJuvenileJustice() {
		return formerlyWardOfJuvenileJustice;
	}

	public void setFormerlyWardOfJuvenileJustice(
			EntryRHYFormerWardJuvenileJusticeEnum formerlyWardOfJuvenileJustice) {
		this.formerlyWardOfJuvenileJustice = formerlyWardOfJuvenileJustice;
	}

	/**
	 * Return the value associated with the column: healthIssuesFamilyMbr.
	 * @return A Integer object (this.healthIssuesFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYHealthIssuesFamEnumType")
	@Basic( optional = true )
	@Column (name="health_issues_family_mbrily_mbr")
	public EntryRHYHealthIssuesFamEnum getHealthIssuesFamilyMbr() {
		return healthIssuesFamilyMbr;
	}

	public void setHealthIssuesFamilyMbr(
			EntryRHYHealthIssuesFamEnum healthIssuesFamilyMbr) {
		this.healthIssuesFamilyMbr = healthIssuesFamilyMbr;
	}

	/**
	 * Return the value associated with the column: healthIssuesYouth.
	 * @return A Integer object (this.healthIssuesYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYHealthIssuesYouthEnumType")
	@Basic( optional = true )
	@Column (name="health_issues_youth")
	public EntryRHYHealthIssuesYouthEnum getHealthIssuesYouth() {
		return healthIssuesYouth;
	}

	public void setHealthIssuesYouth(EntryRHYHealthIssuesYouthEnum healthIssuesYouth) {
		this.healthIssuesYouth = healthIssuesYouth;
	}

	/**
	 * Return the value associated with the column: houseHoldDynamics.
	 * @return A Integer object (this.houseHoldDynamics)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYHouseholdDynamicsEnumType")
	@Basic( optional = true )
	@Column (name="house_hold_dynamics")
	public EntryRHYHouseholdDynamicsEnum getHouseHoldDynamics() {
		return houseHoldDynamics;
	}

	public void setHouseHoldDynamics(EntryRHYHouseholdDynamicsEnum houseHoldDynamics) {
		this.houseHoldDynamics = houseHoldDynamics;
	}

	/**
	 * Return the value associated with the column: housingIssuesFamilyMbr.
	 * @return A Integer object (this.housingIssuesFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYHousingIssuesFamEnumType")
	@Basic( optional = true )
	@Column(name="housing_issues_family_mbrily_mbr")
	public EntryRHYHousingIssuesFamEnum getHousingIssuesFamilyMbr() {
		return housingIssuesFamilyMbr;
	}

	public void setHousingIssuesFamilyMbr(
			EntryRHYHousingIssuesFamEnum housingIssuesFamilyMbr) {
		this.housingIssuesFamilyMbr = housingIssuesFamilyMbr;
	}

	/**
	 * Return the value associated with the column: housingIssuesYouth.
	 * @return A Integer object (this.housingIssuesYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYHousingIssuesYouthEnumType")
	@Basic( optional = true )
	@Column (name="housing_issues_youth")
	public EntryRHYHousingIssuesYouthEnum getHousingIssuesYouth() {
		return housingIssuesYouth;
	}

	public void setHousingIssuesYouth(
			EntryRHYHousingIssuesYouthEnum housingIssuesYouth) {
		this.housingIssuesYouth = housingIssuesYouth;
	}

	/**
	 * Return the value associated with the column: incarceratedParent.
	 * @return A Integer object (this.incarceratedParent)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYIncarceratedParentEnumType")
	@Basic( optional = true )
	@Column (name="incarcerated_parent")
	public EntryRHYIncarceratedParentEnum getIncarceratedParent() {
		return incarceratedParent;
	}

	public void setIncarceratedParent(
			EntryRHYIncarceratedParentEnum incarceratedParent) {
		this.incarceratedParent = incarceratedParent;
	}

	/**
	 * Return the value associated with the column: incarceratedParentStatus.
	 * @return A Integer object (this.incarceratedParentStatus)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYIncarceratedParentStatusEnumType")
	@Basic( optional = true )
	@Column (name="incarcerated_parent_status")
	public EntryRHYIncarceratedParentStatusEnum getIncarceratedParentStatus() {
		return incarceratedParentStatus;
	}

	public void setIncarceratedParentStatus(
			EntryRHYIncarceratedParentStatusEnum incarceratedParentStatus) {
		this.incarceratedParentStatus = incarceratedParentStatus;
	}

	/**
	 * Return the value associated with the column: insufficientIncomeToSupportYouth.
	 * @return A Integer object (this.insufficientIncomeToSupportYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYInsufficientIncomeEnumType")
	@Basic( optional = true )
	@Column (name="insufficient_income_to_support_youth")
	public EntryRHYInsufficientIncomeEnum getInsufficientIncomeToSupportYouth() {
		return insufficientIncomeToSupportYouth;
	}

	public void setInsufficientIncomeToSupportYouth(
			EntryRHYInsufficientIncomeEnum insufficientIncomeToSupportYouth) {
		this.insufficientIncomeToSupportYouth = insufficientIncomeToSupportYouth;
	}

	/**
	 * Return the value associated with the column: laborExploitPastThreeMonths.
	 * @return A Integer object (this.laborExploitPastThreeMonths)
	 */
	@Basic( optional = true )
	@Column (name="labor_exploit_past_three_months")
	public Integer getLaborExploitPastThreeMonths() {
		return laborExploitPastThreeMonths;
	}

	public void setLaborExploitPastThreeMonths(
			Integer laborExploitPastThreeMonths) {
		this.laborExploitPastThreeMonths = laborExploitPastThreeMonths;
	}

	/**
	 * Return the value associated with the column: mentalDisabilityFamilyMbr.
	 * @return A Integer object (this.mentalDisabilityFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYMentalDisabilityFamEnumType")
	@Basic( optional = true )
	@Column (name="mental_disability_family_mbrily_mbr")
	public EntryRHYMentalDisabilityFamEnum getMentalDisabilityFamilyMbr() {
		return mentalDisabilityFamilyMbr;
	}

	public void setMentalDisabilityFamilyMbr(
			EntryRHYMentalDisabilityFamEnum mentalDisabilityFamilyMbr) {
		this.mentalDisabilityFamilyMbr = mentalDisabilityFamilyMbr;
	}

	/**
	 * Return the value associated with the column: mentalDisabilityYouth.
	 * @return A Integer object (this.mentalDisabilityYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYMentalDisabilityYouthEnumType")
	@Basic( optional = true )
	@Column (name="mental_disability_youth")
	public EntryRHYMentalDisabilityYouthEnum getMentalDisabilityYouth() {
		return mentalDisabilityYouth;
	}

	public void setMentalDisabilityYouth(
			EntryRHYMentalDisabilityYouthEnum mentalDisabilityYouth) {
		this.mentalDisabilityYouth = mentalDisabilityYouth;
	}

	/**
	 * Return the value associated with the column: mentalHealthIssuesFamilyMbr.
	 * @return A Integer object (this.mentalHealthIssuesFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYMentalHealthIssuesFamEnumType")
	@Basic( optional = true )
	@Column (name="mental_health_issues_family_mbrily_mbr")
	public EntryRHYMentalHealthIssuesFamEnum getMentalHealthIssuesFamilyMbr() {
		return mentalHealthIssuesFamilyMbr;
	}

	public void setMentalHealthIssuesFamilyMbr(
			EntryRHYMentalHealthIssuesFamEnum mentalHealthIssuesFamilyMbr) {
		this.mentalHealthIssuesFamilyMbr = mentalHealthIssuesFamilyMbr;
	}

	/**
	 * Return the value associated with the column: mentalHealthIssuesYouth.
	 * @return A Integer object (this.mentalHealthIssuesYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYMentalHealthIssuesYouthEnumType")
	@Basic( optional = true )
	@Column (name="mental_health_issues_youth")
	public EntryRHYMentalHealthIssuesYouthEnum getMentalHealthIssuesYouth() {
		return mentalHealthIssuesYouth;
	}

	public void setMentalHealthIssuesYouth(
			EntryRHYMentalHealthIssuesYouthEnum mentalHealthIssuesYouth) {
		this.mentalHealthIssuesYouth = mentalHealthIssuesYouth;
	}

	/**
	 * Return the value associated with the column: physicalDisabilityFamilyMbr.
	 * @return A Integer object (this.physicalDisabilityFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYPhysicalDisabilityFamEnumType")
	@Basic( optional = true )
	@Column (name="physical_disability_family_mbr")
	public EntryRHYPhysicalDisabilityFamEnum getPhysicalDisabilityFamilyMbr() {
		return physicalDisabilityFamilyMbr;
	}

	public void setPhysicalDisabilityFamilyMbr(
			EntryRHYPhysicalDisabilityFamEnum physicalDisabilityFamilyMbr) {
		this.physicalDisabilityFamilyMbr = physicalDisabilityFamilyMbr;
	}

	/**
	 * Return the value associated with the column: physicalDisabilityYouth.
	 * @return A Integer object (this.physicalDisabilityYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYPhysicalDisabilityYouthEnumType")
	@Basic( optional = true )
	@Column (name="physical_disability_youth")
	public EntryRHYPhysicalDisabilityYouthEnum getPhysicalDisabilityYouth() {
		return physicalDisabilityYouth;
	}

	public void setPhysicalDisabilityYouth(
			EntryRHYPhysicalDisabilityYouthEnum physicalDisabilityYouth) {
		this.physicalDisabilityYouth = physicalDisabilityYouth;
	}

	/**
	 * Return the value associated with the column: schoolEducationIssuesFamilyMbr.
	 * @return A Integer object (this.schoolEducationIssuesFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYSchoolEducationalIssuesFamEnumType")
	@Basic( optional = true )
	@Column (name="school_education_issues_family_mbr")
	public EntryRHYSchoolEducationalIssuesFamEnum getSchoolEducationIssuesFamilyMbr() {
		return schoolEducationIssuesFamilyMbr;
	}

	public void setSchoolEducationIssuesFamilyMbr(
			EntryRHYSchoolEducationalIssuesFamEnum schoolEducationIssuesFamilyMbr) {
		this.schoolEducationIssuesFamilyMbr = schoolEducationIssuesFamilyMbr;
	}


	/**
	 * Return the value associated with the column: schoolEducationIssuesYouth.
	 * @return A Integer object (this.schoolEducationIssuesYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYSchoolEducationalIssuesYouthEnumType")
	@Basic( optional = true )
	@Column (name="school_education_issues_youth")
	public EntryRHYSchoolEducationalIssuesYouthEnum getSchoolEducationIssuesYouth() {
		return schoolEducationIssuesYouth;
	}

	public void setSchoolEducationIssuesYouth(
			EntryRHYSchoolEducationalIssuesYouthEnum schoolEducationIssuesYouth) {
		this.schoolEducationIssuesYouth = schoolEducationIssuesYouth;
	}

	/**
	 * Return the value associated with the column: sexualOrientatiionGenderIdentityFamilyMbr.
	 * @return A Integer object (this.sexualOrientatiionGenderIdentityFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYSexualOrientationGenderIDFamEnumType")
	@Basic( optional = true )
	@Column (name="sexual_orientatiion_gender_identity_family_mbr")
	public EntryRHYSexualOrientationGenderIDFamEnum getSexualOrientatiionGenderIdentityFamilyMbr() {
		return sexualOrientatiionGenderIdentityFamilyMbr;
	}

	public void setSexualOrientatiionGenderIdentityFamilyMbr(
			EntryRHYSexualOrientationGenderIDFamEnum sexualOrientatiionGenderIdentityFamilyMbr) {
		this.sexualOrientatiionGenderIdentityFamilyMbr = sexualOrientatiionGenderIdentityFamilyMbr;
	}


	/**
	 * Return the value associated with the column: sexualOrientatiionGenderIdentityYouth.
	 * @return A Integer object (this.sexualOrientatiionGenderIdentityYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYSexualOrientationGenderIdentityYouthEnumType")
	@Basic( optional = true )
	@Column (name="sexual_orientatiion_gender_identity_youth")
	public EntryRHYSexualOrientationGenderIdentityYouthEnum getSexualOrientatiionGenderIdentityYouth() {
		return sexualOrientatiionGenderIdentityYouth;
	}

	public void setSexualOrientatiionGenderIdentityYouth(
			EntryRHYSexualOrientationGenderIdentityYouthEnum sexualOrientatiionGenderIdentityYouth) {
		this.sexualOrientatiionGenderIdentityYouth = sexualOrientatiionGenderIdentityYouth;
	}

	/**
	 * Return the value associated with the column: sexualOrientation.
	 * @return A Integer object (this.sexualOrientation)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.SexualorientationSexualorientationEnumType")
	@Basic( optional = true )
	@Column (name="sexual_orientation")
	public SexualorientationSexualorientationEnum getSexualOrientation() {
		return sexualOrientation;
	}

	public void setSexualOrientation(
			SexualorientationSexualorientationEnum sexualOrientation) {
		this.sexualOrientation = sexualOrientation;
	}

	/**
	 * Return the value associated with the column: unemployementFamilyMbr.
	 * @return A Integer object (this.unemployementFamilyMbr)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYUnemploymentFamEnumType")
	@Basic( optional = true )
	@Column (name="unemployement_family_mbr")
	public EntryRHYUnemploymentFamEnum getUnemployementFamilyMbr() {
		return unemployementFamilyMbr;
	}

	public void setUnemployementFamilyMbr(
			EntryRHYUnemploymentFamEnum unemployementFamilyMbr) {
		this.unemployementFamilyMbr = unemployementFamilyMbr;
	}

	/**
	 * Return the value associated with the column: unemployementYouth.
	 * @return A Integer object (this.unemployementYouth)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYUnemploymentYouthEnumType")
	@Basic( optional = true )
	@Column (name="unemployement_youth")
	public EntryRHYUnemploymentYouthEnum getUnemployementYouth() {
		return unemployementYouth;
	}

	public void setUnemployementYouth(
			EntryRHYUnemploymentYouthEnum unemployementYouth) {
		this.unemployementYouth = unemployementYouth;
	}

	/**
	 * Return the value associated with the column: workPlacePromiseDifference.
	 * @return A Integer object (this.workPlacePromiseDifference)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYWorkplacePromiseDifferenceEnumType")
	@Basic( optional = true )
	@Column (name="work_place_promise_difference")
	public EntryRHYWorkplacePromiseDifferenceEnum getWorkPlacePromiseDifference() {
		return workPlacePromiseDifference;
	}

	public void setWorkPlacePromiseDifference(
			EntryRHYWorkplacePromiseDifferenceEnum workPlacePromiseDifference) {
		this.workPlacePromiseDifference = workPlacePromiseDifference;
	}

	/**
	 * Return the value associated with the column: workPlaceViolenceThreat.
	 * @return A Integer object (this.workPlaceViolenceThreat)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYWorkPlaceViolenceThreatsEnumType")
	@Basic( optional = true )
	@Column (name="work_place_violence_threat")
	public EntryRHYWorkPlaceViolenceThreatsEnum getWorkPlaceViolenceThreat() {
		return workPlaceViolenceThreat;
	}

	public void setWorkPlaceViolenceThreat(
			EntryRHYWorkPlaceViolenceThreatsEnum workPlaceViolenceThreat) {
		this.workPlaceViolenceThreat = workPlaceViolenceThreat;
	}

	/**
	 * Return the value associated with the column: yearsChildWelfrForestCare.
	 * @return A Integer object (this.yearsChildWelfrForestCare)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYChildWelfareYearsEnumType")
	@Basic( optional = true )
	@Column (name="years_child_welfr_forest_care")
	public EntryRHYChildWelfareYearsEnum getYearsChildWelfrForestCare() {
		return yearsChildWelfrForestCare;
	}

	public void setYearsChildWelfrForestCare(
			EntryRHYChildWelfareYearsEnum yearsChildWelfrForestCare) {
		this.yearsChildWelfrForestCare = yearsChildWelfrForestCare;
	}

	/**
	 * Return the value associated with the column: yearsJuvenileJustice.
	 * @return A Integer object (this.yearsJuvenileJustice)
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYJuvenileJusticeYearsEnumType")
	@Basic( optional = true )
	@Column (name="years_juvenile_justice")
	public EntryRHYJuvenileJusticeYearsEnum getYearsJuvenileJustice() {
		return yearsJuvenileJustice;
	}

	public void setYearsJuvenileJustice(
			EntryRHYJuvenileJusticeYearsEnum yearsJuvenileJustice) {
		this.yearsJuvenileJustice = yearsJuvenileJustice;
	}

	/**
	 * @return the monthsJuvenileJustice
	 */
	@Type(type = "com.servinglynk.hmis.warehouse.enums.EntryRHYJuvenileJusticeYearsEnumType")
	@Basic( optional = true )
	@Column (name="months_juvenile_justice")
	public EntryRHYJuvenileJusticeYearsEnum getMonthsJuvenileJustice() {
		return monthsJuvenileJustice;
	}

	/**
	 * @param monthsJuvenileJustice the monthsJuvenileJustice to set
	 */
	public void setMonthsJuvenileJustice(
			EntryRHYJuvenileJusticeYearsEnum monthsJuvenileJustice) {
		this.monthsJuvenileJustice = monthsJuvenileJustice;
	}

	/** Field mapping. */
	protected Export export;
	 /**
	 * Return the value associated with the column: export.
	 * @return A Export object (this.export)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = true )
	@JoinColumn(name = "export_id", nullable = true )
	public Export getExport() {
		return this.export;

	}



	 /**
	 * Set the value related to the column: export.
	 * @param export the export value you wish to set
	 */
	public void setExport(final Export export) {
		this.export = export;
	}
   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Entryrhy clone() throws CloneNotSupportedException {

        final Entryrhy copy = (Entryrhy)super.clone();

		copy.setAbuseAndNeglectFamilyMbr(this.getAbuseAndNeglectFamilyMbr());
		copy.setAbuseAndNeglectYouth(this.getAbuseAndNeglectYouth());
		copy.setActiveMilitaryParent(this.getActiveMilitaryParent());
		copy.setAlcoholDrugAbuseFamilyMbr(this.getAlcoholDrugAbuseFamilyMbr());
		copy.setAlcoholDrugAbuseYouth(this.getAlcoholDrugAbuseYouth());
		copy.setAskedOfForcedToExchangeForSex(this.getAskedOfForcedToExchangeForSex());
		copy.setAskedOfForcedToExchangeForSexPastThreeMonths(this.getAskedOfForcedToExchangeForSexPastThreeMonths());
		copy.setCoercedToContinueWork(this.getCoercedToContinueWork());
		copy.setCountOfExchangeForSex(this.getCountOfExchangeForSex());
		copy.setCountOutReachReferralApproaches(this.getCountOutReachReferralApproaches());
		copy.setDateCreated(this.getDateCreated());
		copy.setDateCreatedFromSource(this.getDateCreatedFromSource());
		copy.setDateUpdated(this.getDateUpdated());
		copy.setDateUpdatedFromSource(this.getDateUpdatedFromSource());
		copy.setDeleted(this.isDeleted());
		copy.setEnrollmentid(this.getEnrollmentid());
		copy.setExchangeForSex(this.getExchangeForSex());
		copy.setExchangeForSexPastThreeMonths(this.getExchangeForSexPastThreeMonths());
		copy.setExport(this.getExport());
		copy.setFormerlyWardChildWelfrForestCare(this.getFormerlyWardChildWelfrForestCare());
		copy.setFormerlyWardOfJuvenileJustice(this.getFormerlyWardOfJuvenileJustice());
		copy.setHealthIssuesFamilyMbr(this.getHealthIssuesFamilyMbr());
		copy.setHealthIssuesYouth(this.getHealthIssuesYouth());
		copy.setHouseHoldDynamics(this.getHouseHoldDynamics());
		copy.setHousingIssuesFamilyMbr(this.getHousingIssuesFamilyMbr());
		copy.setHousingIssuesYouth(this.getHousingIssuesYouth());
		copy.setId(this.getId());
		copy.setIncarceratedParent(this.getIncarceratedParent());
		copy.setIncarceratedParentStatus(this.getIncarceratedParentStatus());
		copy.setInsufficientIncomeToSupportYouth(this.getInsufficientIncomeToSupportYouth());
		copy.setLaborExploitPastThreeMonths(this.getLaborExploitPastThreeMonths());
		copy.setMentalDisabilityFamilyMbr(this.getMentalDisabilityFamilyMbr());
		copy.setMentalDisabilityYouth(this.getMentalDisabilityYouth());
		copy.setMentalHealthIssuesFamilyMbr(this.getMentalHealthIssuesFamilyMbr());
		copy.setMentalHealthIssuesYouth(this.getMentalHealthIssuesYouth());
		copy.setMonthsChildWelfrForestCare(this.getMonthsChildWelfrForestCare());
		copy.setParentId(this.getParentId());
		copy.setPhysicalDisabilityFamilyMbr(this.getPhysicalDisabilityFamilyMbr());
		copy.setPhysicalDisabilityYouth(this.getPhysicalDisabilityYouth());
		copy.setProjectGroupCode(this.getProjectGroupCode());
		copy.setReferralSource(this.getReferralSource());
		copy.setSchoolEducationIssuesFamilyMbr(this.getSchoolEducationIssuesFamilyMbr());
		copy.setSchoolEducationIssuesYouth(this.getSchoolEducationIssuesYouth());
		copy.setSexualOrientatiionGenderIdentityFamilyMbr(this.getSexualOrientatiionGenderIdentityFamilyMbr());
		copy.setSexualOrientatiionGenderIdentityYouth(this.getSexualOrientatiionGenderIdentityYouth());
		copy.setSexualOrientation(this.getSexualOrientation());
		copy.setSync(this.isSync());
		copy.setUnemployementFamilyMbr(this.getUnemployementFamilyMbr());
		copy.setUnemployementYouth(this.getUnemployementYouth());
		copy.setUserId(this.getUserId());
		copy.setVersion(this.getVersion());
		copy.setWorkPlacePromiseDifference(this.getWorkPlacePromiseDifference());
		copy.setWorkPlaceViolenceThreat(this.getWorkPlaceViolenceThreat());
		copy.setYearsChildWelfrForestCare(this.getYearsChildWelfrForestCare());
		copy.setYearsJuvenileJustice(this.getYearsJuvenileJustice());
		return copy;
	}



	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();

		sb.append("abuseAndNeglectFamilyMbr: " + this.getAbuseAndNeglectFamilyMbr() + ", ");
		sb.append("abuseAndNeglectYouth: " + this.getAbuseAndNeglectYouth() + ", ");
		sb.append("activeMilitaryParent: " + this.getActiveMilitaryParent() + ", ");
		sb.append("alcoholDrugAbuseFamilyMbr: " + this.getAlcoholDrugAbuseFamilyMbr() + ", ");
		sb.append("alcoholDrugAbuseYouth: " + this.getAlcoholDrugAbuseYouth() + ", ");
		sb.append("askedOfForcedToExchangeForSex: " + this.getAskedOfForcedToExchangeForSex() + ", ");
		sb.append("askedOfForcedToExchangeForSexPastThreeMonths: " + this.getAskedOfForcedToExchangeForSexPastThreeMonths() + ", ");
		sb.append("coercedToContinueWork: " + this.getCoercedToContinueWork() + ", ");
		sb.append("countOfExchangeForSex: " + this.getCountOfExchangeForSex() + ", ");
		sb.append("countOutReachReferralApproaches: " + this.getCountOutReachReferralApproaches() + ", ");
		sb.append("dateCreated: " + this.getDateCreated() + ", ");
		sb.append("dateCreatedFromSource: " + this.getDateCreatedFromSource() + ", ");
		sb.append("dateUpdated: " + this.getDateUpdated() + ", ");
		sb.append("dateUpdatedFromSource: " + this.getDateUpdatedFromSource() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("exchangeForSex: " + this.getExchangeForSex() + ", ");
		sb.append("exchangeForSexPastThreeMonths: " + this.getExchangeForSexPastThreeMonths() + ", ");
		sb.append("formerlyWardChildWelfrForestCare: " + this.getFormerlyWardChildWelfrForestCare() + ", ");
		sb.append("formerlyWardOfJuvenileJustice: " + this.getFormerlyWardOfJuvenileJustice() + ", ");
		sb.append("healthIssuesFamilyMbr: " + this.getHealthIssuesFamilyMbr() + ", ");
		sb.append("healthIssuesYouth: " + this.getHealthIssuesYouth() + ", ");
		sb.append("houseHoldDynamics: " + this.getHouseHoldDynamics() + ", ");
		sb.append("housingIssuesFamilyMbr: " + this.getHousingIssuesFamilyMbr() + ", ");
		sb.append("housingIssuesYouth: " + this.getHousingIssuesYouth() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("incarceratedParent: " + this.getIncarceratedParent() + ", ");
		sb.append("incarceratedParentStatus: " + this.getIncarceratedParentStatus() + ", ");
		sb.append("insufficientIncomeToSupportYouth: " + this.getInsufficientIncomeToSupportYouth() + ", ");
		sb.append("laborExploitPastThreeMonths: " + this.getLaborExploitPastThreeMonths() + ", ");
		sb.append("mentalDisabilityFamilyMbr: " + this.getMentalDisabilityFamilyMbr() + ", ");
		sb.append("mentalDisabilityYouth: " + this.getMentalDisabilityYouth() + ", ");
		sb.append("mentalHealthIssuesFamilyMbr: " + this.getMentalHealthIssuesFamilyMbr() + ", ");
		sb.append("mentalHealthIssuesYouth: " + this.getMentalHealthIssuesYouth() + ", ");
		sb.append("monthsChildWelfrForestCare: " + this.getMonthsChildWelfrForestCare() + ", ");
		sb.append("parentId: " + this.getParentId() + ", ");
		sb.append("physicalDisabilityFamilyMbr: " + this.getPhysicalDisabilityFamilyMbr() + ", ");
		sb.append("physicalDisabilityYouth: " + this.getPhysicalDisabilityYouth() + ", ");
		sb.append("projectGroupCode: " + this.getProjectGroupCode() + ", ");
		sb.append("referralSource: " + this.getReferralSource() + ", ");
		sb.append("schoolEducationIssuesFamilyMbr: " + this.getSchoolEducationIssuesFamilyMbr() + ", ");
		sb.append("schoolEducationIssuesYouth: " + this.getSchoolEducationIssuesYouth() + ", ");
		sb.append("sexualOrientatiionGenderIdentityFamilyMbr: " + this.getSexualOrientatiionGenderIdentityFamilyMbr() + ", ");
		sb.append("sexualOrientatiionGenderIdentityYouth: " + this.getSexualOrientatiionGenderIdentityYouth() + ", ");
		sb.append("sexualOrientation: " + this.getSexualOrientation() + ", ");
		sb.append("sync: " + this.isSync() + ", ");
		sb.append("unemployementFamilyMbr: " + this.getUnemployementFamilyMbr() + ", ");
		sb.append("unemployementYouth: " + this.getUnemployementYouth() + ", ");
		sb.append("userId: " + this.getUserId() + ", ");
		sb.append("version: " + this.getVersion() + ", ");
		sb.append("workPlacePromiseDifference: " + this.getWorkPlacePromiseDifference() + ", ");
		sb.append("workPlaceViolenceThreat: " + this.getWorkPlaceViolenceThreat() + ", ");
		sb.append("yearsChildWelfrForestCare: " + this.getYearsChildWelfrForestCare() + ", ");
		sb.append("yearsJuvenileJustice: " + this.getYearsJuvenileJustice());
		return sb.toString();
	}


	/** Equals implementation.
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;

		if ( this == aThat ) {
			 return true;
		}


		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}

		final Entryrhy that;
		try {
			that = (Entryrhy) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}


		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAbuseAndNeglectFamilyMbr() == null) && (that.getAbuseAndNeglectFamilyMbr() == null)) || (getAbuseAndNeglectFamilyMbr() != null && getAbuseAndNeglectFamilyMbr().equals(that.getAbuseAndNeglectFamilyMbr())));
		result = result && (((getAbuseAndNeglectYouth() == null) && (that.getAbuseAndNeglectYouth() == null)) || (getAbuseAndNeglectYouth() != null && getAbuseAndNeglectYouth().equals(that.getAbuseAndNeglectYouth())));
		result = result && (((getActiveMilitaryParent() == null) && (that.getActiveMilitaryParent() == null)) || (getActiveMilitaryParent() != null && getActiveMilitaryParent().equals(that.getActiveMilitaryParent())));
		result = result && (((getAlcoholDrugAbuseFamilyMbr() == null) && (that.getAlcoholDrugAbuseFamilyMbr() == null)) || (getAlcoholDrugAbuseFamilyMbr() != null && getAlcoholDrugAbuseFamilyMbr().equals(that.getAlcoholDrugAbuseFamilyMbr())));
		result = result && (((getAlcoholDrugAbuseYouth() == null) && (that.getAlcoholDrugAbuseYouth() == null)) || (getAlcoholDrugAbuseYouth() != null && getAlcoholDrugAbuseYouth().equals(that.getAlcoholDrugAbuseYouth())));
		result = result && (((getAskedOfForcedToExchangeForSex() == null) && (that.getAskedOfForcedToExchangeForSex() == null)) || (getAskedOfForcedToExchangeForSex() != null && getAskedOfForcedToExchangeForSex().equals(that.getAskedOfForcedToExchangeForSex())));
		result = result && (((getAskedOfForcedToExchangeForSexPastThreeMonths() == null) && (that.getAskedOfForcedToExchangeForSexPastThreeMonths() == null)) || (getAskedOfForcedToExchangeForSexPastThreeMonths() != null && getAskedOfForcedToExchangeForSexPastThreeMonths().equals(that.getAskedOfForcedToExchangeForSexPastThreeMonths())));
		result = result && (((getCoercedToContinueWork() == null) && (that.getCoercedToContinueWork() == null)) || (getCoercedToContinueWork() != null && getCoercedToContinueWork().equals(that.getCoercedToContinueWork())));
		result = result && (((getCountOfExchangeForSex() == null) && (that.getCountOfExchangeForSex() == null)) || (getCountOfExchangeForSex() != null && getCountOfExchangeForSex().equals(that.getCountOfExchangeForSex())));
		result = result && (((getCountOutReachReferralApproaches() == null) && (that.getCountOutReachReferralApproaches() == null)) || (getCountOutReachReferralApproaches() != null && getCountOutReachReferralApproaches().equals(that.getCountOutReachReferralApproaches())));
		result = result && (((getDateCreated() == null) && (that.getDateCreated() == null)) || (getDateCreated() != null && getDateCreated().equals(that.getDateCreated())));
		result = result && (((getDateCreatedFromSource() == null) && (that.getDateCreatedFromSource() == null)) || (getDateCreatedFromSource() != null && getDateCreatedFromSource().equals(that.getDateCreatedFromSource())));
		result = result && (((getDateUpdated() == null) && (that.getDateUpdated() == null)) || (getDateUpdated() != null && getDateUpdated().equals(that.getDateUpdated())));
		result = result && (((getDateUpdatedFromSource() == null) && (that.getDateUpdatedFromSource() == null)) || (getDateUpdatedFromSource() != null && getDateUpdatedFromSource().equals(that.getDateUpdatedFromSource())));
		result = result && (((getEnrollmentid() == null) && (that.getEnrollmentid() == null)) || (getEnrollmentid() != null && getEnrollmentid().getId().equals(that.getEnrollmentid().getId())));
		result = result && (((getExchangeForSex() == null) && (that.getExchangeForSex() == null)) || (getExchangeForSex() != null && getExchangeForSex().equals(that.getExchangeForSex())));
		result = result && (((getExchangeForSexPastThreeMonths() == null) && (that.getExchangeForSexPastThreeMonths() == null)) || (getExchangeForSexPastThreeMonths() != null && getExchangeForSexPastThreeMonths().equals(that.getExchangeForSexPastThreeMonths())));
		result = result && (((getExport() == null) && (that.getExport() == null)) || (getExport() != null && getExport().getId().equals(that.getExport().getId())));
		result = result && (((getFormerlyWardChildWelfrForestCare() == null) && (that.getFormerlyWardChildWelfrForestCare() == null)) || (getFormerlyWardChildWelfrForestCare() != null && getFormerlyWardChildWelfrForestCare().equals(that.getFormerlyWardChildWelfrForestCare())));
		result = result && (((getFormerlyWardOfJuvenileJustice() == null) && (that.getFormerlyWardOfJuvenileJustice() == null)) || (getFormerlyWardOfJuvenileJustice() != null && getFormerlyWardOfJuvenileJustice().equals(that.getFormerlyWardOfJuvenileJustice())));
		result = result && (((getHealthIssuesFamilyMbr() == null) && (that.getHealthIssuesFamilyMbr() == null)) || (getHealthIssuesFamilyMbr() != null && getHealthIssuesFamilyMbr().equals(that.getHealthIssuesFamilyMbr())));
		result = result && (((getHealthIssuesYouth() == null) && (that.getHealthIssuesYouth() == null)) || (getHealthIssuesYouth() != null && getHealthIssuesYouth().equals(that.getHealthIssuesYouth())));
		result = result && (((getHouseHoldDynamics() == null) && (that.getHouseHoldDynamics() == null)) || (getHouseHoldDynamics() != null && getHouseHoldDynamics().equals(that.getHouseHoldDynamics())));
		result = result && (((getHousingIssuesFamilyMbr() == null) && (that.getHousingIssuesFamilyMbr() == null)) || (getHousingIssuesFamilyMbr() != null && getHousingIssuesFamilyMbr().equals(that.getHousingIssuesFamilyMbr())));
		result = result && (((getHousingIssuesYouth() == null) && (that.getHousingIssuesYouth() == null)) || (getHousingIssuesYouth() != null && getHousingIssuesYouth().equals(that.getHousingIssuesYouth())));
		result = result && (((getIncarceratedParent() == null) && (that.getIncarceratedParent() == null)) || (getIncarceratedParent() != null && getIncarceratedParent().equals(that.getIncarceratedParent())));
		result = result && (((getIncarceratedParentStatus() == null) && (that.getIncarceratedParentStatus() == null)) || (getIncarceratedParentStatus() != null && getIncarceratedParentStatus().equals(that.getIncarceratedParentStatus())));
		result = result && (((getInsufficientIncomeToSupportYouth() == null) && (that.getInsufficientIncomeToSupportYouth() == null)) || (getInsufficientIncomeToSupportYouth() != null && getInsufficientIncomeToSupportYouth().equals(that.getInsufficientIncomeToSupportYouth())));
		result = result && (((getLaborExploitPastThreeMonths() == null) && (that.getLaborExploitPastThreeMonths() == null)) || (getLaborExploitPastThreeMonths() != null && getLaborExploitPastThreeMonths().equals(that.getLaborExploitPastThreeMonths())));
		result = result && (((getMentalDisabilityFamilyMbr() == null) && (that.getMentalDisabilityFamilyMbr() == null)) || (getMentalDisabilityFamilyMbr() != null && getMentalDisabilityFamilyMbr().equals(that.getMentalDisabilityFamilyMbr())));
		result = result && (((getMentalDisabilityYouth() == null) && (that.getMentalDisabilityYouth() == null)) || (getMentalDisabilityYouth() != null && getMentalDisabilityYouth().equals(that.getMentalDisabilityYouth())));
		result = result && (((getMentalHealthIssuesFamilyMbr() == null) && (that.getMentalHealthIssuesFamilyMbr() == null)) || (getMentalHealthIssuesFamilyMbr() != null && getMentalHealthIssuesFamilyMbr().equals(that.getMentalHealthIssuesFamilyMbr())));
		result = result && (((getMentalHealthIssuesYouth() == null) && (that.getMentalHealthIssuesYouth() == null)) || (getMentalHealthIssuesYouth() != null && getMentalHealthIssuesYouth().equals(that.getMentalHealthIssuesYouth())));
		result = result && (((getMonthsChildWelfrForestCare() == null) && (that.getMonthsChildWelfrForestCare() == null)) || (getMonthsChildWelfrForestCare() != null && getMonthsChildWelfrForestCare().equals(that.getMonthsChildWelfrForestCare())));
		result = result && (((getParentId() == null) && (that.getParentId() == null)) || (getParentId() != null && getParentId().equals(that.getParentId())));
		result = result && (((getPhysicalDisabilityFamilyMbr() == null) && (that.getPhysicalDisabilityFamilyMbr() == null)) || (getPhysicalDisabilityFamilyMbr() != null && getPhysicalDisabilityFamilyMbr().equals(that.getPhysicalDisabilityFamilyMbr())));
		result = result && (((getPhysicalDisabilityYouth() == null) && (that.getPhysicalDisabilityYouth() == null)) || (getPhysicalDisabilityYouth() != null && getPhysicalDisabilityYouth().equals(that.getPhysicalDisabilityYouth())));
		result = result && (((getProjectGroupCode() == null) && (that.getProjectGroupCode() == null)) || (getProjectGroupCode() != null && getProjectGroupCode().equals(that.getProjectGroupCode())));
		result = result && (((getReferralSource() == null) && (that.getReferralSource() == null)) || (getReferralSource() != null && getReferralSource().equals(that.getReferralSource())));
		result = result && (((getSchoolEducationIssuesFamilyMbr() == null) && (that.getSchoolEducationIssuesFamilyMbr() == null)) || (getSchoolEducationIssuesFamilyMbr() != null && getSchoolEducationIssuesFamilyMbr().equals(that.getSchoolEducationIssuesFamilyMbr())));
		result = result && (((getSchoolEducationIssuesYouth() == null) && (that.getSchoolEducationIssuesYouth() == null)) || (getSchoolEducationIssuesYouth() != null && getSchoolEducationIssuesYouth().equals(that.getSchoolEducationIssuesYouth())));
		result = result && (((getSexualOrientatiionGenderIdentityFamilyMbr() == null) && (that.getSexualOrientatiionGenderIdentityFamilyMbr() == null)) || (getSexualOrientatiionGenderIdentityFamilyMbr() != null && getSexualOrientatiionGenderIdentityFamilyMbr().equals(that.getSexualOrientatiionGenderIdentityFamilyMbr())));
		result = result && (((getSexualOrientatiionGenderIdentityYouth() == null) && (that.getSexualOrientatiionGenderIdentityYouth() == null)) || (getSexualOrientatiionGenderIdentityYouth() != null && getSexualOrientatiionGenderIdentityYouth().equals(that.getSexualOrientatiionGenderIdentityYouth())));
		result = result && (((getSexualOrientation() == null) && (that.getSexualOrientation() == null)) || (getSexualOrientation() != null && getSexualOrientation().equals(that.getSexualOrientation())));
		result = result && (((getUnemployementFamilyMbr() == null) && (that.getUnemployementFamilyMbr() == null)) || (getUnemployementFamilyMbr() != null && getUnemployementFamilyMbr().equals(that.getUnemployementFamilyMbr())));
		result = result && (((getUnemployementYouth() == null) && (that.getUnemployementYouth() == null)) || (getUnemployementYouth() != null && getUnemployementYouth().equals(that.getUnemployementYouth())));
		result = result && (((getUserId() == null) && (that.getUserId() == null)) || (getUserId() != null && getUserId().equals(that.getUserId())));
		result = result && (((getVersion() == null) && (that.getVersion() == null)) || (getVersion() != null && getVersion().equals(that.getVersion())));
		result = result && (((getWorkPlacePromiseDifference() == null) && (that.getWorkPlacePromiseDifference() == null)) || (getWorkPlacePromiseDifference() != null && getWorkPlacePromiseDifference().equals(that.getWorkPlacePromiseDifference())));
		result = result && (((getWorkPlaceViolenceThreat() == null) && (that.getWorkPlaceViolenceThreat() == null)) || (getWorkPlaceViolenceThreat() != null && getWorkPlaceViolenceThreat().equals(that.getWorkPlaceViolenceThreat())));
		result = result && (((getYearsChildWelfrForestCare() == null) && (that.getYearsChildWelfrForestCare() == null)) || (getYearsChildWelfrForestCare() != null && getYearsChildWelfrForestCare().equals(that.getYearsChildWelfrForestCare())));
		result = result && (((getYearsJuvenileJustice() == null) && (that.getYearsJuvenileJustice() == null)) || (getYearsJuvenileJustice() != null && getYearsJuvenileJustice().equals(that.getYearsJuvenileJustice())));
		return result;
	}

}
